name: A Brief Introduction to Web3
name_cn: Web3 入门指南
slug: a-brief-introduction-to-web3
toc:
- - '#'
  - Web3 简介
- - '#'
  - 目录
- - '##'
  - 第 1 章：去中心化与 Web3
- - '###'
  - 1.1 Web 1.0
- - '###'
  - 1.2 Web 2.0
- - '###'
  - 1.3 Web 3.0
- - '####'
  - 1.3.1 去中心化简介
- - '####'
  - 1.3.2 网络的不同拓扑结构
- - '#####'
  - 1.3.2.1 中心化且非分布式
- - '#####'
  - 1.3.2.2 中心化但分布式
- - '####'
  - 1.3.3 去中心化系统
- - '###'
  - 1.3.4 Web3 案例研究
- - '###'
  - 1.4 总结
- - '##'
  - 第 2 章：区块链
- - '###'
  - 2.1 区块链的类型
- - '####'
  - 2.1.1 公有区块链
- - '####'
  - 2.1.2 私有区块链
- - '####'
  - 2.1.3 许可型区块链
- - '###'
  - 2.2 什么是区块链？
- - '###'
  - 2.3 区块链的构建模块
- - '####'
  - 2.3.1 区块
- - '###'
  - 2.3.2 链
- - '###'
  - 2.3.3 网络
- - '###'
  - 2.4 区块链应用于何处？
- - '###'
  - 2.5 演化
- - '###'
  - 2.6 共识
- - '####'
  - 2.6.1 工作量证明
- - '###'
  - 2.8 加密密钥
- - '###'
  - 2.9 区块链与单向链表的比较
- - '###'
  - 2.10 以太坊
- - '###'
  - 2.11 总结
- - '##'
  - 第 3 章：Solidity
- - '###'
  - 3.1 什么是 Solidity？
- - '###'
  - 3.2 以太坊
- - '####'
  - 以太坊燃料机制
- - '####'
  - 3.2.1 以太坊虚拟机
- - '###'
  - 3.3 智能合约
- - '###'
  - 3.4 理解 Solidity 语法
- - '####'
  - 3.4.1 编译指示
- - '####'
  - 3.4.2 变量
- - '#####'
  - 3.4.2.1 变量命名
- - '#####'
  - 3.4.2.2 变量的作用域
- - '####'
  - 3.4.3 值类型
- - '####'
  - 3.4.4 地址
- - '####'
  - 3.4.5 Solidty 中的运算符
- - '#####'
  - 3.4.5.1 算术运算符
- - '#####'
  - 3.4.5.2 比较运算符
- - '#####'
  - 3.4.5.3 逻辑运算符
- - '#####'
  - 3.4.5.4 赋值运算符
- - '####'
  - 3.4.6 循环
- - '####'
  - 3.4.7 决策流
- - '####'
  - 3.4.8 Solidity 中的函数
- - '#####'
  - 3.4.8.1 函数修饰符
- - '#####'
  - 3.4.8.2 视图函数
- - '#####'
  - 3.4.8.3 纯函数
- - '#####'
  - 3.4.8.4 回退函数
- - '#####'
  - 3.4.8.5 Solidity 中的函数重载
- - '####'
  - 3.4.9 抽象合约
- - '####'
  - 3.4.10 接口
- - '####'
  - 3.4.11 库
- - '####'
  - 3.4.12 事件
- - '####'
  - 3.4.13 Solidity 中的错误处理
- - '####'
  - 3.4.14 Solidity 与地址
- - '#####'
  - 3.4.14.1 以太坊地址
- - '#####'
  - 3.4.14.4 转账函数
- - '#####'
  - 3.4.14.5 合约相关函数
- - '#####'
  - 3.4.14.6 以太坊中的 Gas
- - '#####'
  - 3.4.14.7 以太坊交易成本
- - '###'
  - 3.5 本章小结
- - '##'
  - 第 4 章：钱包与网关
- - '###'
  - 4.1 钱包类型
- - '###'
  - 4.2 那么，什么是测试网？
- - '###'
  - 4.3 MetaMask
- - '####'
  - 4.3.1 安装
- - '###'
  - 4.4 Web3.js
- - '####'
  - 4.4.1 web3-eth
- - '####'
  - 4.4.2 web3-shh
- - '####'
  - 4.4.3 web3-bzz
- - '####'
  - 4.4.4 web3-net
- - '####'
  - 4.4.5 web3-utils
- - '###'
  - 4.5 Infura 设置
- - '####'
  - 4.5.1 通过 Infura 网关与 Ropsten 网络交互
- - '###'
  - 4.6 本章小结
- - '##'
  - 第 5 章：Remix IDE 入门
- - '###'
  - 5.1 Remix IDE
- - '###'
  - 5.2 创建自己的代币
- - '##'
  - 第 6 章：Truffle
- - '###'
  - 6.2.1 合约代码
- - '###'
  - 6.2.2 编译并部署合约
- - '###'
  - 6.3 本章小结
- - '##'
  - 第 7 章：IPFS 与 NFT
- - '###'
  - 7.1 IPFS
- - '####'
  - 7.1.1 IPFS：三万英尺鸟瞰
- - '####'
  - 7.1.2 安装
- - '###'
  - 7.2 ERC-721
- - '###'
  - 7.3 创建 ERC-721 代币并部署至 IPFS
- - '###'
  - 7.4 本章小结
- - '##'
  - 第 8 章：Hardhat
- - '###'
  - 8.1 Hardhat 框架的安装
- - '###'
  - 8.2 Hardhat 工作流程
- - '###'
  - 8.3 智能合约的部署
- - '####'
  - '**图 8-2.** 使用 `hardhat` 部署基于 ERC-20 标准代币的输出结果'
- - '####'
  - '**图 8-3.** Etherscan 上的部署交易视图'
- - '####'
  - '**清单 8-3.** 调用智能合约函数的代码'
- - '####'
  - '**清单 8-4.** 转账代币的代码'
- - '####'
  - '**图 8-4.** 智能合约转账函数调用的 Hardhat 输出'
- - '####'
  - '**图 8-5.** Etherscan 上的智能合约转账交易视图'
- - '####'
  - '**清单 8-5.** 检查账户余额的代码'
- - '###'
  - 8.4 本章小结
- - '##'
  - 索引
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
