name: Blockchain Consensus
name_cn: 区块链共识
slug: blockchain-consensus
toc:
- - '#'
  - 书籍封面
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审阅者
- - '#'
  - 1. 引言
- - '##'
  - 分布式系统
- - '###'
  - 特性
- - '###'
  - 为何构建分布式系统
- - '####'
  - 可靠性
- - '####'
  - 性能
- - '#####'
  - 响应性
- - '####'
  - 吞吐量
- - '####'
  - 资源共享
- - '####'
  - 固有分布性
- - '##'
  - 挑战
- - '###'
  - 容错性
- - '###'
  - 安全性
- - '###'
  - 异构性
- - '###'
  - 分布透明性
- - '###'
  - 时序与同步
- - '####'
  - 全局状态
- - '####'
  - 并发
- - '###'
  - 并行 vs. 分布式 vs. 并发
- - '###'
  - 集中式 vs. 分散式 vs. 分布式
- - '#'
  - 分布式算法
- - '##'
  - 分布式计算的要素、相关术语、概念
- - '###'
  - 进程
- - '###'
  - 事件
- - '###'
  - 状态
- - '###'
  - 全局状态
- - '###'
  - 执行
- - '####'
  - 切割（Cuts）
- - '###'
  - 分布式系统的类型
- - '###'
  - 软件架构模型
- - '####'
  - 客户端-服务器
- - '####'
  - 多服务器架构
- - '####'
  - 代理服务器
- - '####'
  - 点对点架构
- - '###'
  - 分布式系统模型
- - '###'
  - 进程
- - '####'
  - 崩溃-停止故障
- - '####'
  - 遗漏故障
- - '####'
  - 崩溃后恢复
- - '####'
  - 窃听
- - '####'
  - 任意（拜占庭）故障
- - '###'
  - 网络
- - '####'
  - 链路故障
- - '#####'
  - 公平丢失链路
- - '######'
  - 公平丢失
- - '######'
  - 有限重复
- - '######'
  - 无捏造
- - '#####'
  - 顽固链路
- - '######'
  - 顽固投递
- - '######'
  - 无捏造
- - '#####'
  - 完美（可靠）链路
- - '######'
  - 可靠投递
- - '######'
  - 无重复
- - '######'
  - 无捏造
- - '#####'
  - 日志式完美链路
- - '#####'
  - 认证完美链路
- - '#####'
  - 任意链路
- - '###'
  - 同步性与时序
- - '####'
  - 同步
- - '####'
  - 异步
- - '####'
  - 部分同步
- - '####'
  - 最终同步
- - '#####'
  - 形式化定义
- - '###'
  - 对手模型
- - '####'
  - 阈值对手
- - '####'
  - 动态对手
- - '####'
  - 静态对手
- - '####'
  - 被动敌手
- - '#'
  - 时间、时钟与顺序
- - '##'
  - 物理时钟
- - '###'
  - 时钟偏差 vs. 漂移
- - '###'
  - 原子钟
- - '###'
  - 物理时钟的同步算法
- - '####'
  - NTP
- - '##'
  - GPS 作为时间源
- - '##'
  - UTC 时间
- - '##'
  - 分布式系统中的逻辑时钟与物理时钟
- - '###'
  - 物理时钟的类型
- - '###'
  - 集合
- - '###'
  - 关系
- - '###'
  - 偏序
- - '####'
  - 自反性
- - '####'
  - 反对称性
- - '####'
  - 传递性
- - '###'
  - 非自反偏序
- - '####'
  - 非自反性
- - '###'
  - 全序
- - '###'
  - 发生在先关系与因果关系
- - '###'
  - 逻辑时钟
- - '###'
  - 兰波特时钟
- - '##'
  - 向量时钟
- - '#'
  - 故障与容错
- - '##'
  - 崩溃-停止
- - '##'
  - 失效-停止
- - '##'
  - 遗漏故障
- - '###'
  - 发送遗漏
- - '###'
  - 接收遗漏
- - '###'
  - 一般性遗漏
- - '##'
  - 隐蔽故障
- - '##'
  - 计算故障
- - '##'
  - 拜占庭故障
- - '###'
  - 带认证的拜占庭故障
- - '###'
  - 不带认证的拜占庭故障
- - '##'
  - 时序故障
- - '###'
  - 安全性与活性
- - '###'
  - 容错的形式
- - '##'
  - CAP 定理
- - '###'
  - 一致性
- - '###'
  - 可用性
- - '###'
  - 分区容错性
- - '#'
  - 域名系统与分布式共识
- - '##'
  - 分布式系统中的密码学
- - '##'
  - 本章小结
- - '#'
  - 2. 密码学
- - '##'
  - 引言
- - '##'
  - 典型密码系统
- - '###'
  - 密码原语
- - '###'
  - 对称密码学
- - '####'
  - 流密码
- - '####'
  - 分组密码
- - '#####'
  - 电子密码本
- - '#####'
  - 密码块链接
- - '#####'
  - 计数器模式
- - '#####'
  - 密钥流生成模式
- - '#####'
  - 消息认证模式
- - '#####'
  - 密码哈希模式
- - '####'
  - 高级加密标准
- - '####'
  - 一些基础数学知识
- - '#####'
  - 素数
- - '#####'
  - 模算术
- - '#####'
  - 群
- - '#####'
  - 阿贝尔群
- - '#####'
  - 域
- - '#####'
  - 有限域（伽罗瓦域）
- - '#####'
  - 素域
- - '#####'
  - 生成元
- - '###'
  - 公钥密码学
- - '###'
  - Diffie-Hellman 密钥交换
- - '###'
  - 数字签名
- - '####'
  - 实体认证
- - '####'
  - 密钥协商
- - '###'
  - RSA
- - '####'
  - 密钥对生成
- - '####'
  - 加密与解密
- - '####'
  - 密钥生成、加密和解密的示例
- - '###'
  - 椭圆曲线密码学
- - '####'
  - 点加法
- - '####'
  - 点倍乘
- - '#####'
  - 标量点乘
- - '#####'
  - 椭圆曲线离散对数问题
- - '####'
  - 数字签名
- - '#####'
  - 真实性
- - '#####'
  - 不可伪造性
- - '#####'
  - 不可重用性
- - '#####'
  - ECDSA 签名
- - '#####'
  - 多重签名
- - '#####'
  - 门限签名
- - '#####'
  - 聚合签名
- - '#####'
  - 环签名
- - '###'
  - 哈希函数
- - '####'
  - 原像抗性
- - '####'
  - 第二原像抗性
- - '####'
  - 抗碰撞性
- - '####'
  - 安全哈希算法（SHA）的设计
- - '#####'
  - SHA-256 的设计
- - '######'
  - 预处理
- - '####'
  - 哈希计算
- - '####'
  - SHA-3 (Keccak) 的设计
- - '###'
  - 消息认证码
- - '####'
  - 基于哈希的 MACs (HMACs)
- - '##'
  - 可验证延迟函数
- - '##'
  - 可验证随机函数
- - '##'
  - 总结
- - '#'
  - 3. 分布式共识
- - '##'
  - 广播原语
- - '###'
  - 尽力而为广播
- - '####'
  - 有效性
- - '####'
  - 无重复
- - '####'
  - 无凭空创建
- - '###'
  - 可靠广播
- - '####'
  - 有效性
- - '####'
  - 一致性
- - '####'
  - 备注
- - '###'
  - 统一可靠广播
- - '####'
  - Uniform Agreement
- - '####'
  - FIFO 可靠广播
- - '#####'
  - FIFO 投递
- - '###'
  - 因果可靠广播
- - '###'
  - 全序可靠广播或原子可靠广播
- - '####'
  - 有效性
- - '####'
  - 一致性
- - '####'
  - 完整性
- - '####'
  - 全序
- - '###'
  - FIFO 全序广播
- - '####'
  - 概率有效性
- - '####'
  - 完整性
- - '###'
  - 广播与共识之间的关系
- - '##'
  - 协商
- - '###'
  - 可靠广播
- - '###'
  - 全序广播
- - '###'
  - 拜占庭协议问题
- - '####'
  - 基础拜占庭将军问题（BGP）
- - '####'
  - 交互一致性问题
- - '####'
  - 共识问题
- - '##'
  - 共识属性定义
- - '##'
  - 系统模型
- - '###'
  - 分布式系统
- - '###'
  - 时序模型/同步
- - '###'
  - 进程故障
- - '##'
  - 信道可靠性
- - '##'
  - 历史
- - '###'
  - 两将军问题
- - '###'
  - 拜占庭将军问题
- - '##'
  - 复制
- - '###'
  - 主动复制
- - '###'
  - 被动复制
- - '####'
  - 优点与缺点
- - '####'
  - 主备复制
- - '####'
  - 链式复制
- - '###'
  - 状态机复制
- - '####'
  - 相同初始状态
- - '####'
  - 确定性操作
- - '####'
  - 协调性
- - '####'
  - 安全性
- - '####'
  - 活跃性
- - '#####'
  - 线性一致性
- - '#####'
  - 顺序一致性
- - '#####'
  - 最终一致性
- - '#####'
  - 使用较弱广播抽象的 SMR
- - '###'
  - 基础成果
- - '####'
  - 不可能性结果
- - '####'
  - 最小进程数
- - '####'
  - 崩溃故障
- - '####'
  - 拜占庭故障
- - '####'
  - 最小连通性
- - '####'
  - 最小轮数
- - '##'
  - FLP 不可能性
- - '###'
  - 同步性假设
- - '###'
  - 随机预言机
- - '###'
  - 混合模型
- - '###'
  - 故障检测器
- - '####'
  - 强完备性
- - '####'
  - 弱完备性
- - '####'
  - 强准确性
- - '####'
  - 弱准确性
- - '####'
  - 最终强准确性
- - '####'
  - 最终弱准确性
- - '####'
  - 完美故障检测器 P
- - '####'
  - 强故障检测器 S
- - '####'
  - 最终完美故障检测器 – 菱形 P
- - '####'
  - 最终强故障检测器 – 菱形 S
- - '####'
  - 弱故障检测器 W
- - '####'
  - 最终弱故障检测器（菱形 W）
- - '####'
  - 探测器 Q 或 V
- - '####'
  - 最终探测器 Q（菱形 Q）或菱形 V
- - '#####'
  - 领导者选举故障检测器
- - '####'
  - 使用故障检测器解决共识问题
- - '##'
  - 仲裁
- - '###'
  - 崩溃容错仲裁
- - '###'
  - 拜占庭仲裁
- - '###'
  - 读仲裁与写仲裁
- - '##'
  - 我们现在处于什么位置
- - '###'
  - 经典共识
- - '###'
  - 中本聪及后中本聪共识
- - '##'
  - 本章小结
- - '#'
  - 4. 区块链
- - '##'
  - 什么是区块链
- - '###'
  - 外行定义
- - '###'
  - 技术定义
- - '##'
  - 背景
- - '###'
  - 数字现金的创建尝试
- - '####'
  - 第一个区块链？
- - '##'
  - 区块链的优势
- - '##'
  - 区块链的类型
- - '###'
  - 区块链是一种分布式系统
- - '####'
  - CAP 与无需许可区块链
- - '####'
  - CAP 与需许可区块链
- - '####'
  - 区块链账本抽象
- - '#####'
  - 属性
- - '######'
  - 一致性
- - '######'
  - 容错性
- - '######'
  - 最终性
- - '######'
  - 不可篡改性
- - '######'
  - 仅追加
- - '######'
  - 防篡改/篡改证明
- - '######'
  - 有效性
- - '######'
  - 区块链操作的终止保证：`get()`、`append()`、`verify()`
- - '######'
  - 有序性
- - '######'
  - 可验证性
- - '##'
  - 区块链如何工作
- - '##'
  - 区块链的剖析
- - '###'
  - 区块
- - '###'
  - 平台
- - '####'
  - 比特币
- - '#####'
  - 比特币节点与架构
- - '#####'
  - 比特币中的密码学
- - '######'
  - 公钥和私钥
- - '#####'
  - 地址与账户
- - '#####'
  - 交易与 UTXO 模型
- - '#####'
  - 比特币脚本与 Miniscript
- - '###'
  - 区块与区块链
- - '###'
  - 挖矿
- - '###'
  - 作为平台的比特币
- - '##'
  - 以太坊
- - '###'
  - 以太坊网络
- - '####'
  - 以太坊中的密码学
- - '#####'
  - 账户与地址
- - '####'
  - 交易与执行
- - '####'
  - 区块与区块链
- - '#####'
  - 交易树（Transaction Trie）
- - '#####'
  - 世界状态树
- - '#####'
  - 交易收据树
- - '#####'
  - 账户存储树
- - '###'
  - 以太坊中的挖矿
- - '###'
  - 以太坊虚拟机与智能合约
- - '##'
  - 总结
- - '#'
  - 5. 区块链共识
- - '##'
  - 背景
- - '##'
  - 区块链共识
- - '###'
  - 传统 BFT
- - '####'
  - 一致性
- - '####'
  - 有效性
- - '####'
  - 终止性
- - '####'
  - 完整性
- - '#####'
  - 链式进展（活跃性）
- - '#####'
  - 即时不可撤销性
- - '#####'
  - 共识最终性
- - '###'
  - 中本聪共识
- - '####'
  - 一致性
- - '####'
  - 有效性
- - '####'
  - 终止性
- - '####'
  - 共识最终性
- - '####'
  - 链进展（活跃性）
- - '####'
  - 一致性/一致性
- - '####'
  - 最终不可撤销性
- - '##'
  - 系统模型
- - '###'
  - 公有区块链系统模型（无许可）
- - '###'
  - 联盟区块链系统模型（许可）
- - '##'
  - 首个区块链共识机制
- - '###'
  - PoW 的工作原理
- - '####'
  - 工作量证明的教育性解释
- - '####'
  - '`PoW`公式'
- - '####'
  - 矿工的任务
- - '####'
  - 工作量证明的性质
- - '#####'
  - 完备性
- - '#####'
  - 计算复杂——难以计算——生成缓慢
- - '#####'
  - 自动调整成本——动态成本
- - '#####'
  - 快速高效验证——快速验证
- - '#####'
  - 进度无关性
- - '#####'
  - 动态参数的概率方面
- - '###'
  - 攻击者追上概率
- - '###'
  - PoW 算法
- - '###'
  - 博弈论与工作量证明
- - '####'
  - 囚徒困境
- - '#####'
  - 工作量证明与博弈论
- - '####'
  - PoW 与传统 BFT 的相似之处
- - '#####'
  - 公共前缀
- - '#####'
  - 链质量
- - '#####'
  - 链增长
- - '###'
  - 作为状态机复制的 PoW
- - '##'
  - 领导者选举算法
- - '##'
  - 日志复制
- - '###'
  - 新区块传播
- - '###'
  - 区块验证
- - '###'
  - 追加到区块链
- - '####'
  - 分叉解决
- - '#####'
  - 常规分叉
- - '#####'
  - 硬分叉
- - '#####'
  - 软分叉
- - '#####'
  - 拜占庭分叉
- - '#####'
  - Sybil 抗性
- - '###'
  - 区块时间戳的意义
- - '###'
  - 一个注意事项
- - '##'
  - 工作量证明：拜占庭将军问题的一种解决方案
- - '###'
  - 一致性
- - '###'
  - 有效性 – 基于谓词
- - '###'
  - 终止性
- - '##'
  - 工作量证明的担忧
- - '###'
  - 51% 攻击
- - '###'
  - 自私挖矿
- - '###'
  - 竞态攻击
- - '###'
  - 费尼攻击
- - '###'
  - Vector76 攻击
- - '###'
  - 日蚀攻击
- - '###'
  - 环境、社会和治理（ESG）影响
- - '###'
  - 工作量证明的变种
- - '####'
  - CPU 密集型工作量证明
- - '####'
  - 内存密集型工作量证明
- - '##'
  - 总结
- - '#'
  - 6. 早期协议
- - '##'
  - 引言
- - '##'
  - 分布式事务
- - '###'
  - 两阶段提交
- - '###'
  - 三阶段提交
- - '##'
  - 口头消息算法
- - '###'
  - 拜占庭将军问题的签名消息解决方案
- - '##'
  - 部分同步下的 DLS 协议
- - '##'
  - Ben-Or 算法
- - '###'
  - 针对良性故障/崩溃故障的算法——非拜占庭
- - '###'
  - 针对拜占庭故障的 Ben-Or 算法
- - '##'
  - 利用故障检测器达成共识
- - '##'
  - 总结
- - '#'
  - 7. 经典共识算法
- - '##'
  - 视图戳复制
- - '###'
  - 协议步骤
- - '###'
  - 视图变更
- - '##'
  - Paxos
- - '###'
  - 故障场景
- - '###'
  - 安全性与活性
- - '###'
  - 实际应用
- - '###'
  - 变体
- - '###'
  - Multi-Paxos
- - '##'
  - RAFT
- - '###'
  - 领导者选举
- - '###'
  - 日志复制
- - '###'
  - 保证与正确性
- - '##'
  - PBFT
- - '###'
  - 预准备阶段 – 阶段一
- - '###'
  - PBFT 协议详解
- - '####'
  - 准备阶段 – 阶段 2
- - '####'
  - 提交阶段
- - '#####'
  - 提交子协议步骤
- - '###'
  - PBFT 中的证书
- - '####'
  - 消息类型
- - '#####'
  - 视图变更
- - '#####'
  - 检查点子协议
- - '###'
  - PBFT 的优缺点
- - '####'
  - 优势
- - '####'
  - 缺点
- - '###'
  - 安全性与活性
- - '###'
  - 视图内的排序
- - '###'
  - 跨视图的排序
- - '##'
  - 区块链与经典共识
- - '##'
  - 总结
- - '#'
  - 8. 区块链时代协议
- - '##'
  - 引言
- - '##'
  - 权益证明
- - '###'
  - 基于链的 PoS
- - '###'
  - 基于委员会的 PoS
- - '###'
  - 基于 BFT 的 PoS
- - '####'
  - 委托权益证明（Delegated PoS）
- - '####'
  - 流动权益证明（Liquid PoS）
- - '###'
  - 攻击
- - '####'
  - 无成本利益问题（Nothing-at-Stake Problem）
- - '####'
  - 长程攻击（Long-Range Attacks）
- - '####'
  - 其他攻击
- - '##'
  - 以太坊的工作量证明
- - '##'
  - Solana
- - '###'
  - 历史证明
- - '##'
  - Tendermint
- - '###'
  - Tendermint 流程
- - '##'
  - HotStuff
- - '###'
  - 线性视图变更
- - '###'
  - 乐观响应性
- - '###'
  - 链质量
- - '###'
  - 隐藏锁定
- - '###'
  - 心跳机制（Pacemaker）
- - '###'
  - 更好的参与者组织拓扑
- - '####'
  - 工作原理
- - '#####'
  - 准备阶段
- - '#####'
  - 预提交阶段
- - '#####'
  - 提交阶段
- - '#####'
  - 决定阶段
- - '#####'
  - 安全性与活跃性
- - '##'
  - Polkadot
- - '###'
  - Polkadot 的共识机制
- - '####'
  - BABE – 区块链扩展的盲分配协议
- - '#####'
  - 创世阶段
- - '#####'
  - 常规阶段
- - '#####'
  - 纪元更新
- - '###'
  - 安全性与活跃性
- - '####'
  - 链增长
- - '####'
  - 链质量
- - '####'
  - 链密度
- - '####'
  - 共同前缀
- - '###'
  - GRANDPA – 基于 GHOST 的递归祖先衍生前缀共识协议
- - '####'
  - GRANDPA 协议步骤
- - '####'
  - 安全性
- - '####'
  - 活跃性
- - '##'
  - 以太坊 2
- - '###'
  - Casper
- - '####'
  - Casper FFG
- - '#####'
  - 协议步骤
- - '#####'
  - 安全性与活性
- - '##'
  - 总结
- - '#'
  - 9. 量子共识
- - '##'
  - 引言
- - '##'
  - 什么是量子计算机？
- - '###'
  - 量子比特
- - '###'
  - 叠加态
- - '###'
  - 纠缠态
- - '####'
  - 最大协调性
- - '####'
  - 单一配分性
- - '##'
  - 量子门
- - '###'
  - 阿达玛门
- - '###'
  - T 门
- - '###'
  - CNOT
- - '###'
  - Toffoli（CCNOT）
- - '###'
  - Z 门
- - '###'
  - NOT 门
- - '###'
  - 交换门
- - '###'
  - 测量
- - '##'
  - 量子电路
- - '###'
  - 隐形传态电路
- - '###'
  - GHZ 电路
- - '###'
  - W 态电路
- - '##'
  - 量子算法
- - '##'
  - 量子计算复杂度
- - '###'
  - P – 多项式（Polynomial）
- - '###'
  - NP – 非确定性多项式（Nondeterministic Polynomial）
- - '###'
  - BPP – 有界误差概率多项式时间（Bounded Error Probabilistic Polynomial Time）
- - '###'
  - BQP – 有界误差量子多项式时间（Bounded Error Quantum Polynomial Time）
- - '###'
  - PSPACE – 多项式空间（Polynomial Space）
- - '##'
  - 其他量子系统
- - '###'
  - 量子网络（Quantum Networks）
- - '##'
  - 量子互联网
- - '##'
  - 量子分布式系统 – 分布式量子计算
- - '##'
  - 量子区块链
- - '###'
  - 量子密码学
- - '##'
  - 量子共识
- - '###'
  - 快速量子拜占庭协定
- - '##'
  - 如何反驳 FLP 不可能性
- - '###'
  - 增强型分布式共识
- - '####'
  - 量子领导者选举与共识
- - '####'
  - 其他算法
- - '##'
  - 总结
- - '#'
  - 10. 结论
- - '##'
  - 引言
- - '##'
  - 其他协议
- - '###'
  - PoET
- - '###'
  - PoA（权威证明）
- - '###'
  - HoneyBadger BFT（蜜獾拜占庭容错协议）
- - '###'
  - 雪崩协议
- - '###'
  - 基于 DAG 的共识协议
- - '####'
  - 基于区块的 DAG
- - '####'
  - 基于交易的 DAG
- - '###'
  - 潮汐协议
- - '##'
  - 形式化验证
- - '##'
  - 不可能性结果
- - '##'
  - 复杂度与性能
- - '###'
  - 消息复杂度
- - '###'
  - 通信复杂度（比特复杂度）
- - '###'
  - 时间复杂度
- - '###'
  - 空间复杂度
- - '##'
  - 协议对比
- - '###'
  - 网络模型
- - '####'
  - 同步网络
- - '####'
  - 最终同步网络
- - '####'
  - 部分同步网络
- - '####'
  - 弱同步网络
- - '###'
  - 异步
- - '##'
  - 研究方向
- - '##'
  - 总结
