name: BEGINNING ETHEREUM SMART CONTRACTS PROGRAMMING
name_cn: 以太坊智能合约编程入门指南
slug: beginning-ethereum-smart-contracts-programming
toc:
- - '##'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 1. 理解区块链背后的科学：密码学
- - '##'
  - 什么是密码学？
- - '##'
  - 密码学的类型
- - '##'
  - 哈希函数
- - '###'
  - 哈希的用途
- - '###'
  - 在 Python 中实现哈希
- - '#'
  - 输出：559cc2cb0e1998182b4b6343e38611b3757e8a6279d43e9914d74dfb7e7089e6
- - '##'
  - 对称密码学
- - '###'
  - 在 Python 中生成共享密钥
- - '#'
  - 生成共享密钥
- - '#'
  - 返回 base64 编码的二进制格式
- - '#'
  - 每次运行这段代码都会生成一个新的密钥
- - '#'
  - 例如：b'ixXEfrz2NTJlxy1OhxXlsCiFf0Ycg_GL0Cy0MlgTv4U='
- - '###'
  - 执行对称加密
- - '#'
  - 创建 Fernet 类的实例
- - '#'
  - 使用共享密钥加密消息
- - '#'
  - 记得传入一个字节数组
- - '#'
  - 将加密消息写入文件
- - '#'
  - 将共享密钥写入文件
- - '###'
  - 执行对称解密
- - '#'
  - 创建 Fernet 类的实例
- - '#'
  - 从文件中读取并解密已加密的消息
- - '##'
  - 非对称密码学
- - '###'
  - 生成并保存公钥/私钥对
- - '#'
  - 生成私钥
- - '#'
  - 从私钥派生公钥
- - '###'
  - 使用公钥加密
- - '#'
  - 使用公钥加密消息
- - '###'
  - 使用私钥解密
- - '#'
  - 使用私钥解密
- - '#'
  - 解码明文，因为它是字节数组
- - '#'
  - This message is secret.
- - '###'
  - 数字签名：使用私钥签名
- - '#'
  - 'AttributeError: ''_RSAPrivateKey'' object has no attribute ''encrypt'''
- - '#'
  - 使用私钥对消息进行签名
- - '#'
  - 使用 base64 编码打印数字签名
- - '###'
  - 使用公钥验证数字签名
- - '#'
  - 从 base64 解码数字签名
- - '##'
  - 密码学在区块链中的应用
- - '###'
  - 哈希
- - '###'
  - 对称加密与非对称加密
- - '###'
  - 数字签名
- - '##'
  - 总结
- - '#'
  - 2. 理解区块链
- - '##'
  - 区块链背后的动机
- - '###'
  - 信任的寄托
- - '###'
  - 信任问题
- - '###'
  - 利用去中心化解决信任问题
- - '###'
  - 去中心化的例子
- - '#'
  - 区块链作为分布式账本
- - '##'
  - 区块链的工作原理
- - '###'
  - 链接区块
- - '###'
  - 区块链的不可篡改性
- - '###'
  - 共识协议
- - '###'
  - 工作量证明
- - '####'
  - 挖矿过程
- - '#'
  - 双花问题
- - '#'
  - 工作量证明（PoW）
- - '#'
  - 权益证明（PoS）
- - '##'
  - PoW 与 PoS 的比较
- - '#'
  - 更详细的区块链
- - '###'
  - 节点类型
- - '###'
  - 默克尔树与默克尔根
- - '###'
  - 默克尔树与默克尔根的用途
- - '##'
  - 本章小结
- - '#'
  - 3. 使用 Python 实现你自己的区块链
- - '#'
  - 你的概念性区块链实现
- - '##'
  - 获取随机数
- - '##'
  - 安装 Flask
- - '##'
  - 导入各种模块和库
- - '##'
  - 在 Python 中声明类
- - '##'
  - 寻找随机数
- - '#'
  - 使用工作量证明来寻找当前区块的随机数
- - '##'
  - 将区块附加到区块链
- - '#'
  - 创建一个新区块并将其添加到区块链中
- - '###'
  - 添加交易
- - '#'
  - returns the last block in the blockchain
- - '###'
  - 将区块链类公开为 REST API
- - '#'
  - generate a globally unique address for this node
- - '#'
  - instantiate the Blockchain
- - '###'
  - 获取完整区块链
- - '#'
  - return the entire blockchain
- - '###'
  - 执行挖矿
- - '#'
  - obtain the hash of last block in the blockchain
- - '#'
  - using PoW, get the nonce for the new block to be added
- - '#'
  - to the blockchain
- - '#'
  - add the new block to the blockchain using the last block
- - '#'
  - hash and the current nonce
- - '###'
  - 添加交易
- - '#'
  - get the value passed in from the client
- - '#'
  - check that the required fields are in the POST'ed data
- - '#'
  - create a new transaction
- - '##'
  - 测试你的区块链
- - '##'
  - 同步区块链
- - '#'
  - 判断给定的区块链是否有效
- - '###'
  - 使用多节点测试区块链
- - '##'
  - Python 区块链实现的完整代码清单
- - '###'
  - 区块链核心代码
- - '#'
  - generate a globally unique address for this node
- - '#'
  - instantiate the Blockchain
- - '#'
  - return the entire blockchain
- - '##'
  - 总结
- - '#'
  - 4. 创建您自己的私有以太坊测试网络
- - '#'
  - 下载并安装以太坊客户端 Geth
- - '###'
  - 为 macOS 安装 Geth
- - '###'
  - 为 Windows 安装 Geth
- - '###'
  - 为 Linux 安装 Geth
- - '##'
  - 创建私有以太坊测试网络
- - '###'
  - 创世区块
- - '###'
  - 创建用于存储节点数据的文件夹
- - '###'
  - 启动区块链节点
- - '###'
  - 启动节点
- - '####'
  - 创建账户
- - '####'
  - 检查账户余额
- - '####'
  - 停止节点
- - '###'
  - 启动另一个节点
- - '###'
  - 获取节点信息
- - '###'
  - 配对节点
- - '##'
  - 执行挖矿
- - '##'
  - 检查区块
- - '##'
  - 在两个节点上挖矿
- - '##'
  - 在节点之间转账以太币
- - '##'
  - 管理账户
- - '###'
  - 删除账户
- - '###'
  - 设置 Coinbase
- - '##'
  - 总结
- - '#'
  - 5. 使用 MetaMask 加密货币钱包
- - '##'
  - 什么是 MetaMask？
- - '###'
  - MetaMask 的工作机制
- - '###'
  - 安装 MetaMask
- - '###'
  - 设置账户
- - '###'
  - 使用 MetaMask 扩展程序
- - '###'
  - 选择以太坊网络
- - '###'
  - 获取测试以太币
- - '###'
  - 创建额外账户
- - '#'
  - 转移以太币
- - '##'
  - Gas 费
- - '#'
  - 恢复账户
- - '#'
  - 导入和导出账户
- - '##'
  - 导出账户
- - '###'
  - 导入账户
- - '##'
  - 本章小结
- - '#'
  - 6. 智能合约入门
- - '##'
  - 什么是智能合约？
- - '###'
  - 智能合约如何执行
- - '##'
  - 你的第一个智能合约
- - '###'
  - 使用 Remix IDE
- - '###'
  - 编译合约
- - '###'
  - 使用 JavaScript 虚拟机测试智能合约
- - '###'
  - 获取合约的 ABI 和字节码
- - '###'
  - 使用 Goerli 测试网络测试智能合约
- - '##'
  - 本章小结
- - '#'
  - 7. 使用智能合约存储凭证
- - '##'
  - 智能合约作为凭证存储库
- - '###'
  - 创建智能合约
- - '###'
  - 编译合约
- - '###'
  - 部署合约
- - '###'
  - 测试合约
- - '##'
  - 对智能合约进行进一步修改
- - '###'
  - 限制函数访问权限
- - '###'
  - 在智能合约中接受付款
- - '####'
  - 在 Solidity 中指定以太币单位
- - '###'
  - 智能合约中的事件
- - '###'
  - 提取资金
- - '###'
  - 销毁合约
- - '####'
  - 调用 `selfdestruct()` 后会发生什么？
- - '###'
  - 本章小结
- - '#'
  - 8. 使用 web3.js API
- - '#'
  - 什么是 web3.js？
- - '##'
  - 安装 web3.js
- - '##'
  - 使用 MetaMask 测试 web3.js
- - '###'
  - 使用 `web3.js` 与合约交互
- - '##'
  - 总结
- - '#'
  - 9. 使用 Python 开发 Web3 去中心化应用
- - '##'
  - 使用 Python 与以太坊交互
- - '###'
  - 注册 Infura
- - '###'
  - 连接到 Infura
- - '###'
  - 获取区块
- - '#'
  - '7978182'
- - '###'
  - 设置账户
- - '#'
  - 账户 1
- - '#'
  - 账户 2
- - '###'
  - 获取账户余额
- - '###'
  - 在账户之间转账以太币
- - '###'
  - 使用 Python 创建去中心化应用（Dapp）
- - '###'
  - 加载合约
- - '###'
  - Base64 编码
- - '###'
  - 将凭证保存到区块链
- - '#'
  - 包含考试成绩的 JSON 字符串
- - '#'
  - 获取账户的 nonce
- - '#'
  - 估算 gas 费用
- - '#'
  - 构建交易
- - '#'
  - 签署交易
- - '#'
  - 发送交易
- - '#'
  - 等待交易确认
- - '###'
  - 验证结果
- - '#'
  - 估算 gas 费用
- - '#'
  - 构建交易
- - '#'
  - 签署交易
- - '#'
  - 发送交易
- - '#'
  - 创建事件实例
- - '#'
  - 打印 Result 事件的内容
- - '#'
  - 估算 gas 费用
- - '#'
  - 创建事件实例
- - '###'
  - 调用不需要交易的函数
- - '##'
  - 总结
- - '#'
  - 10. 项目：在线彩票
- - '#'
  - 彩票游戏工作原理
- - '##'
  - 定义智能合约
- - '###'
  - 下注数字
- - '###'
  - 设置中奖号码并公布获胜者
- - '###'
  - 获取游戏状态和中奖号码
- - '###'
  - 从合约中提现
- - '##'
  - 测试合约
- - '###'
  - 公布赢家
- - '###'
  - 保存合约的 ABI
- - '###'
  - 将合约部署到测试网
- - '##'
  - 创建 Web 前端
- - '###'
  - 公布中奖号码
- - '###'
  - 提现
- - '##'
  - 完整合约
- - '##'
  - 本章小结
- - '#'
  - 11. 创建您的代币
- - '#'
  - 什么是代币？
- - '##'
  - 币（Coin）与代币（Token）
- - '##'
  - 代币是如何实现的？
- - '##'
  - 铸造新代币
- - '##'
  - 销毁代币
- - '##'
  - 代币合约内部使用的单位
- - '###'
  - ERC-20 代币标准
- - '##'
  - 创建代币合约
- - '###'
  - 覆盖小数位数精度
- - '###'
  - 部署代币合约
- - '###'
  - 将代币添加到 MetaMask
- - '###'
  - 你能用代币做什么？
- - '###'
  - 使用代币进行智能合约支付
- - '##'
  - 以编程方式出售代币
- - '###'
  - 计算购买的代币数量
- - '###'
  - 部署合约
- - '##'
  - 本章小结
- - '#'
  - 12. 使用 ERC-721 创建非同质化代币
- - '#'
  - 什么是 NFT？
- - '##'
  - 所有权 vs. 版权
- - '##'
  - 在哪里购买或出售 NFT？
- - '#'
  - 使用代币合约创建 NFT
- - '##'
  - 谁部署 NFT 代币合约？
- - '##'
  - 使用 ERC-721 创建 NFT
- - '##'
  - 部署 NFT 代币合约
- - '###'
  - 测试 NFT 合约
- - '####'
  - 获取代币的拥有者
- - '####'
  - 准备要作为 NFT 出售的数字资产
- - '####'
  - 铸造 NFT
- - '####'
  - 获取 NFT 代币合约的名称和符号
- - '####'
  - 查找某个地址的 NFT 余额
- - '####'
  - 获取 NFT 的拥有者
- - '####'
  - 获取 NFT 的 TokenURI
- - '####'
  - 将 NFT 转移到另一个账户
- - '####'
  - 转移合约的所有权
- - '##'
  - 本章小结
- - '#'
  - 13. 去中心化金融入门
- - '##'
  - 传统金融的局限性
- - '###'
  - 去中心化金融
- - '###'
  - DeFi 的组成部分
- - '##'
  - 稳定币
- - '###'
  - 稳定币背后的动机
- - '###'
  - 法币抵押稳定币
- - '####'
  - 法币抵押稳定币示例
- - '###'
  - 加密货币抵押稳定币
- - '####'
  - 到底什么是 `DAO`？
- - '####'
  - DAI 的工作原理
- - '####'
  - DAI 如何保持稳定？
- - '####'
  - 加密货币抵押型稳定币示例
- - '####'
  - DAI 的清算
- - '####'
  - 与当铺运作方式的相似性
- - '###'
  - 无抵押型稳定币
- - '####'
  - 无抵押型稳定币示例
- - '#'
  - 加密货币交易所
- - '###'
  - 创建去中心化交易所
- - '###'
  - 创建通证合约
- - '###'
  - 部署通证合约
- - '###'
  - 创建 DEX 合约
- - '###'
  - 为 DEX 注入资金
- - '###'
  - 将 WML 代币兑换为 LWM 代币
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
