name: Practical Blockchains and Cryptocurrencies
name_cn: 区块链与加密货币实践指南
slug: practical-blockchains-and-cryptocurrencies
toc:
- - '##'
  - 目录
- - '#'
  - 引言
- - '#'
  - 排版后的文档
- - '##'
  - 致谢
- - '##'
  - 关于作者 / 关于技术审阅者
- - '#'
  - 1. 货币简史
- - '##'
  - 新石器时代
- - '##'
  - 银行与纸币的诞生
- - '##'
  - 哈瓦拉体系
- - '##'
  - 罗马帝国与通胀的起源
- - '##'
  - 黄金与新大陆的掠夺
- - '##'
  - 金本位制
- - '##'
  - 大萧条与凯恩斯经济学
- - '##'
  - 石油美元体系
- - '##'
  - 在部分准备金银行体系中赚钱
- - '###'
  - 基础货币经济学
- - '##'
  - 比特币登场
- - '##'
  - 比特币的特性及其影响
- - '###'
  - 暗网
- - '##'
  - 结语
- - '#'
  - 2. 加密货币生态系统
- - '##'
  - 以太坊
- - '##'
  - 比特币现金
- - '##'
  - 瑞波币
- - '##'
  - 门罗币
- - '##'
  - 莱特币
- - '##'
  - 基本注意力代币
- - '##'
  - 币安币
- - '##'
  - TRON
- - '##'
  - Tether
- - '##'
  - 加密货币宏观解剖
- - '##'
  - 结论
- - '#'
  - 3. 对称加密
- - '##'
  - 对称加密的工作原理
- - '##'
  - 对称加密算法的设计
- - '###'
  - 高级加密标准
- - '###'
  - 密钥分发问题
- - '##'
  - 伪随机数生成器
- - '##'
  - 结论
- - '#'
  - 4. 密码学哈希函数
- - '##'
  - 密码学哈希简介
- - '##'
  - 密码学哈希函数
- - '###'
  - 固定长度输出属性
- - '###'
  - 抗碰撞性
- - '###'
  - 不可逆性
- - '###'
  - 高效计算性
- - '##'
  - 证明文件被篡改过
- - '###'
  - 安全哈希算法 256 (SHA-256)
- - '###'
  - 一个针对 SHA-256 的 Python 示例
- - '###'
  - RIPEMD-160
- - '##'
  - 消息认证码
- - '##'
  - 结论
- - '#'
  - 5. 公钥密码系统的炼金术
- - '##'
  - 密钥分发问题再探讨
- - '###'
  - 数字签名算法的启发式方法
- - '###'
  - 公钥基础设施
- - '###'
  - RSA 算法
- - '###'
  - Python 代码示例
- - '##'
  - RSA 公钥密码学示例
- - '###'
  - 生成一个 RSA 密钥对
- - '###'
  - 爱丽丝生成一个 RSA 密钥对
- - '###'
  - 爱丽丝的公钥
- - '###'
  - 爱丽丝的公钥（PEM 格式）
- - '###'
  - PEM 格式对密钥进行 Base64 编码
- - '###'
  - 爱丽丝的私钥
- - '###'
  - 爱丽丝的私钥（PEM 格式）
- - '###'
  - 史密斯使用爱丽丝的公钥加密一条消息
- - '###'
  - 消息必须是二进制字符串
- - '###'
  - 爱丽丝使用她的私钥解密史密斯的消息
- - '###'
  - 爱丽丝通过对消息先生成 SHA-256
- - '####'
  - 摘要，然后用她的私钥对其加密来签名一条消息。
- - '###'
  - 字符串消息被转换为二进制字符串
- - '###'
  - 史密斯通过比较从接收到的消息生成的 SHA-256 哈希值
- - '####'
  - 与从爱丽丝收到的签名解密得到的哈希值来验证签名
- - '###'
  - 生成全局唯一标识符
- - '##'
  - 结论
- - '#'
  - 6. 区块链构建者指南
- - '##'
  - 为什么用 Python 编写加密货币？
- - '##'
  - 计算机即区块链
- - '##'
  - 理解区块链
- - '###'
  - 创世区块
- - '###'
  - 区块链数据库
- - '###'
  - 哈希指针：秘密配料
- - '####'
  - 区块链的不可篡改性
- - '####'
  - 构建一个简单的区块链
- - '####'
  - 区块链宇宙
- - '###'
  - 结论
- - '#'
  - 7. 氦气加密货币项目
- - '##'
  - Python 安装与虚拟环境
- - '##'
  - Helium 配置
- - '###'
  - Helium 版本号
- - '###'
  - Helium 硬币的最大数量
- - '###'
  - 最小的 Helium 货币单位
- - '###'
  - Helium 区块大小
- - '###'
  - 最大交易输入数量
- - '###'
  - 最大交易输出数量
- - '###'
  - 锁定时间间隔
- - '###'
  - Coinbase 间隔
- - '###'
  - 随机数
- - '###'
  - 难度值
- - '####'
  - 重定向间隔
- - '####'
  - 挖矿奖励
- - '####'
  - 奖励间隔
- - '##'
  - Helium 配置模块
- - '###'
  - Helium 版本号
- - '###'
  - 可挖掘的最大 Helium 币数量
- - '###'
  - 一个 Helium 币的最小货币单位
- - '###'
  - Helium 区块的最大大小（字节）
- - '###'
  - 交易可被锁定的最大时间（秒）
- - '###'
  - Helium 交易中的最大输入数量
- - '###'
  - Helium 交易中的最大输出数量
- - '###'
  - 从前一个参考区块算起，必须再挖掘多少个新区块后，才能使用前一个参考区块中的 coinbase 交易
- - '###'
  - 挖矿工作量证明计算中的起始 nonce 值
- - '###'
  - 挖矿工作量证明计算中使用的难度值
- - '###'
  - 为调整 DIFFICULTY_NUMBER 而设置的区块重定向间隔
- - '###'
  - 挖矿奖励
- - '###'
  - 挖矿奖励减半的区块间隔
- - '##'
  - 总结
- - '#'
  - 8. Helium 区块链
- - '##'
  - Python 加密包
- - '##'
  - '`rcrypt` 模块解读'
- - '###'
  - '`rcrypt` 模块'
- - '###'
  - 依赖项
- - '###'
  - 导入
- - '####'
  - 导入正则表达式模块
- - '####'
  - 从 cryptodome 包中导入
- - '####'
  - 导入 Python 的调试和日志模块
- - '###'
  - 日志配置
- - '###'
  - 函数
- - '####'
  - '`make_SHA256_hash(msg: ''string'') -> ''string''`'
- - '####'
  - '`validate_SHA256_hash(digest: "string") -> bool`'
- - '####'
  - '`make_RIPEMD160_hash(message: ''byte stream'') -> ''string''`'
- - '####'
  - '`validate_RIPEMD160_hash(digest: ''string'') -> ''bool''`'
- - '####'
  - '`make_ecc_keys()`'
- - '####'
  - '`sign_message(private_key: ''String'', message: ''String'') -> ''string''`'
- - '####'
  - '`verify_signature(public_key: ''String'', msg: ''String'', signature: ''string'')
    -> ''bool''`'
- - '####'
  - '`make_address(prefix: ''string'') -> ''string''`'
- - '####'
  - '`validate_address(address: ''string'') -> bool`'
- - '####'
  - '`make_uuid() -> ''string''`'
- - '##'
  - Pytest 入门指南
- - '##'
  - rcrypt 单元测试
- - '##'
  - Python 日志记录器
- - '##'
  - Helium 区块结构
- - '##'
  - Helium 区块链详解
- - '##'
  - Helium 区块链模块
- - '###'
  - 区块结构
- - '###'
  - 函数
- - '####'
  - '`add_block(block: "dictionary") -> "bool"`'
- - '####'
  - '`serialize_block(block: "dictionary") -> "bool"`'
- - '####'
  - '`read_block(blockno: ''long'') -> "dictionary or False"`'
- - '####'
  - '`blockheader_hash(block: ''dictionary'') -> "False or String"`'
- - '####'
  - '`validate_block(block: "dictionary") -> "bool"`'
- - '####'
  - '`merkle_root(tx_list: "list of transactions", first: "bool") -> "string or False"`'
- - '####'
  - '`merkle_tree(tx_list: "list of transactions", first: "bool") -> "bool or string"`'
- - '##'
  - Helium 区块链单元测试
- - '###'
  - 生成用于测试的合成随机交易
- - '###'
  - 构建三个用于测试的合成区块
- - '##'
  - 结论
- - '#'
  - 9. 加密货币交易处理
- - '##'
  - 公共地址构建
- - '##'
  - 规范交易结构
- - '###'
  - 交易 `vin` 列表
- - '###'
  - 交易 `vout` 列表
- - '###'
  - 交易机制
- - '##'
  - ScriptPubKey 和 ScriptSig 脚本
- - '###'
  - ScriptSig 脚本
- - '###'
  - ScriptPubKey 脚本
- - '###'
  - 脚本签名与脚本公钥的实际操作
- - '##'
  - 多重签名交易
- - '##'
  - 交易手续费
- - '##'
  - 交易验证
- - '##'
  - 总结
- - '##'
  - 参考
- - '#'
  - 10. 默克尔树
- - '##'
  - 树数据结构
- - '##'
  - Merkle 树
- - '##'
  - 在 Helium 中推导默克尔根
- - '###'
  - 如果 start 为 False，则验证是否包含 SHA-256 哈希列表
- - '###'
  - 如果是首次进入该函数，则创建默克尔叶节点
- - '###'
  - 如果 buffer 只有一个元素，则已得到默克尔根
- - '###'
  - 从子节点构建父节点列表
- - '####'
  - 将两个子节点拼接成一个字符串
- - '####'
  - 计算父节点字符串的 SHA-256 哈希值并添加到父节点列表
- - '###'
  - 递归调用本函数，但将 start 标志设置为 False
- - '###'
  - 交易列表不能为空
- - '###'
  - 验证类型是否为列表
- - '###'
  - 验证每个交易的类型是否为字典
- - '###'
  - 交易数量必须为偶数
- - '###'
  - 复制交易列表
- - '###'
  - 将每个交易转换为 JSON 字符串
- - '###'
  - 创建叶节点
- - '##'
  - 默克尔代码的 Pytest 测试
- - '##'
  - 结论
- - '#'
  - 11. 氦气交易处理
- - '##'
  - 交易处理代码解读
- - '###'
  - '`tx.py` 模块文档'
- - '###'
  - 交易结构
- - '###'
  - 函数文档
- - '####'
  - '`create_transaction()`'
- - '####'
  - '`validate_transaction()`'
- - '####'
  - '`validate_vin()`'
- - '####'
  - '`validate_vout()`'
- - '####'
  - '`prevtx_value()`'
- - '####'
  - '`transaction_fee()`'
- - '####'
  - '`unlock_transaction_fragment()`'
- - '##'
  - 交易处理单元测试
- - '###'
  - 合成前期交易
- - '###'
  - 随机化访问列表
- - '###'
  - Vin 测试
- - '###'
  - Vout 测试
- - '###'
  - 交易测试
- - '##'
  - 更新 Helium 区块链模块
- - '###'
  - 验证接收到的区块参数
- - '###'
  - 验证区块中的交易
- - '###'
  - 区块中的第一笔交易是 coinbase 交易
- - '###'
  - 将区块序列化到文件
- - '###'
  - 将区块添加到内存中的区块链
- - '##'
  - 本章小结
- - '#'
  - 12. 链状态
- - '##'
  - 查找未花费的交易值
- - '##'
  - 链状态数据库设计
- - '##'
  - 链状态数据库代码
- - '###'
  - 创建 Helium Chainstate 键值存储
- - '###'
  - Helium 链状态数据库句柄
- - '##'
  - 链状态数据库的 Pytest 测试
- - '###'
  - hchaindb 模块的 Pytest 单元测试
- - '###'
  - 用于合成前一笔交易的全局变量
- - '###'
  - 实例化密钥对
- - '##'
  - 更新 tx 模块
- - '##'
  - '`blk_index` 数据库'
- - '###'
  - '`blk_index` 代码解读'
- - '####'
  - 创建 Helium blk_index 键值存储
- - '####'
  - Helium blk_index 键值存储的句柄
- - '####'
  - 获取区块编号，如果该交易在存储中不存在则返回 False
- - '####'
  - 在存储中保存 transactionid-block no 键值对
- - '##'
  - '`blk_index` 数据库的 Pytest 测试'
- - '##'
  - 更新区块链模块
- - '##'
  - 结论
- - '#'
  - 13. 挖掘加密货币
- - '##'
  - 挖矿过程
- - '##'
  - 挖掘区块
- - '###'
  - 区块高度验证
- - '###'
  - 前序区块验证
- - '####'
  - 定义
- - '####'
  - 算法
- - '###'
  - 工作量证明
- - '##'
  - 难度值
- - '##'
  - 算力计算
- - '##'
  - 分布式共识算法
- - '###'
  - 恶意节点
- - '###'
  - 交易确认
- - '###'
  - 双重支付问题
- - '##'
  - '结论  '
- - '#'
  - '14. Helium 挖矿  '
- - '##'
  - '分布式共识算法详解  '
- - '##'
  - 氦气挖矿代码详解
- - '###'
  - 创世区块没有奖励
- - '###'
  - 确定挖矿奖励
- - '####'
  - 截断为整数
- - '####'
  - 挖矿奖励不能低于最小面额的货币单位
- - '###'
  - 在以下情况下不添加交易：
- - '####'
  - 交易已存在于交易池中
- - '####'
  - 交易存在于链状态中
- - '####'
  - 交易无效
- - '###'
  - 如果交易在交易池中，则返回
- - '###'
  - 如果交易已被记录在链状态数据库中，则不添加
- - '###'
  - 验证传入的交易是否有效
- - '###'
  - 将交易添加到交易池
- - '###'
  - 将交易放置在 P2P 网络上以进一步传播
- - '###'
  - 如果交易池为空，则无法将任何交易放入候选区块
- - '###'
  - 生成矿工用于接收挖矿奖励和交易费用的公私钥对
- - '###'
  - 创建不完整的候选区块头
- - '####'
  - 获取前一个区块头的哈希值
- - '####'
  - 这可以保证区块链的防篡改性
- - '####'
  - 计算候选区块头的大小（以字节为单位）
- - '####'
  - 数字 64 是 SHA-256 十六进制默克尔根的字节大小
- - '####'
  - 默克尔根是在所有交易都包含在候选区块后计算的
- - '####'
  - 为 coinbase 交易预留 1000 字节
- - '###'
  - 区块中的交易列表
- - '###'
  - 获取当前 Unix 时间
- - '###'
  - 从交易池向候选区块添加交易，
- - '####'
  - 直到交易池中的交易耗尽或区块达到其最大允许大小
- - '###'
  - 不处理未来的交易
- - '###'
  - 将交易添加到候选区块
- - '###'
  - 获取之前的交易片段
- - '###'
  - 计算交易费用
- - '###'
  - 计算挖矿奖励
- - '###'
  - 创建一个 coinbase 交易
- - '####'
  - 挖掘大约 100 个区块后才可以领取挖矿奖励
- - '####'
  - 将其转换为时间间隔
- - '####'
  - 创建包含奖励的 vout 元素
- - '###'
  - 循环直到区块被挖出
- - '####'
  - 计算候选区块头的 SHA-256 哈希值
- - '####'
  - 将 SHA-256 哈希字符串转换为 Python 整数
- - '####'
  - 测试以确定区块是否已被挖出
- - '####'
  - 挖矿失败，因此递增 nonce 并重试
- - '###'
  - 将区块添加到 received_blocks 列表并处理列表
- - '####'
  - 计算候选区块头的 SHA-256 哈希值
- - '####'
  - 将 SHA-256 哈希字符串转换为 Python 整数（基数为 10）
- - '####'
  - 测试以确定区块是否已被挖出
- - '###'
  - 测试区块是否已存在于 received_blocks 列表中
- - '###'
  - 验证工作量证明
- - '###'
  - 将 Nonce 恢复为其初始值
- - '###'
  - 验证区块和区块交易
- - '###'
  - 不要将过时的区块添加到区块链
- - '###'
  - 测试区块是否在主区块链或辅助区块链中
- - '###'
  - 将区块添加到 blocks_received 列表
- - '###'
  - 处理 received_blocks 列表中的所有区块
- - '####'
  - 获取一个收到的区块
- - '####'
  - 尝试将区块添加到主区块链
- - '####'
  - 测试主区块链是否必须分叉
- - '####'
  - 如果前一个区块哈希等于区块链头部区块的父区块的哈希值，
- - '#####'
  - 则将该区块添加为父区块的子区块并创建一个辅助区块链。这构成主区块链的分叉
- - '####'
  - 尝试将区块添加到辅助区块链
- - '####'
  - 无法将区块附加到区块链，添加到孤块列表
- - '####'
  - 移除该区块中同样存在于交易池中的任何交易
- - '####'
  - 如果需要，切换主区块链和辅助区块链
- - '#####'
  - 如果辅助区块链比主区块链长，
- - '######'
  - 则将辅助区块链指定为主区块链，主区块链指定为辅助区块链
- - '#####'
  - 如果主区块链至少领先辅助区块链两个区块，
- - '######'
  - 则清空辅助区块链
- - '####'
  - 遍历孤块，尝试将孤块追加到区块链
- - '#####'
  - 尝试追加到主区块链
- - '#####'
  - 尝试追加到辅助区块链
- - '###'
  - 平均每 600 秒挖出一个区块
- - '###'
  - 从交易池中移除已挖矿区块中的交易
- - '##'
  - 氦气挖矿数据结构
- - '###'
  - mempool
- - '###'
  - received_blocks
- - '###'
  - orphan_blocks
- - '###'
  - Blockchain
- - '###'
  - Secondary Blockchain
- - '##'
  - 氦气挖矿函数
- - '###'
  - mining_reward
- - '###'
  - receive_transaction
- - '###'
  - make_candidate_block
- - '###'
  - make_miner_keys
- - '###'
  - add_transaction_fee
- - '###'
  - make_coinbase_transaction
- - '###'
  - remove_mempool_transactions
- - '###'
  - mine_block
- - '###'
  - proof_of_work
- - '###'
  - receive_block
- - '####'
  - '`process_received_blocks`'
- - '####'
  - '`fork_blockchain`'
- - '####'
  - '`swap_blockchains`'
- - '####'
  - '`handle_orphans`'
- - '####'
  - '`remove_received_block`'
- - '####'
  - '`retarget_difficulty_number`'
- - '####'
  - 其他内容
- - '##'
  - 对氦区块链模块的修改
- - '##'
  - 氦挖矿单元测试
- - '###'
  - 合成交易
- - '##'
  - 结论
- - '#'
  - 15. 氦气网络
- - '##'
  - 客户端-服务器模型
- - '##'
  - 点对点网络
- - '##'
  - 启动一个节点
- - '##'
  - 点对点网络上的数据传播
- - '##'
  - 并发挖矿
- - '###'
  - 'start mining in a thread:'
- - '###'
  - $(virtual) python hmining.py
- - '##'
  - 在本地主机上模拟 Helium 网络
- - '###'
  - 仅供测试的虚假地址列表
- - '###'
  - 在本地回环地址 127.0.0.69:8081 上启动节点的网络接口
- - '###'
  - 代码架构说明
- - '####'
  - JSON-RPC 客户端
- - '####'
  - JSON-RPC 服务器
- - '###'
  - 移除所有锁文件
- - '###'
  - 启动链状态数据库
- - '###'
  - 启动 LevelDB 数据库 blk_index
- - '###'
  - 在本地回环地址上启动服务器节点的网络接口
- - '####'
  - 127.0.0.19:8081
- - '###'
  - 启动此节点
- - '###'
  - 启动事件循环
- - '##'
  - RPC 请求格式
- - '##'
  - 发送命令到远程服务器
- - '##'
  - 远程 JSON 服务器响应格式
- - '##'
  - 错误响应格式
- - '##'
  - JSON-RPC 服务器部分
- - '##'
  - 启动服务器
- - '##'
  - 氦气节点网络接口
- - '###'
  - 氦气启动脚本
- - '###'
  - 地址解析
- - '###'
  - 区块链初始化
- - '###'
  - 区块链查询
- - '###'
  - 区块传播
- - '###'
  - 交易传播
- - '###'
  - 节点进程空间
- - '###'
  - 氦气网络接口的 Pytest 测试
- - '####'
  - 测试氦气网络
- - '####'
  - 启动链状态数据库
- - '####'
  - 启动 LevelDB 数据库 blk_index
- - '####'
  - 未花费交易片段值 [{fragmentid:value}]
- - '####'
  - 启动链状态数据库
- - '####'
  - 启动 LevelDB 数据库 blk_index
- - '####'
  - 未花费交易片段值 [{fragmentid:value}]
- - '####'
  - 创建一个用于测试的合成随机交易
- - '####'
  - 接收区块编号和一个指示交易是否为币基交易的谓词
- - '####'
  - 此交易的公钥-私钥对
- - '####'
  - 此交易花费的先前交易片段
- - '####'
  - 构建 vin 数组
- - '####'
  - 创世区块交易没有前置输入。
- - '####'
  - 币基交易没有任何输入
- - '####'
  - 获取一些随机的先前未花费交易
- - '#####'
  - 片段进行花费
- - '####'
  - 创建一个随机 vin 元素
- - '####'
  - 构建 Vout 列表
- - '####'
  - 创世区块
- - '####'
  - 对于非币基交易，我们至少需要一个交易输出
- - '####'
  - 保存交易片段
- - '####'
  - 为此测试清除主区块链和次区块链
- - '####'
  - 为此测试清除主区块链和次区块链
- - '####'
  - 为此测试清除主区块链和次区块链
- - '####'
  - 为此测试清除主区块链和次区块链
- - '####'
  - 区块链中最新区块的高度属性值
- - '####'
  - 表示区块链中有一个区块
- - '####'
  - 区块链中最新区块的高度属性值
- - '####'
  - 表示区块链中有两个区块
- - '####'
  - 为此测试清除主区块链和次区块链
- - '##'
  - 结论
- - '#'
  - 16. 区块链维护
- - '##'
  - 区块链维护
- - '##'
  - Helium 的可靠性工程
- - '###'
  - validate the received block parameters
- - '###'
  - validate the transactions in the block
- - '###'
  - update the chainstate database
- - '###'
  - first transaction in the block is a coinbase transaction
- - '###'
  - serialize the block to a file
- - '###'
  - add the block to the blockchain in memory
- - '###'
  - update the blk_index
- - '###'
  - create the block file and serialize the block
- - '##'
  - 构建模拟区块链
- - '###'
  - 模拟区块链构造器
- - '###'
  - 启动链状态数据库
- - '###'
  - 启动 LevelDB 数据库 blk_index
- - '###'
  - 未花费的交易碎片值 [{fragmentid:value}]
- - '###'
  - 创建一个用于测试的合成随机交易
- - '###'
  - 接收一个区块编号和一个指示交易是否为 coinbase 交易的谓词
- - '###'
  - 该交易的公私钥对
- - '###'
  - 该交易花费的先前交易碎片
- - '###'
  - 构建 vin 数组
- - '###'
  - 创世区块交易没有先前的输入。
- - '###'
  - coinbase 交易没有任何输入
- - '###'
  - 获取一些随机的、先前未花费的交易碎片用于花费
- - '###'
  - 创建一个随机的 vin 元素
- - '###'
  - 构建 Vout 列表
- - '###'
  - 创世区块
- - '###'
  - 对于非 coinbase 交易，我们至少需要一个交易输出
- - '###'
  - 保存交易碎片
- - '###'
  - 构建模拟区块链
- - '##'
  - 目录文件约束
- - '##'
  - 链状态维护
- - '###'
  - 'build_chainstate: Builds the chainstate database from the blockchain files.'
- - '###'
  - start the Chainstate Database
- - '###'
  - test whether the block file exists
- - '###'
  - load the block file into a dictionary object
- - '###'
  - process the vout and vin arrays for each block transaction
- - '###'
  - start the chainstate build
- - '##'
  - blk_index 维护
- - '###'
  - 'build_blk_index: rebuilds the blk_index database from the blockchain'
- - '###'
  - start the blk_index Database
- - '###'
  - test whether the block file exists
- - '###'
  - load the block file into a dictionary object
- - '###'
  - process the transactions in the block
- - '###'
  - start the build_index build
- - '##'
  - 结论
- - '#'
  - 17. Helium 钱包构建
- - '##'
  - 引言
- - '##'
  - 什么是钱包
- - '##'
  - Helium 钱包接口
- - '###'
  - 密钥管理
- - '###'
  - 交易记录
- - '###'
  - 持久化
- - '##'
  - Helium 钱包程序代码
- - '###'
  - 'wallet.rb: Helium 的命令行钱包'
- - '###'
  - 钱包的状态
- - '###'
  - 从区块链中获取接收的值
- - '###'
  - 更新钱包状态
- - '###'
  - 从区块链交易中获取转出的值
- - '###'
  - 更新钱包状态
- - '##'
  - Helium 钱包 Pytest 代码
- - '###'
  - test_wallet.rb
- - '###'
  - 未花费交易片段的值 [{fragmentid:value}]
- - '###'
  - 生成用于测试的随机合成交易
- - '###'
  - 接收区块编号和一个指示交易是否为 Coinbase 交易的谓词
- - '##'
  - '结论  '
- - '#'
  - '18. Helium 测试网  '
- - '##'
  - '实现 Helium 测试网  '
- - '###'
  - '######################################################  '
- - '###'
  - 'start the network interface for the server node on  '
- - '###'
  - 'the localhost loop: 127.0.0.19:8081  '
- - '###'
  - '#####################################################  '
- - '##'
  - '实现 Helium 水龙头  '
- - '##'
  - '结论  '
- - '#'
  - 脚注
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W
- - '###'
  - X, Y, Z
