name: Getting Started with Ethereum
name_cn: 以太坊入门指南
slug: getting-started-with-ethereum
toc:
- - '#'
  - 目录
- - '##'
  - 引言
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. 开始入门
- - '##'
  - 什么是以太坊？
- - '##'
  - 安装 Visual Studio Code
- - '###'
  - 安装 Docker
- - '###'
  - 在 VS Code 上安装区块链开发套件扩展
- - '####'
  - 安装该扩展
- - '##'
  - 安装 Truffle
- - '###'
  - 安装 Truffle
- - '###'
  - 检查 Truffle 安装
- - '##'
  - 安装 Ganache CLI
- - '###'
  - 安装 Ganache
- - '###'
  - 在本地启动 Ganache
- - '##'
  - 安装并设置 MetaMask 钱包
- - '###'
  - 安装钱包
- - '###'
  - 配置钱包
- - '###'
  - 访问您的钱包
- - '###'
  - 查找您的钱包地址
- - '##'
  - 在 Infura 上创建账户
- - '###'
  - 创建新账户
- - '####'
  - 配置您的 Infura 项目
- - '##'
  - 总结
- - '#'
  - 2. Solidity
- - '##'
  - 在 VS Code 上开始 Solidity 项目
- - '###'
  - 创建新项目
- - '###'
  - 编译项目
- - '###'
  - 部署到开发区块链
- - '##'
  - 总结
- - '#'
  - 3. ERC-20：同质化代币
- - '##'
  - 使用 OpenZeppelin 编写一个简单的 ERC-20 代币
- - '###'
  - 准备环境
- - '###'
  - 编写合约
- - '###'
  - 设置 Solidity 编译器版本
- - '###'
  - 编译合约
- - '###'
  - 验证结果
- - '##'
  - 将 ERC-20 代币部署到 Ganache 开发区块链
- - '###'
  - 准备迁移
- - '###'
  - 启动区块链
- - '###'
  - 配置区块链网络
- - '###'
  - 部署合约
- - '###'
  - 将 Ganache 添加到 MetaMask 网络
- - '###'
  - 将代币添加到钱包
- - '##'
  - 创建具有固定供应量的 ERC-20 代币
- - '###'
  - 创建项目
- - '###'
  - 编写固定供应合约
- - '###'
  - 编译合约
- - '###'
  - 启动 Ganache 开发区块链
- - '###'
  - 将合约迁移至 Ganache
- - '###'
  - 配置 MetaMask
- - '###'
  - 将代币添加到 MetaMask
- - '###'
  - 在账户之间转移代币
- - '##'
  - 使用 Infura 将 ERC-20 代币部署到测试网
- - '###'
  - 安装先决条件
- - '###'
  - 设置你的 Infura 项目
- - '###'
  - 设置你的智能合约
- - '###'
  - 配置私钥
- - '###'
  - 部署智能合约
- - '###'
  - 检查你的钱包余额
- - '###'
  - 在 Etherscan 上验证智能合约
- - '##'
  - 将 ERC-20 代币部署到 Polygon 测试网（第 2 层）
- - '###'
  - 安装先决条件
- - '###'
  - 将 Polygon Mumbai 添加到 MetaMask 网络
- - '###'
  - 在 Infura 上激活 Polygon 附加组件
- - '###'
  - 设置你的 Infura 项目
- - '####'
  - 设置你的智能合约
- - '####'
  - 配置网络（使用 Matic 端点）
- - '####'
  - 配置网络（使用 Infura 端点）
- - '####'
  - 配置私钥
- - '####'
  - 部署智能合约
- - '####'
  - 检查钱包余额
- - '####'
  - 在 PolygonScan 上验证智能合约
- - '##'
  - 将 ERC-20 代币部署到 Polygon 主网（第 2 层）
- - '###'
  - 将 Polygon 主网添加到 MetaMask 网络
- - '###'
  - 配置网络（使用 Infura 端点）
- - '###'
  - 部署智能合约
- - '###'
  - 检查钱包余额
- - '###'
  - 在 PolygonScan 上验证智能合约
- - '##'
  - 总结
- - '#'
  - 4. 智能合约的单元测试
- - '##'
  - 为 ERC-20 智能合约编写单元测试
- - '###'
  - 创建新的单元测试文件
- - '###'
  - 为总供应量合约编写测试
- - '###'
  - 为余额合约编写测试断言
- - '###'
  - 运行单元测试
- - '###'
  - 检查单元测试结果
- - '##'
  - 本章小结
- - '#'
  - 5. ERC-721：非同质化代币
- - '##'
  - 使用 Ganache 和 OpenZeppelin 创建你的艺术 NFT
- - '###'
  - 创建项目
- - '####'
  - 配置钱包以签署交易
- - '####'
  - 配置网络
- - '####'
  - 配置 Solidity 编译器
- - '####'
  - 配置私钥
- - '####'
  - 创建徽章图像
- - '####'
  - 将徽章添加到本地 IPFS
- - '####'
  - 将徽章固定到远程 IPFS 节点
- - '####'
  - 创建徽章元数据
- - '####'
  - 编译智能合约
- - '####'
  - 迁移智能合约
- - '####'
  - 实例化智能合约
- - '####'
  - 向钱包授予徽章
- - '####'
  - 在 Etherscan 上检查徽章
- - '#####'
  - 将 NFT 代币添加到你的钱包
- - '##'
  - 在 OpenSea 上出售你的艺术品 NFT
- - '###'
  - 连接到 OpenSea
- - '###'
  - 查看你的徽章
- - '###'
  - 挂牌出售你的徽章
- - '###'
  - 探索清单详情
- - '##'
  - 本章小结
- - '#'
  - 6. 水龙头
- - '##'
  - 从 Ropsten 网络的水龙头获取测试以太币
- - '###'
  - 访问水龙头
- - '###'
  - 等待交易
- - '##'
  - 从 Rinkeby 测试网的水龙头获取测试以太币
- - '###'
  - 准备充值
- - '###'
  - 为钱包充值
- - '###'
  - 检查你的钱包
- - '##'
  - 从 Mumbai 测试网的水龙头获取测试 MATIC
- - '###'
  - 准备充值
- - '###'
  - 为钱包充值
- - '###'
  - 检查你的钱包
- - '##'
  - 从主网的水龙头获取测试 MATIC
- - '###'
  - 准备充值
- - '###'
  - 为钱包充值
- - '###'
  - 检查你的钱包
- - '##'
  - 总结
- - '#'
  - 7. 星际文件系统
- - '##'
  - 创建您的 IPFS 节点
- - '###'
  - 安装节点
- - '###'
  - 配置节点
- - '###'
  - 测试节点
- - '###'
  - 探索您的 IPFS 节点
- - '##'
  - 向 IPFS 添加文件
- - '###'
  - 添加文件
- - '###'
  - 在控制台上查看文件内容
- - '###'
  - 在 Web UI 中检查文件
- - '###'
  - 在浏览器中查看文件内容
- - '##'
  - 设置 IPFS 浏览器扩展
- - '###'
  - 安装浏览器扩展
- - '###'
  - 配置节点类型
- - '###'
  - 启动外部节点
- - '###'
  - 导入文件
- - '##'
  - 在本地节点上固定和取消固定 IPFS 文件
- - '###'
  - 启动本地节点
- - '###'
  - 向节点添加文件
- - '###'
  - 检查文件是否已添加
- - '###'
  - 验证文件已固定
- - '###'
  - 取消固定文件
- - '###'
  - 手动固定文件
- - '##'
  - 使用 Pinata 在远程节点上固定与取消固定文件
- - '###'
  - 在 Pinata 上设置 API 密钥
- - '###'
  - 在终端中将 Pinata 设置为远程服务
- - '###'
  - 向本地 IPFS 节点添加新文件
- - '###'
  - 将文件固定到远程 IPFS 节点
- - '###'
  - 从远程 IPFS 节点取消固定文件
- - '##'
  - 使用 Fleek 在 IPFS 上托管您的网站
- - '###'
  - 登录 Fleek
- - '###'
  - 克隆您现有的仓库
- - '###'
  - 安装 Fleek
- - '###'
  - 初始化 Fleek
- - '###'
  - 部署您的站点
- - '##'
  - 总结
- - '#'
  - 8. Filecoin
- - '##'
  - 如何在 Filecoin 本地节点上保存文件
- - '###'
  - 创建项目
- - '###'
  - 配置 Truffle
- - '###'
  - 添加要保存的图片
- - '###'
  - 安装依赖项
- - '###'
  - 启动本地端点
- - '###'
  - 将文件保存到 Filecoin
- - '##'
  - 总结
- - '#'
  - 9. 以太坊名称服务
- - '##'
  - 注册你的 ENS 以在钱包中接收加密货币、代币或 NFT
- - '###'
  - 搜索你的域名
- - '###'
  - 注册你的名称
- - '###'
  - 管理你的注册名称
- - '###'
  - 检查名称解析
- - '##'
  - 总结
- - '#'
  - 10. Chainlink
- - '##'
  - 使用 Chainlink 预言机在智能合约内获取加密货币价格
- - '###'
  - 创建项目
- - '###'
  - 创建智能合约
- - '###'
  - 创建迁移
- - '###'
  - 设置你的 Infura 项目
- - '###'
  - 配置钱包以签署交易
- - '###'
  - 配置网络
- - '###'
  - 配置 Solidity 编译器
- - '###'
  - 配置私钥
- - '###'
  - 编译智能合约
- - '###'
  - 部署智能合约
- - '####'
  - 从智能合约获取价格信息
- - '##'
  - 总结
- - '#'
  - 11. Nethereum
- - '##'
  - 使用 Nethereum 获取你的以太币余额
- - '###'
  - 创建项目
- - '###'
  - 安装 Web3
- - '###'
  - 创建方法
- - '###'
  - 获取余额
- - '##'
  - 总结
- - '#'
  - 12. 总结
- - '##'
  - 延伸阅读
- - '##'
  - 索引
