name: How to Create a Web3 Startup
name_cn: Web3 创业公司创建指南
slug: how-to-create-a-web3-startup
toc:
- - '##'
  - 前言
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. 为什么是 Web3？
- - '##'
  - Web3 的定义
- - '###'
  - Web1
- - '###'
  - Web2
- - '###'
  - Web3 的催化剂
- - '###'
  - Web3 与加密货币
- - '###'
  - Web3 的弊端
- - '##'
  - 亿万富翁的 Web3 之争
- - '##'
  - Web3 的平台转移
- - '###'
  - 初创公司
- - '##'
  - 结论
- - '#'
  - 2. 核心技术
- - '##'
  - 区块链的起源
- - '###'
  - 比特币
- - '##'
  - 加密货币交易所
- - '###'
  - 加密货币钱包
- - '###'
  - 山寨币
- - '###'
  - 加密货币的价值
- - '###'
  - 以太坊
- - '##'
  - 智能合约开发与区块链平台
- - '###'
  - Solana
- - '###'
  - Near Protocol
- - '###'
  - Avalanche
- - '###'
  - ConsenSys
- - '###'
  - Lido
- - '###'
  - 私有区块链
- - '###'
  - Iron Fish
- - '##'
  - 结论
- - '#'
  - 3. Web3 技术栈
- - '##'
  - Web3 技术栈
- - '###'
  - 第一层
- - '###'
  - 第二层
- - '##'
  - Layer 2 与区块链三难困境
- - '###'
  - IoTeX
- - '###'
  - Mina Ecosystem
- - '###'
  - Mysten Labs
- - '###'
  - StarkWare
- - '###'
  - Matter Labs
- - '###'
  - Optimism
- - '###'
  - Offchain Labs
- - '###'
  - Layer 3
- - '##'
  - Web3 框架与库
- - '###'
  - Web3 编程语言
- - '###'
  - Rust
- - '###'
  - Solidity
- - '###'
  - Vyper
- - '###'
  - QuickNode
- - '###'
  - 开发者观点
- - '##'
  - 结论
- - '#'
  - 4. Web3 团队
- - '##'
  - 初创公司成功所需的关键角色
- - '###'
  - 人才争夺战
- - '###'
  - 开发者布道师
- - '###'
  - 社区经理
- - '###'
  - 总法律顾问
- - '###'
  - 财务或会计经理
- - '###'
  - 前端开发人员
- - '###'
  - 后端开发工程师
- - '###'
  - 区块链或智能合约工程师
- - '###'
  - 安全工程师
- - '###'
  - 招聘
- - '###'
  - 招聘最佳实践
- - '###'
  - 薪酬
- - '####'
  - 注意
- - '###'
  - 技能重塑
- - '##'
  - 结论
- - '#'
  - 5. 去中心化自治组织 (DAO)
- - '##'
  - DAO 的起源
- - '##'
  - DAO 是如何运作的？
- - '###'
  - DAO 的优势
- - '###'
  - DAO 与法律
- - '###'
  - 存在的问题
- - '###'
  - DAO 服务
- - '###'
  - 公益公司
- - '###'
  - MakerDAO
- - '###'
  - Friends with Benefits
- - '###'
  - SailGP
- - '###'
  - Uniswap
- - '##'
  - 结论
- - '#'
  - 6. NFT、游戏与社交网络
- - '##'
  - 消费者初创企业
- - '##'
  - NFT 如何运作？
- - '###'
  - NFT 实例
- - '###'
  - 购买与创建 NFT
- - '###'
  - NFT 的价值
- - '###'
  - NFT 的问题
- - '###'
  - 新的市场进入策略
- - '###'
  - Web3 的社会身份
- - '###'
  - Web3 社交网络
- - '###'
  - Web3 游戏
- - '##'
  - 品牌与 NFT
- - '###'
  - Novel
- - '###'
  - Fractal
- - '###'
  - Magic Eden
- - '###'
  - OpenSea
- - '###'
  - Rarible
- - '###'
  - Pastel Network
- - '###'
  - Rally
- - '##'
  - 结论
- - '#'
  - 7. DeFi (去中心化金融)
- - '##'
  - 什么是 DeFi？
- - '###'
  - DeFi 的 dApp 流程
- - '###'
  - DeFi 生态系统
- - '###'
  - 风险
- - '###'
  - 颠覆
- - '###'
  - 总锁仓价值 (TVL)
- - '###'
  - Tribal
- - '###'
  - Valora
- - '###'
  - TrustToken
- - '###'
  - Ox Labs
- - '##'
  - 结论
- - '#'
  - 8. 元宇宙
- - '##'
  - 什么是元宇宙？
- - '##'
  - 大型科技公司与元宇宙
- - '###'
  - 挑战
- - '###'
  - 元宇宙中的营销
- - '###'
  - 企业应用
- - '###'
  - Genies
- - '###'
  - Now.gg
- - '###'
  - Teslasuit
- - '##'
  - 结论
- - '#'
  - 9. 税收与监管
- - '##'
  - 加密货币税收
- - '###'
  - 税务场景
- - '##'
  - NFT 税务
- - '###'
  - 捐赠
- - '###'
  - 美国国税局 (IRS)
- - '###'
  - 网络安全与监管
- - '###'
  - 加密货币监管会是什么样子？
- - '###'
  - 排版后的内容
- - '##'
  - 律师与游说者
- - '###'
  - CertiK
- - '###'
  - LiquiFi
- - '##'
  - 结论
