name: Unlocking Blockchain on Azure
name_cn: Azure 区块链解锁指南
slug: unlocking-blockchain-on-azure
toc:
- - '#'
  - 地标
- - '##'
  - 引言
- - '###'
  - 本书结构
- - '###'
  - 您将学到什么
- - '###'
  - 本书适合读者
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 1. 区块链：全景解析
- - '##'
  - 定义区块链
- - '###'
  - 为新用户定义
- - '###'
  - 为初学者定义
- - '###'
  - 为专家定义
- - '##'
  - 历史事件链：分布式计算
- - '###'
  - 阶段一：客户端-服务器
- - '###'
  - 阶段二：多层网络架构
- - '###'
  - 阶段三：点对点网络
- - '###'
  - 第四阶段：区块链
- - '#'
  - 区块链术语
- - '#'
  - 区块链是如何工作的？
- - '##'
  - 对于个人而言
- - '##'
  - 在办公室部门内
- - '##'
  - 在跨分公司公司内
- - '###'
  - 在企业集团中
- - '###'
  - 在国家间贸易集团中
- - '###'
  - 在全球范围内
- - '##'
  - 共识算法
- - '#'
  - Azure 与区块链
- - '##'
  - 链上用户授权
- - '##'
  - 现有信息的元数据
- - '##'
  - 需要区块链的流程挑战
- - '##'
  - 业务应用与呈现工具
- - '#'
  - 2. 解码真实世界的区块链
- - '##'
  - 共识与协议
- - '###'
  - 联邦拜占庭协议
- - '###'
  - 权益证明
- - '###'
  - 重要性证明
- - '#'
  - 共享账本
- - '#'
  - 加密
- - '#'
  - 代币
- - '##'
  - 数据流排序
- - '#'
  - 去中心化应用
- - '#'
  - 搭建区块链环境
- - '#'
  - 部署 Azure Blockchain Workbench
- - '#'
  - 3. 区块链交易的相关方面
- - '##'
  - 加密与验证
- - '##'
  - 分布与安全性
- - '###'
  - 分布式数据
- - '###'
  - 分布式处理过程
- - '#'
  - 4. 金融科技中的许可型区块链
- - '##'
  - 国际交易的历史
- - '#'
  - 金融机构中的解码流程设计
- - '##'
  - Hyperledger Composer
- - '###'
  - 'lib: sample.js'
- - '####'
  - 模型：`sample.cto`
- - '####'
  - '`package.json`'
- - '####'
  - '`permissions.acl`'
- - '####'
  - '`README.md`'
- - '###'
  - 运行示例
- - '####'
  - 练习
- - '#'
  - 5. 智能合约
- - '##'
  - 现实生活中的智能合约
- - '###'
  - 案例：购买房产
- - '###'
  - 房地产领域的公链与私链设置
- - '###'
  - 练习
- - '##'
  - 智能合约语言
- - '##'
  - 创建智能合约
- - '##'
  - 汽车：制造、分销、转售、维修
- - '##'
  - 练习
- - '#'
  - 区块链的集成点
- - '#'
  - 6. 数据源：与企业现有系统的集成
- - '##'
  - 结构化数据源
- - '##'
  - SQL 与区块链集成的连接与定义
- - '###'
  - 区块链的 Azure Cosmos DB 集成
- - '###'
  - 用户接入：合规与监管要求
- - '####'
  - 区块链的 GDPR 考量
- - '#####'
  - 目的与同意的定义
- - '####'
  - 主体访问请求 (SAR)
- - '####'
  - 数据泄露通知
- - '####'
  - Azure 蓝图
- - '####'
  - Azure 策略
- - '####'
  - Azure 安全中心
- - '##'
  - 授权：访问控制与安全访问
- - '#'
  - 7. 自动化：智能合约的自动触发与警报流程
- - '##'
  - 整体视图
- - '#'
  - 技术工具
- - '#'
  - 业务需求与去中心化的缘由
- - '#'
  - 面向运维的解决方案架构
- - '##'
  - 用例：跨医院共享患者医疗健康记录
- - '###'
  - GHOSSTTT 协议
- - '####'
  - 治理
- - '####'
  - 高速交易与并发处理
- - '####'
  - 开放或封闭，许可或无许可
- - '####'
  - 存储
- - '####'
  - 代币、交易与信任
- - '#'
  - GHOSSTTT 协议的应用
- - '##'
  - Azure Stack
- - '###'
  - Quorum：EEA 单成员区块链
- - '###'
  - Ether.camp 以太坊区块链开发环境
- - '###'
  - 微软或 Parity 基于权威证明（PoA）的 Azure 以太坊
- - '##'
  - 开发者的技术组件分解视角
- - '###'
  - 工具层
- - '####'
  - 网络 P2P 库
- - '###'
  - 核心区块链框架
- - '####'
  - 微软机密联盟框架（CCF）
- - '###'
  - 隐私与扩展组件
- - '###'
  - 工具元素
- - '###'
  - 前端元素
- - '###'
  - 区块链即服务
- - '####'
  - 方块网络 （Blocknet）
- - '#'
  - 8. 技术架构
- - '##'
  - 为贸易金融设计区块链解决方案架构
- - '#'
  - 第一个挑战
- - '#'
  - 第二个挑战
- - '#'
  - 第三个挑战
- - '###'
  - 第四项挑战
- - '###'
  - 第五项挑战
- - '###'
  - 第六项挑战
- - '###'
  - 基于用户群、地点、实体和对象的规模衡量
- - '####'
  - 用户群与地点
- - '####'
  - 实体与对象
- - '###'
  - 功能密度与覆盖范围
- - '###'
  - 功能性与可扩展性（深度与广度）
- - '###'
  - 计算复杂度与硬件依赖
- - '###'
  - 实施的核心决策
- - '###'
  - 支持扩展与维护的工具
- - '###'
  - 框架
- - '###'
  - 链上与链下结合的架构设计
- - '##'
  - 为内容追踪、许可和版税定义内容分发区块链架构
- - '#'
  - 排版后的文本
- - '##'
  - 实施法律智能合约的架构
- - '#'
  - 9. 应用案例
- - '##'
  - 去中心化客户互动
- - '###'
  - Bill’U：您的个人 ERP
- - '###'
  - 微软 Azure 与星巴克
- - '###'
  - 其他行业
- - '##'
  - 去中心化贸易金融
- - '###'
  - 微软 Azure 与银行
- - '###'
  - 其他金融行业
- - '#'
  - 去中心化 KYC 与信用数据验证
- - '#'
  - 降低欺诈风险与合规成本
- - '#'
  - 贸易活动融资与追踪的新途径
- - '##'
  - 海事行业：保险、采购与贸易
- - '###'
  - 海上保险
- - '#'
  - 海事交易市场
- - '#'
  - 文档签署与记录管理
- - '#'
  - 柯达企业服务概述
- - '#'
  - 10. 谜题与练习
- - '##'
  - 正确理解术语与定义
- - '###'
  - 填字游戏 1
- - '###'
  - 填字游戏 2
- - '###'
  - 填字游戏 3
- - '###'
  - 填字游戏 4
- - '##'
  - 选择适合的共识形式
- - '##'
  - 用例设计挑战
- - '###'
  - 示例解决方案
- - '###'
  - 工作量证明 (Proof of Work)
- - '####'
  - 链上活动 (Activities on-chain)：
- - '####'
  - 优势 (Advantages)：
- - '####'
  - 局限性 (Limitations)：
- - '###'
  - 权益证明 (Proof of Stake)
- - '####'
  - 链上活动 (Activities on-chain)：
- - '####'
  - 优势 (Advantages)：
- - '####'
  - 局限性 (Limitations)：
- - '###'
  - 委托权益证明 (Delegated Proof of Stake)
- - '####'
  - 链上活动 (Activities on-chain)：
- - '####'
  - 优势 (Advantages)：
- - '####'
  - 局限性 (Limitations)：
- - '###'
  - 有向无环图 (Directed Acyclic Graphs, DAG)
- - '####'
  - 链上活动 (Activities on-chain)：
- - '####'
  - 优势 (Advantages)：
- - '####'
  - 局限性 (Limitations)：
- - '###'
  - 联邦拜占庭协议 (Federated Byzantine Agreement, FBA)
- - '####'
  - 链上活动 (Activities on-chain)：
- - '####'
  - 优势 (Advantages)：
- - '####'
  - 局限性 (Limitations)：
- - '###'
  - 重要性证明 (Proof of Importance)
- - '####'
  - 链上活动 (Activities on-chain)：
- - '####'
  - 优势 (Advantages)：
- - '####'
  - 局限性 (Limitations)：
- - '###'
  - 混合链 (Hybrid Chain)
- - '##'
  - 数据与交易 (Data and Transactions)
- - '##'
  - 能源分配 (Energy Allocation)
- - '##'
  - 小工具 (Gadgets)
- - '#'
  - 透明更新与公平贸易
- - '#'
  - JSON 准备
- - '#'
  - 解决痛点
- - '#'
  - 解决方案
- - '##'
  - 填字游戏 1
- - '##'
  - 填字游戏 2
- - '##'
  - 填字游戏 3
- - '##'
  - 填字游戏 4
- - '##'
  - 匹配顺序
- - '#'
  - 权益证明设计挑战
- - '###'
  - 委托权益证明
- - '###'
  - 有向无环图
- - '###'
  - 联邦拜占庭协议
- - '###'
  - 重要性证明
- - '###'
  - 混合链
- - '###'
  - 数据与交易
- - '###'
  - 能源分配
- - '###'
  - 小工具
- - '####'
  - 透明更新与公平交易
- - '##'
  - JSON 准备
- - '###'
  - 状态图
- - '##'
  - 解决痛点
- - '#'
  - 索引
- - '##'
  - A
- - '###'
  - 应用程序架构
- - '###'
  - Bill’U
- - '###'
  - 比特币
- - '###'
  - 区块链
- - '###'
  - 区块链解决方案生命周期
- - '##'
  - C
- - '###'
  - 内容管理平台
- - '##'
  - D
- - '###'
  - 去中心化
- - '###'
  - 去中心化应用（DApps）
- - '###'
  - 去中心化客户互动
- - '###'
  - 去中心化贸易金融
- - '###'
  - 解码流程设计
- - '###'
  - 数字签名
- - '###'
  - 分布式计算
- - '###'
  - 分布式数据
- - '###'
  - 文档签名与记录管理
- - '###'
  - 互联网泡沫
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '###'
  - GHOSSTTT 协议
- - '###'
  - 全球移动通信系统（GSMA）
- - '##'
  - H
- - '###'
  - Hyperledger
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '###'
  - 信用证（LoC）
- - '###'
  - 链接层
- - '##'
  - M, N
- - '###'
  - 医疗记录
- - '###'
  - 多层网络架构
- - '##'
  - O
- - '###'
  - 组织设计
- - '##'
  - P
- - '###'
  - 权益证明
- - '###'
  - 公有区块链
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '###'
  - 智能合约
- - '###'
  - 社交媒体平台
- - '###'
  - Solidity
- - '###'
  - 状态存储
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V, W
- - '##'
  - X, Y, Z
