name: UNDERSTANDING CRYPTO FUNDAMENTALS
name_cn: 加密货币基础理解指南
slug: understanding-crypto-fundamentals
toc:
- - '#'
  - 免责声明
- - '#'
  - 前言
- - '#'
  - 反馈
- - '#'
  - 引言
- - '#'
  - 关于作者 关于技术审校者
- - '#'
  - 第一部分：为何考虑加密货币投资？
- - '##'
  - 1. 货币简史
- - '###'
  - 货币的构成要素
- - '###'
  - 贵金属作为货币
- - '###'
  - 价值存储
- - '###'
  - 从货币到法定通货
- - '###'
  - 纸币的崛起
- - '##'
  - 中央银行与部分准备金银行制度
- - '###'
  - 大萧条
- - '###'
  - 布雷顿森林时代
- - '##'
  - 回归法定货币
- - '##'
  - 加快印钞速度
- - '###'
  - 新冠疫情
- - '##'
  - 接下来往哪走？
- - '###'
  - 史上最高存量-流量比的资产
- - '##'
  - 关键概念
- - '##'
  - 拓展问题
- - '#'
  - 2. 互补货币
- - '###'
  - 结构性失衡
- - '###'
  - 顺周期的货币体系
- - '###'
  - 货币与金融的可持续性
- - '##'
  - 多货币体系
- - '##'
  - 沃格尔实验
- - '###'
  - 瑞士奇迹
- - '##'
  - 货币贬值带来的激励
- - '##'
  - 可能的未来
- - '##'
  - 关键概念
- - '##'
  - 延伸问题
- - '#'
  - 3. 区块链作为向善的力量
- - '###'
  - 去中心化
- - '###'
  - 隐私
- - '###'
  - 包容性
- - '###'
  - 私有财产
- - '###'
  - 言论自由
- - '###'
  - 通货膨胀
- - '###'
  - 环境
- - '####'
  - 可持续性
- - '###'
  - 透明度
- - '###'
  - 流通速度
- - '###'
  - 外汇
- - '###'
  - 会计
- - '###'
  - 共享经济
- - '###'
  - 创作者赋能
- - '##'
  - 关键概念
- - '##'
  - 扩展问题
- - '#'
  - 4. 投资组合管理入门
- - '###'
  - 价格波动
- - '###'
  - 风险与回报
- - '####'
  - 夏普比率
- - '####'
  - 索提诺比率
- - '####'
  - 投资回报的简单分析
- - '###'
  - 相关性与多元化
- - '###'
  - 投资组合经理的信托责任
- - '##'
  - 核心概念
- - '##'
  - 扩展问题
- - '#'
  - 第二部分：什么是加密资产？
- - '#'
  - 5. 新型资产类别的诞生
- - '##'
  - 首个加密资产的诞生：比特币
- - '##'
  - 双重支付问题的解决方案
- - '###'
  - 拜占庭将军问题
- - '###'
  - 拜占庭容错
- - '###'
  - 去中心化货币概念验证：雅浦岛石币
- - '##'
  - 比特币的创世之后
- - '##'
  - 加密平台与智能合约
- - '###'
  - 替代币
- - '##'
  - 关键概念
- - '##'
  - 延伸问题
- - '#'
  - 6. 区块链基础
- - '###'
  - 区块链的主要特征
- - '###'
  - 区块的链条
- - '###'
  - 非对称加密
- - '###'
  - 更新去中心化账本
- - '###'
  - 共识机制
- - '###'
  - 使用工作量证明更新去中心化账本
- - '####'
  - 工作量证明下的区块结构
- - '###'
  - “最长”链永远是对的
- - '###'
  - 软件更新与分叉
- - '####'
  - 主要分叉与区块链概念
- - '###'
  - 公有链与私有链及混合链
- - '###'
  - 区块链会取代所有数据库吗？
- - '###'
  - 在权益证明下更新账本
- - '###'
  - 替代共识机制
- - '###'
  - 去中心化数据 vs. 去中心化交易
- - '###'
  - 为什么区块链与众不同？
- - '##'
  - 关键概念
- - '##'
  - 扩展问题
- - '#'
  - 7. 加密资产分类法
- - '##'
  - 建立加密资产分类法面临的挑战
- - '##'
  - 按形式与功能划分的加密资产分类法
- - '###'
  - 加密货币
- - '####'
  - 数字价值存储
- - '####'
  - 交易媒介
- - '####'
  - 隐私币
- - '####'
  - 稳定币
- - '####'
  - 替代性加密货币分类法
- - '###'
  - 加密商品
- - '####'
  - 平台协议或智能合约平台
- - '####'
  - 互操作性
- - '####'
  - Oracles
- - '###'
  - 加密代币
- - '####'
  - 平台代币
- - '####'
  - 金融服务类加密代币
- - '####'
  - 非金融服务类加密代币
- - '####'
  - Web 3.0 加密代币
- - '####'
  - 非同质化代币
- - '###'
  - 通用加密资产分类标准
- - '###'
  - 数字资产分类标准
- - '####'
  - 全球加密货币分类标准 (GCCS)
- - '####'
  - 分层视角的加密资产技术
- - '####'
  - 加密资产是证券吗？
- - '##'
  - 国际监管格局
- - '##'
  - 关键概念
- - '##'
  - 扩展问题
- - '#'
  - 8. 加密资产的投资类型
- - '##'
  - 加密资产的直接与间接投资
- - '###'
  - 交易所交易基金（ETF）
- - '###'
  - 使用区块链的公司
- - '###'
  - 资产负债表上持有加密资产的公司
- - '###'
  - 提供加密服务的公司
- - '##'
  - 早期加密资产投资
- - '##'
  - 挖矿
- - '###'
  - 传统加密资产挖矿
- - '###'
  - 抗 ASIC 挖矿
- - '###'
  - 矿池
- - '##'
  - 质押
- - '##'
  - 加密货币借贷
- - '##'
  - 流动性挖矿
- - '###'
  - 收益耕作
- - '###'
  - 空投
- - '##'
  - 交易路由
- - '##'
  - 关键概念
- - '##'
  - 延伸问题
- - '#'
  - 第三部分：何时是投资的好时机？
- - '##'
  - 9. 加密货币趋势
- - '###'
  - 比特币价格
- - '####'
  - 比特币“减半”周期
- - '###'
  - 比特币黄金牛市比率
- - '###'
  - 比特币周期反弹
- - '###'
  - 比特币周期持续时间
- - '###'
  - 相对市场主导地位
- - '###'
  - 比特币引领作用
- - '##'
  - 宏观周期与相关性
- - '##'
  - 其他加密周期
- - '##'
  - 技术分析中的图表
- - '###'
  - 理解高德纳的炒作周期
- - '###'
  - 日历效应
- - '###'
  - 恐惧与贪婪指数
- - '###'
  - 采用
- - '##'
  - 关键概念
- - '##'
  - 扩展问题
- - '#'
  - 10. 黄金时代
- - '###'
  - 流动性
- - '###'
  - DEX 的可访问性
- - '###'
  - 第一层互操作性
- - '###'
  - 交易所交易基金（ETF）的可获得性
- - '###'
  - 正式分类法
- - '###'
  - 监管
- - '###'
  - 历史数据
- - '###'
  - 隐私意识
- - '###'
  - 作为支付手段的普及
- - '###'
  - 加密生态系统
- - '##'
  - 关键概念
- - '##'
  - 延伸问题
- - '#'
  - 第四部分：投资哪里？
- - '#'
  - 11. 投资工具
- - '###'
  - 密钥与地址
- - '###'
  - 热钱包与冷钱包
- - '###'
  - 托管钱包与非托管钱包
- - '###'
  - 中心化与去中心化平台
- - '####'
  - 用户界面与交易所
- - '####'
  - 确定性钱包与非确定性钱包
- - '###'
  - 助记词
- - '###'
  - 钱包附加功能
- - '###'
  - Bitcoin Core
- - '###'
  - 钱包安全
- - '###'
  - 安全存储私钥
- - '##'
  - 核心概念
- - '##'
  - 延伸问题
- - '#'
  - 第五部分：如何进行投资？
- - '#'
  - 12. 投资策略
- - '###'
  - 低买高卖
- - '###'
  - 把握市场时机
- - '###'
  - 平均成本法
- - '###'
  - 过滤噪音
- - '###'
  - 税务
- - '###'
  - 借款作为出售的替代方案
- - '###'
  - 行为与心理偏差
- - '####'
  - 确认偏误
- - '####'
  - 损失规避
- - '####'
  - 禀赋效应
- - '####'
  - 保守主义偏见
- - '####'
  - 锚定效应
- - '####'
  - 过度拟合偏见
- - '####'
  - 数据挖掘偏见
- - '####'
  - 样本选择偏见
- - '####'
  - 幸存者偏差
- - '####'
  - 框架偏差
- - '####'
  - 从众行为偏差
- - '####'
  - 预测过度自信偏差
- - '####'
  - 规模偏差与 ESG 偏差
- - '##'
  - 关键概念
- - '##'
  - 拓展问题
- - '#'
  - 13. 非金融风险管理
- - '###'
  - “51% 攻击”风险
- - '###'
  - 量子计算
- - '###'
  - 政府风险
- - '###'
  - 开发者风险
- - '###'
  - 社区分歧风险
- - '###'
  - 挖矿中心化风险
- - '###'
  - 所有权集中风险
- - '###'
  - 监管风险
- - '###'
  - 平台风险
- - '###'
  - 托管风险
- - '###'
  - 预言机风险
- - '###'
  - DDoS 攻击
- - '###'
  - 诈骗与市场操纵
- - '##'
  - 去中心化保险
- - '##'
  - 关键概念
- - '##'
  - 拓展问题
- - '#'
  - 14. 金融风险管理
- - '###'
  - 信用风险
- - '###'
  - 流动性风险
- - '###'
  - 市场风险
- - '###'
  - 风险价值（VaR）
- - '####'
  - 分析法 VaR
- - '####'
  - 历史 VaR
- - '####'
  - 蒙特卡洛 VaR
- - '####'
  - VaR 指标的特性
- - '###'
  - 罗伊安全第一准则
- - '###'
  - 亏损风险
- - '###'
  - 预期亏损
- - '###'
  - 回测
- - '####'
  - 压力测试
- - '##'
  - 关键概念
- - '##'
  - 扩展问题
- - '#'
  - 第六部分：存在哪些估值方法？
- - '##'
  - 15. 评估框架
- - '###'
  - 该资产解决了什么问题？
- - '###'
  - 该问题有多重要？
- - '###'
  - 该资产如何解决问题？
- - '###'
  - 哪个候选者最能解决这个市场的问题？
- - '###'
  - 资产背后的团队有多可靠？
- - '###'
  - 当地监管环境如何？
- - '###'
  - 代币经济是否合理？
- - '###'
  - 评级机构如何评估加密货币资产？
- - '###'
  - 加密货币资产的选择
- - '##'
  - 关键概念
- - '##'
  - 延伸问题
- - '#'
  - 16. 加密资产的价值投资
- - '##'
  - 结合多种估值方法
- - '##'
  - 未来现金流的净现值
- - '###'
  - 基于倍数的估值
- - '##'
  - 资产价值、盈利能力与成长价值
- - '###'
  - 基于重置成本的资产价值
- - '###'
  - 基于质押奖励的盈利价值
- - '###'
  - 评估增长
- - '###'
  - 衡量和评估加密资产的使用情况
- - '###'
  - 基于使用情况的增长衡量
- - '###'
  - 将供应纳入估值考量
- - '###'
  - 存量-流量模型
- - '###'
  - 存量-流量跨资产（S2FX）模型
- - '###'
  - 基于可比资产的估值
- - '###'
  - 网络价值与交易量比率
- - '###'
  - 加密资产背后的其他基本面指标
- - '####'
  - 支点指数
- - '####'
  - 将比特币作为网络安全协议进行估值
- - '####'
  - 非基于基本面的估值方法
- - '####'
  - 关键概念
- - '####'
  - 拓展问题
- - '#'
  - 17. 结语
- - '##'
  - 回顾过去
- - '###'
  - 展望未来
- - '#'
  - 第七部分 附录
- - '#'
  - 加密资产的前身
- - '###'
  - 匿名电子现金与 DigiCash：1982 年
- - '###'
  - 用于为文档添加时间戳的安全区块链表：1991 年
- - '###'
  - 永恒服务：1996 年
- - '###'
  - 哈希现金：1997 年
- - '###'
  - 比特黄金：1998 年
- - '###'
  - B-money：1998 年
- - '#'
  - 比特币的重置成本估值
- - '#'
  - 应用于加密领域的金融产品
- - '###'
  - 杠杆与保证金交易
- - '###'
  - 衍生品产品
- - '####'
  - 看涨期权与看跌期权
- - '####'
  - 期货合约
