name: NFTs for Business
name_cn: 商业的NFT
slug: nfts-for-business
toc:
- - '#'
  - 去中心化的黎明
- - '#'
  - 本书概览
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 第1章 NFT 解决的问题
- - '##'
  - 引言
- - '###'
  - 稀缺性
- - '###'
  - 所有权
- - '###'
  - 真实性
- - '###'
  - 来源出处
- - '###'
  - 版税
- - '##'
  - 总结
- - '#'
  - 第2章 NFT 背后的技术
- - '##'
  - 区块链基础
- - '###'
  - 应对挑战
- - '####'
  - 密码学与加密
- - '####'
  - 智能合约
- - '####'
  - 智能合约与预言机
- - '##'
  - 概述
- - '#'
  - 第3章 创建与出售 NFT
- - '##'
  - 特性
- - '###'
  - 变量
- - '####'
  - 内在变量
- - '####'
  - 外在变量
- - '###'
  - 实用性
- - '###'
  - 其他变量功能
- - '###'
  - 文件大小
- - '###'
  - 存储考量
- - '###'
  - 内容与区块链选择
- - '##'
  - 钱包
- - '##'
  - 市场平台
- - '###'
  - 买卖基础
- - '###'
  - 选择市场
- - '####'
  - 交易详情
- - '###'
  - 出售
- - '####'
  - 铸造与白名单
- - '##'
  - 总结
- - '#'
  - 第4章 NFT 对艺术界的颠覆与创新
- - '##'
  - NFT 在艺术界的崛起
- - '###'
  - 早期 NFT 艺术项目及其对艺术界的影响
- - '###'
  - 知名艺术家和品牌对 NFT 的采用
- - '###'
  - NFT 对艺术家和收藏家的好处
- - '####'
  - 经济收益
- - '####'
  - 来源与认证
- - '####'
  - 通过民主化为新兴艺术家拓展机会
- - '####'
  - 数字艺术对收藏家的吸引力
- - '###'
  - 围绕 NFT 在艺术界的争议
- - '####'
  - 环境担忧
- - '####'
  - 艺术完整性与真实性
- - '####'
  - 艺术与文化的商品化
- - '####'
  - 排他性与可及性
- - '###'
  - 艺术家与收藏家的策略
- - '##'
  - 总结
- - '#'
  - 第5章 游戏行业与 NFT
- - '##'
  - 游戏对 NFT 的处理方式
- - '##'
  - 发行商对 NFT 的态度
- - '##'
  - 区块链游戏的优势
- - '##'
  - 去中心化市场与区块链游戏
- - '###'
  - 安全性与抗审查
- - '###'
  - 互操作性与变现能力
- - '##'
  - 回顾
- - '##'
  - 总结
- - '#'
  - 第6章 音乐产业与 NFT
- - '##'
  - NFT 与音乐产业：一段不断发展的爱情故事
- - '###'
  - 对音乐人而言：掌控权、报酬与联系
- - '###'
  - 对粉丝而言：独特性、所有权与投资
- - '##'
  - 权力格局变迁与粉丝文化重塑
- - '##'
  - 制定策略
- - '###'
  - 界定 NFT 机遇
- - '###'
  - 制定 NFT 策略
- - '###'
  - 考虑风险并加以缓解
- - '###'
  - 值得关注的音乐 NFT 市场（截至 2023 年）
- - '##'
  - 总结
- - '#'
  - 第7章 其他应用场景
- - '##'
  - 理解 NFT
- - '##'
  - 数字人工制品的认知与机遇
- - '###'
  - 方法论
- - '###'
  - 应用与用例
- - '####'
  - 活动领域
- - '####'
  - 餐饮
- - '##'
  - 时尚
- - '###'
  - 当前实现的一个示例
- - '##'
  - 供应链
- - '###'
  - 当前实施案例
- - '##'
  - 总结
- - '#'
  - 第8章 NFT 的未来
- - '##'
  - 三个网络时代的故事
- - '###'
  - 回到未来
- - '###'
  - 超越炒作
- - '####'
  - 艺术与收藏品
- - '####'
  - 音乐与娱乐
- - '####'
  - 游戏与虚拟世界
- - '####'
  - 分式所有权与流动性
- - '####'
  - 数字身份与个人品牌
- - '###'
  - 挑战与潜在解决方案
- - '####'
  - 缺乏认知与教育
- - '####'
  - 信任与验证
- - '####'
  - 市场投机与波动性
- - '####'
  - 技术复杂性
- - '####'
  - 可扩展性与网络拥堵
- - '####'
  - 版权与知识产权挑战
- - '###'
  - 环境问题
- - '##'
  - 摘要
- - '#'
  - 第9章 发掘 NFT 的趋势与其他应用
- - '##'
  - NFT 与知识产权的未来
- - '##'
  - 房地产与实物资产中的 NFT
- - '##'
  - NFT 与去中心化金融 (DeFi)
- - '##'
  - 未来的 NFT 平台
- - '##'
  - NFT 与元宇宙
- - '###'
  - 关注要点
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y
- - '##'
  - Z
