name: Introducing Ethereum and Solidity
name_cn: 以太坊与Solidity入门指南
slug: introducing-ethereum-and-solidity
toc:
- - '#'
  - 以太坊与 Solidity 入门
- - '##'
  - 加密货币与区块链编程基础（面向初学者）
- - '#'
  - 内容一览
- - '#'
  - 关于作者与关于技术审校者
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校者
- - '#'
  - 第 1 章：弥合区块链知识鸿沟
- - '##'
  - “区块链点名！”
- - '##'
  - 以太坊的用途
- - '###'
  - 注意：什么是协议？
- - '##'
  - 区块链的三个组成部分
- - '##'
  - 以太坊预设多链共存
- - '##'
  - “这是骗局，就像比特币一样！”
- - '##'
  - 以太币：一种货币与商品
- - '###'
  - 格雷欣法则
- - '###'
  - 通往更优货币之路
- - '###'
  - 加密经济学与安全性
- - '###'
  - 回到过去的美好时光
- - '###'
  - 加密混沌
- - '##'
  - 力量源于协议
- - '###'
  - 注意
- - '###'
  - 你可以构建无需信任的系统
- - '##'
  - 智能合约（真正）的作用
- - '###'
  - 用于价值的对象与方法
- - '###'
  - 只需添加商业逻辑
- - '###'
  - 内容创作
- - '###'
  - 数据在哪里？
- - '###'
  - 什么是挖矿？
- - '###'
  - 以太币与电价
- - '#'
  - 深入理解 EVM
- - '###'
  - 注意
- - '##'
  - Mist 浏览器
- - '###'
  - 浏览器 vs. 钱包或密钥环
- - '###'
  - Solidity 有点像 JavaScript，但……
- - '##'
  - 以太坊的用武之地
- - '###'
  - 批判性审视
- - '####'
  - “绝无停机、审查或第三方干扰的可能”
- - '####'
  - “为物联网提供安全、自由、开放的平台”
- - '####'
  - “为社区和企业实现透明治理”
- - '####'
  - “为您处理用户身份验证和安全支付，以及消息传递甚至去中心化存储”
- - '####'
  - “无需注册或支付应用托管费；全球首个零基础设施平台”
- - '###'
  - 智能合约开发现状
- - '####'
  - 山寨币
- - '####'
  - 为你的项目筹集资金
- - '##'
  - 决定你的定位
- - '###'
  - 给新程序员的一点说明
- - '####'
  - 备注
- - '###'
  - 以太坊是免费且开源的
- - '##'
  - EVM 将长存
- - '##'
  - 你今天可以构建什么
- - '###'
  - 私有链与公有链
- - '####'
  - 发送和接收以太币
- - '####'
  - 编写智能合约
- - '####'
  - 创建可证明公平的应用程序
- - '####'
  - 启动你自己的代币
- - '###'
  - 去中心化数据库的承诺
- - '###'
  - 下一步：新的工作方式
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 2 章：Mist 浏览器
- - '##'
  - 前言：钱包作为一种计算隐喻
- - '##'
  - 你的地址是什么？
- - '###'
  - 注意
- - '##'
  - 我的以太币在哪里？
- - '##'
  - 银行柜员隐喻
- - '###'
  - 在加密货币领域，你自主持有资产
- - '###'
  - 可视化以太坊交易
- - '####'
  - (图 2-1) 复写机在原理上与区块链相似：许多机器协同工作，将相似的数据写入相似的本地数据库。在比特币和以太坊中，技术创新在于这些状态变更可能由于网络延迟而顺序错乱，而网络能够将它们协调统一到单个账本中。
- - '##'
  - 与银行业历史的决裂
- - '#'
  - 加密技术如何构建信任
- - '##'
  - 系统要求
- - '###'
  - 关于 Eth.guide 与本书的更多信息
- - '###'
  - 面向开发者的工具
- - '###'
  - 命令行节点
- - '####'
  - 注
- - '##'
  - 推荐：将 Parity 与 Geth 结合使用
- - '####'
  - 注
- - '##'
  - 最后，进入 Mist！
- - '###'
  - 下载与安装 Mist
- - '####'
  - (图 2-2) 在 GitHub 上的以太坊项目中，点击下载适用于你操作系统的可执行文件，或下载源代码自行编译
- - '####'
  - 注
- - '###'
  - 配置 Mist
- - '####'
  - (图 2-3) 主网络也称为主链。测试网络则是一个沙盒环境，用于使用假以太币进行测试和调试合约。
- - '####'
  - (图 2-4) 以太坊众筹于 2014 年举行，参与者有权获得代表以太币的文件。如果您未参与，请点击“跳过”选项。
- - '####'
  - (图 2-5) 接下来，选择一个密码
- - '####'
  - 注意
- - '####'
  - (图 2-6) 在此处您可以看到新地址。您还可以存入比特币，通过 Shapeshift.io API 将其转换为以太币。
- - '####'
  - (图 2-7) 这需要一些时间。完成后您的账户将显示出来。
- - '###'
  - 查找您的新地址
- - '###'
  - 发送和接收以太币
- - '####'
  - (图 2-8) Mist 中的“发送”对话框使您无需使用命令行界面即可轻松发送、接收和检查以太币余额。
- - '####'
  - 注意
- - '###'
  - 理解以太坊账户类型
- - '###'
  - 备份与恢复密钥
- - '###'
  - 使用纸钱包
- - '###'
  - 使用移动钱包
- - '#'
  - 处理消息与交易
- - '##'
  - 交易改变状态
- - '##'
  - 编辑全局数据库
- - '#'
  - 那么，什么是区块链？
- - '##'
  - 为交易付费
- - '##'
  - 理解面额单位
- - '###'
  - (表 2-1) 以太币面额。左侧的“单位”列中，括号内给出了对应的比特币面额
- - '##'
  - 获取以太币
- - '#'
  - 加密货币中的匿名性
- - '##'
  - 区块链浏览器
- - '####'
  - (图 2-10) 所有以太币和比特币交易都是公开的。一些用户通过为每笔交易创建新账户来避免其公钥与身份关联。另一些用户则多年使用同一个公钥，将其用作接受捐赠或其他形式贡献的渠道。
- - '####'
  - 注意
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 3 章：以太坊虚拟机
- - '##'
  - 以太坊虚拟机（EVM）是一台全球性计算机，任何人都可使用，只需支付少量费用（以以太币计价）
- - '#'
  - 昨日的中央银行网络
- - '##'
  - 究竟什么是虚拟机？
- - '###'
  - 以太坊协议在银行业中的作用
- - '###'
  - 任何人都可以构建银行平台
- - '#'
  - EVM 的功能
- - '###'
  - 全局单例机器
- - '#'
  - EVM 应用程序被称为智能合约
- - '##'
  - “智能合约”的名称
- - '##'
  - EVM 运行字节码
- - '#'
  - 理解状态机
- - '##'
  - 数字与模拟
- - '###'
  - (图 3-1) 海军少将格蕾丝·霍珀是 1944 年为哈佛马克一号计算机编写代码的首批程序员之一。（图片来源：维基百科。）
- - '###'
  - “语句（State-ments）”
- - '###'
  - 数据在状态中的作用
- - '##'
  - EVM 的内部工作机制
- - '###'
  - EVM 持续检查交易
- - '###'
  - 创建关于所发生事件的通用机器叙事
- - '###'
  - 密码学哈希
- - '###'
  - 哈希函数（或哈希算法）的作用
- - '#'
  - 区块：状态变更的历史记录
- - '##'
  - 理解区块时间
- - '##'
  - 短区块的缺点
- - '##'
  - “单节点”区块链
- - '##'
  - 分布式安全
- - '#'
  - 挖矿在状态转换函数中的位置
- - '##'
  - 在 EVM 上租用时间
- - '##'
  - 你好，Gas
- - '###'
  - 为什么 Gas 如此重要？
- - '###'
  - 为什么 Gas 不以以太币计价？
- - '###'
  - 作为监管的费用
- - '##'
  - 处理 Gas
- - '###'
  - 燃料费详解
- - '###'
  - 燃料费与系统扩容的关系
- - '##'
  - 账户、交易与消息
- - '###'
  - 外部拥有账户
- - '###'
  - 合约账户
- - '##'
  - 交易与消息
- - '###'
  - 交易的特征
- - '###'
  - 消息的特征
- - '####'
  - 注意
- - '##'
  - 估算操作燃料费
- - '##'
  - EVM 中的操作码
- - '###'
  - (表 3-2) EVM 操作码完整列表
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 4 章：Solidity 编程
- - '##'
  - 入门
- - '##'
  - （几乎）成为现实的全球银行业务
- - '###'
  - 超大型基础设施
- - '###'
  - 全球货币？
- - '#'
  - 补充货币
- - '##'
  - Solidity 的前景
- - '##'
  - 浏览器编译器
- - '##'
  - 学习为 EVM 编程
- - '###'
  - Easy Deployment
- - '####'
  - Note
- - '###'
  - Reasons to Write Business Logic in Solidity
- - '###'
  - Code, Deploy, Relax
- - '##'
  - Design Principles
- - '####'
  - Note
- - '###'
  - Writing Loops in Solidity
- - '###'
  - 表达力与安全性
- - '##'
  - 形式化证明的重要性
- - '###'
  - 共享全球资源的历史影响
- - '###'
  - 攻击者如何破坏社区
- - '###'
  - 用 Solidity 编写的假设性攻击
- - '####'
  - 注
- - '##'
  - 自动化证明来救场？
- - '###'
  - 实践中的确定性
- - '###'
  - 失之毫厘，谬以千里
- - '##'
  - 测试，测试，再测试
- - '###'
  - 命令行是可选工具！
- - '####'
  - 注意
- - '##'
  - 格式化 Solidity 文件
- - '#'
  - 代码阅读指南
- - '###'
  - (表 4-1)
- - '##'
  - Solidity 中的语句和表达式
- - '###'
  - 什么是表达式？
- - '###'
  - 什么是语句？
- - '###'
  - 函数：公共与私有
- - '####'
  - 注意
- - '##'
  - 值类型
- - '###'
  - 布尔值
- - '###'
  - 有符号和无符号整数
- - '###'
  - 地址
- - '###'
  - 地址的成员
- - '###'
  - 地址相关的关键字
- - '####'
  - 注意
- - '###'
  - 较少使用的值类型
- - '###'
  - 复杂（引用）类型
- - '##'
  - 全局特殊变量、单位和函数
- - '###'
  - 区块和交易属性
- - '###'
  - 运算符速查表
- - '###'
  - 全局函数
- - '###'
  - 异常和继承
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 5 章：智能合约与代币
- - '##'
  - 用 Solidity 编写的小型可重用代码模板（在编程术语中称为类）被称为*智能合约*，这一名称借鉴了金融合约的概念。你可以将智能合约理解为非常适合创建作为网络服务的金融衍生品——只是附带了一些特性。
- - '##'
  - '`EVM` 作为后端'
- - '###'
  - 从智能合约到去中心化应用
- - '##'
  - 任何资产都可作为支撑
- - '###'
  - 用法定货币进行物物交换
- - '###'
  - 以太币作为玻璃珠
- - '#'
  - 加密货币是时间的度量
- - '##'
  - 资产所有权与文明
- - '###'
  - 你的储蓄堆 = 声誉
- - '###'
  - 货币、代币、声誉……那又怎样？
- - '####'
  - (图 5-1) 二维码为机器读取加密货币地址和网址提供了便捷方式。此二维码指向 [`eth.guide`](http://eth.guide)。
- - '###'
  - 硬币即是收藏品
- - '###'
  - 收藏品在人类系统中的功能
- - '###'
  - 早期的伪造行为
- - '###'
  - 珠宝与艺术作为货币
- - '###'
  - 迈向纸币的一步
- - '###'
  - 高价值数字收藏品的平台
- - '#'
  - 代币是智能合约的一种类别
- - '##'
  - 作为社会合约的代币
- - '##'
  - 代币是绝佳的入门应用
- - '##'
  - 在测试网上创建代币
- - '###'
  - 从水龙头获取测试以太币
- - '####'
  - (图 5-4) 以太坊测试网提供了测试以太币的发放功能，可用于编写或调试合约
- - '####'
  - 注意
- - '####'
  - 练习：无需代码创建自定义代币
- - '####'
  - (图 5-5) “合约”标签页用于粘贴和部署你的合约
- - '####'
  - 练习：关注代币
- - '####'
  - (图 5-11) 了解代币的基本信息后，`Mist`就能跟踪你在该代币中的余额
- - '###'
  - 注册你的代币
- - '##'
  - 部署你的第一个合约
- - '####'
  - 注意
- - '####'
  - (图 5-12) 再次确认你在测试网上
- - '####'
  - 练习：5 分钟内部署一个简单合约
- - '###'
  - 同一栋房屋，不同地址
- - '####'
  - 注意
- - '##'
  - 与合约交互
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 6 章：挖掘以太币
- - '#'
  - 意义何在？
- - '##'
  - 以太币的来源
- - '##'
  - 定义挖矿
- - '##'
  - 多重版本的事实
- - '###'
  - 挖矿难度、自我调节与利润追逐
- - '####'
  - 难度
- - '####'
  - 注记
- - '####'
  - 区块验证所需因素
- - '###'
  - 工作量证明如何帮助调节出块时间
- - '##'
  - DAG 与 Nonce 的运作机制
- - '#'
  - 这一切都是为了更快的区块？
- - '###'
  - 让快速区块运作起来
- - '####'
  - 注意
- - '##'
  - 以太坊如何利用过时区块
- - '###'
  - 叔块规则与奖励
- - '#'
  - 难度炸弹
- - '##'
  - 矿工获胜的奖励结构
- - '##'
  - 祖先限制
- - '##'
  - 区块处理逐步解析
- - '####'
  - 注意
- - '##'
  - 评估区块和交易的祖先
- - '#'
  - 以太坊与比特币如何运用树结构
- - '##'
  - 默克尔-帕特里夏树
- - '##'
  - 以太坊区块头的内容
- - '##'
  - 分叉
- - '##'
  - 挖矿教程
- - '###'
  - 在 macOS 上安装 Geth
- - '###'
  - 在 Windows 上安装 Geth
- - '#'
  - 熟练掌握命令行
- - '#'
  - 在 Ubuntu 14.04 上安装 Geth
- - '#'
  - 通过 Geth 控制台在 EVM 中执行命令
- - '####'
  - Note
- - '####'
  - (图 6-5) 在 JavaScript 控制台中创建新账户再简单不过了。您的新公钥以绿色显示。别忘了您的密码！
- - '##'
  - 使用标志启动 Geth
- - '####'
  - (图 6-6) 测试网输出
- - '##'
  - 启动您的矿工！
- - '####'
  - 注意
- - '####'
  - (图 6-7) 矿工准备挖矿
- - '####'
  - 练习：将您的名字添加到区块链
- - '####'
  - 练习：检查您的余额
- - '#'
  - 在测试网络上挖矿
- - '####'
  - 注意
- - '#'
  - GPU 挖矿设备
- - '####'
  - (图 6-8) 作者地下室中运行的四台以太坊矿机
- - '##'
  - 在矿池中使用多 GPU 挖矿
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 7 章：加密经济学概览
- - '##'
  - 通过安全计算机网络进行的经济活动研究被称为加密经济学
- - '##'
  - 发展历程
- - '###'
  - 新技术创造新经济
- - '###'
  - 游戏规则
- - '##'
  - 为什么加密经济有用？
- - '###'
  - 理解哈希与加密的区别
- - '###'
  - 加密
- - '####'
  - 加密的弱点
- - '#'
  - 哈希
- - '##'
  - 哈希的用途
- - '#'
  - 区块速度为何重要
- - '#'
  - 以太币发行方案
- - '####'
  - (图 7-1) 以太币的供应是通胀性的，但这未必会反映在价格上
- - '#'
  - 常见攻击场景
- - '##'
  - 机器间的社会认同
- - '#'
  - 网络安全随网络扩展
- - '##'
  - 更多关于加密经济学
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 8 章：去中心化应用部署
- - '##'
  - 如你所见，部署去中心化应用是新计算范式前沿的一场冒险
- - '##'
  - 关于智能合约的七种思考方式
- - '#'
  - DApp 合约数据模型
- - '##'
  - EVM 后端如何与 JS 前端通信
- - '###'
  - JSON-RPC
- - '##'
  - Web 3 时代即将到来（几乎）
- - '##'
  - 使用 JavaScript API 进行实验
- - '###'
  - 使用 Geth 部署去中心化应用
- - '####'
  - 注意
- - '##'
  - 将 Meteor 与 EVM 结合使用
- - '###'
  - 安装 Web3.js 以构建支持以太坊的 Web 应用
- - '##'
  - 在控制台中执行合约
- - '###'
  - 合约如何暴露接口
- - '#'
  - 原型设计建议
- - '##'
  - 第三方部署库
- - '##'
  - 总结
- - '#'
  - 第 9 章：创建私有链
- - '##'
  - 与公链爱好者所争论的相反，私有链作为学习工具确实有其价值，并最终可能对大型企业、民族国家或非政府组织（NGO）有其用途。然而，需要指出的是，并非对所有数据库和网络来说，区块链天生就更优越。
- - '##'
  - 私有链与许可链
- - '#'
  - 搭建本地私有链
- - '##'
  - 创建你的区块链创世文件
- - '##'
  - 新链的可选标志
- - '##'
  - 生产环境中的私有区块链
- - '#'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 10 章：应用场景
- - '##'
  - 工作量证明、去中心化、默克尔树与帕特里夏树、非对称加密、智能合约……用这些配料能做出什么？
- - '##'
  - 链无处不在
- - '##'
  - 以太坊物联网
- - '####'
  - 注
- - '##'
  - 零售与电子商务
- - '##'
  - 社区与政府融资
- - '##'
  - 人类与组织行为
- - '##'
  - 金融与保险应用
- - '##'
  - 库存与会计系统
- - '#'
  - 软件开发
- - '#'
  - 游戏、博彩与投资
- - '#'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 第 11 章：高级概念
- - '##'
  - 以太坊协议的未来与起源
- - '##'
  - 谁在引领软件开发者走向去中心化？
- - '###'
  - 维塔利克的最佳技术博文
- - '#'
  - 以太坊发布路线图
- - '##'
  - Whisper（消息传递）
- - '##'
  - Swarm（内容寻址）
- - '##'
  - 未来展望
- - '##'
  - 其他有趣的创新
- - '##'
  - 完整的以太坊路线图
- - '###'
  - 前沿发布（2015）
- - '###'
  - Homestead 版本（2016 年）
- - '###'
  - Metropolis 版本（2017 年）
- - '###'
  - Serenity 版本（2018 年）
- - '##'
  - 总结
- - '#'
  - 脚注
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H, I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N, O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T, U
- - '##'
  - V
- - '##'
  - W, X, Y, Z
