name: IoT Standards with Blockchain
name_cn: 区块链物联网标准
slug: iot-standards-with-blockchain
toc:
- - '##'
  - 引言
- - '##'
  - 第一部分：物联网业务战略
- - '#'
  - 1. 入门指南
- - '##'
  - 定义
- - '##'
  - 为未来设计业务
- - '##'
  - 物联网作为数字化推动力
- - '###'
  - 运营技术概述
- - '###'
  - 信息技术与运营技术融合
- - '##'
  - 物联网面临的三大挑战
- - '###'
  - 业务战略
- - '###'
  - 物联网安全
- - '###'
  - IoT 互操作性
- - '####'
  - 设备互操作性
- - '####'
  - 网络互操作性
- - '####'
  - 语义互操作性
- - '####'
  - 语法互操作性
- - '###'
  - 平台互操作性
- - '##'
  - 总结
- - '#'
  - 2. 物联网商业战略
- - '##'
  - 客户参与战略
- - '##'
  - 业务转型战略
- - '###'
  - 流程转型
- - '###'
  - 模式转型
- - '###'
  - 领域转型
- - '##'
  - 业务生产力提升
- - '##'
  - 在客户互动、业务转型与业务生产力提升策略之间做出选择
- - '##'
  - 总结
- - '#'
  - 3. 物联网标准业务转型模型
- - '##'
  - 选定业务战略后下一步做什么
- - '###'
  - 物联网用例参考模型（IoT UCR 模型）
- - '###'
  - 对用例应用物联网处理方式
- - '###'
  - 异构物联网转型
- - '####'
  - 定义
- - '###'
  - 同构物联网转型
- - '##'
  - 总结
- - '#'
  - 第二部分：物联网参考模型
- - '#'
  - 4. 物联网标准参考模型
- - '##'
  - 物联网标准参考模型
- - '###'
  - 设备（传感器与执行器）
- - '###'
  - 智能物联网网关
- - '####'
  - 设备通信是网关的首要功能
- - '####'
  - 设备管理是某些网关执行的另一项基本功能
- - '####'
  - 边缘计算是智能物联网网关的第三大重要功能
- - '###'
  - 定义
- - '###'
  - 智能网关面临的挑战
- - '###'
  - 全栈物联网平台
- - '###'
  - 人工智能是物联网平台执行的一项重要功能，在某些情况下也在物联网网关层面（称为边缘 IT）执行
- - '##'
  - 智能物联网网关与全栈物联网平台的典型活动
- - '##'
  - 安全
- - '###'
  - 设备安全
- - '###'
  - 智能物联网网关安全
- - '###'
  - 物联网平台安全
- - '##'
  - 区块链
- - '##'
  - 总结
- - '#'
  - 5. IoT 设备及其通信
- - '##'
  - 设备类型
- - '###'
  - 小物件（1 类设备）
- - '###'
  - 大物件（2 类设备）
- - '###'
  - 复杂物件（3 类设备）
- - '##'
  - 通信协议
- - '###'
  - LPWAN（低功耗广域网）
- - '###'
  - 卫星通信网络（3G/4G/5G）
- - '###'
  - 射频网络
- - '###'
  - 蓝牙
- - '###'
  - Wi-Fi
- - '###'
  - RFID
- - '###'
  - 有线网络
- - '##'
  - 为行业应用案例选择合适的智能物联网网关
- - '###'
  - 概述
- - '#'
  - 6. 智能物联网网关
- - '##'
  - 安全性
- - '##'
  - IT-OT 团队整合
- - '##'
  - 数据量与数据分析
- - '##'
  - 缺乏标准通信（数据）协议
- - '##'
  - 产品与平台的多样性
- - '##'
  - 投资回报率
- - '##'
  - IoT 网关
- - '###'
  - 智能 IoT 网关
- - '###'
  - 选择正确的智能物联网网关
- - '####'
  - 数据大小与存储能力
- - '####'
  - 物联网网关级别的数据处理能力是另一项要求
- - '####'
  - 物联网网关的坚固性
- - '####'
  - 互操作性（连接性要求）
- - '####'
  - 安全性
- - '####'
  - 遗留设备集成
- - '####'
  - 可扩展性
- - '##'
  - IoT 网关对比
- - '###'
  - 慧与 (HPE)
- - '###'
  - 戴尔
- - '###'
  - 研扬科技 (AAEON)
- - '###'
  - 迪进国际 (Digi International)
- - '###'
  - 华为
- - '##'
  - 总结
- - '#'
  - 7. 物联网云平台
- - '##'
  - 物联网六项基本要素
- - '###'
  - 可靠性与可用性
- - '###'
  - 可扩展性
- - '####'
  - 云弹性
- - '####'
  - 垂直扩展
- - '####'
  - 水平扩展
- - '####'
  - 自动伸缩
- - '##'
  - 灾难恢复
- - '##'
  - 数据安全
- - '##'
  - 定价模式
- - '##'
  - 认证与标准
- - '##'
  - 公司概况
- - '##'
  - 特定能力
- - '###'
  - 连接性
- - '###'
  - 设备管理
- - '####'
  - 设备接入与配置
- - '####'
  - 设备配置
- - '####'
  - 设备维护
- - '###'
  - 应用使能平台（具有卓越应用开发能力的物联网平台）
- - '###'
  - 可扩展性
- - '####'
  - （大规模）设备接入能力
- - '###'
  - 数据存储与物联网分析
- - '##'
  - 概念验证
- - '##'
  - 总结
- - '#'
  - 8. 物联网中的安全
- - '###'
  - 网络安全
- - '###'
  - 专用技术
- - '##'
  - 安全设计一体化（保护整个物联网生态系统）
- - '###'
  - 购买内置安全功能的设备
- - '###'
  - 保护设备
- - '###'
  - API 安全
- - '###'
  - 智能物联网网关安全
- - '####'
  - 身份与访问控制 (IAC)
- - '####'
  - 无线升级与安全启动
- - '####'
  - 可视性与威胁检测
- - '###'
  - 补丁管理/持续软件更新
- - '###'
  - 硬件安全
- - '###'
  - 物联网平台安全
- - '##'
  - 利用区块链保障物联网安全
- - '##'
  - 总结
- - '#'
  - 第三部分：人工智能与区块链：物联网的赋能者
- - '#'
  - 9. 区块链与物联网
- - '##'
  - 公有区块链
- - '##'
  - 私有区块链
- - '###'
  - Hyperledger
- - '###'
  - 区块链如今几乎惠及所有行业
- - '##'
  - 物联网区块链实施模式
- - '###'
  - 模式 1：设备 ➤ 物联网云平台 ➤ 区块链
- - '###'
  - 模式 2：设备 ➤ 物联网网关 ➤ 物联网云平台 ➤ 区块链
- - '###'
  - 模式 3：设备 ➤ 物联网网关 ➤ 区块链
- - '###'
  - 模式 4：设备 ➤ 区块链
- - '###'
  - 模式 5：设备 ➤ 物联网网关 ➤ 物联网平台
- - '####'
  - 明智地应用集成模式
- - '###'
  - '`IoMT`的构建块及相关挑战'
- - '####'
  - 数据接入
- - '####'
  - 延迟
- - '####'
  - 设备数量
- - '####'
  - 互操作性
- - '####'
  - 数据延迟到达
- - '####'
  - 数据重复
- - '####'
  - 数据格式
- - '##'
  - 总结
- - '#'
  - 10. 物联网世界中的人工智能（应用型物联网）
- - '##'
  - 机器人流程自动化
- - '##'
  - 人工智能
- - '###'
  - 数据科学
- - '###'
  - 人工智能与数据科学之间的联系
- - '####'
  - 高质量数据的重要性
- - '###'
  - 人工智能与物联网
- - '####'
  - 在物联网用例中应用人工智能的经验教训（应用物联网）
- - '##'
  - 总结
- - '#'
  - 第四部分：物联网实施要点
- - '##'
  - 物联网实施要点
- - '#'
  - 11. 大数据与分析
- - '##'
  - 大数据挑战
- - '##'
  - 工业 4.0 与物联网数据
- - '##'
  - 物联网数据的关键考量
- - '##'
  - 调试能力
- - '##'
  - 数据的及时性与准确性
- - '##'
  - 数据管理与洞察应在何处进行
- - '##'
  - 数据存储考量（哪些数据需要存储，哪些需要丢弃）
- - '##'
  - 存储的快速配置是另一项关键需求
- - '##'
  - 利用雾计算进行数据管理
- - '##'
  - 自动化数据决策
- - '##'
  - 数据安全与隐私仍是各行各业在物联网领域的重大关切
- - '##'
  - （大）数据优先参考模型
- - '###'
  - 数据源
- - '###'
  - 数据存储层
- - '###'
  - 数据提取层与数据处理层
- - '###'
  - 数据消费层
- - '###'
  - 数据治理
- - '##'
  - 总结
- - '#'
  - 12. 面向物联网用例实现的产品思维
- - '##'
  - 什么是项目或项目型组织？
- - '##'
  - 产品组织
- - '##'
  - 以产品思维看待物联网产品生命周期
- - '###'
  - 从假设到变现
- - '###'
  - 物联网用例开发中的敏捷软件开发方法
- - '####'
  - 敏捷——物联网用例开发的事实标准
- - '##'
  - 总结
- - '#'
  - 13. IoT 产品团队
- - '##'
  - IoT 产品团队
- - '###'
  - 运营技术负责人
- - '###'
  - 安全顾问
- - '###'
  - 产品开发团队
- - '###'
  - DevSecOps 实现更快的交付速度
- - '###'
  - DevSecOps 管理规模并具备主动安全性
- - '###'
  - 管理严格的互操作性测试并确保可用性
- - '###'
  - 信息技术主管
- - '###'
  - 大数据主管
- - '###'
  - 定义
- - '###'
  - IoT 负责人
- - '###'
  - 确定物联网产品团队
- - '###'
  - 传统金字塔模式的成本影响
- - '###'
  - 用于识别产品开发团队的 Hackfest 模式
- - '####'
  - 初选
- - '####'
  - 产品聚焦评估
- - '####'
  - 行为评估
- - '####'
  - 培训
- - '##'
  - 总结
- - '#'
  - 书籍总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J, K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '##'
  - R
- - '##'
  - S, T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X, Y
- - '##'
  - Z
