name: Learn Blockchain by Building One
name_cn: 区块链构建学习指南
slug: learn-blockchain-by-building-one
toc:
- - '##'
  - 修复后的目录
- - '#'
  - 引言
- - '##'
  - 又一本关于区块链的书？为什么？
- - '##'
  - 为成功做好准备
- - '###'
  - GitHub 仓库
- - '###'
  - 花时间配置你的开发环境
- - '###'
  - 知道去哪里获取答案
- - '###'
  - 不会 Python？
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审稿人
- - '#'
  - 1. 为应用开发做好准备
- - '##'
  - Python 版本
- - '##'
  - 安装 Python
- - '###'
  - Windows 系统安装
- - '###'
  - macOS 安装
- - '###'
  - Linux 安装
- - '##'
  - Python 程序如何运行
- - '##'
  - 管理项目依赖
- - '###'
  - 安装 Poetry
- - '###'
  - 使用 Poetry 创建一个 Python 项目
- - '###'
  - 安装依赖
- - '##'
  - 激活虚拟环境
- - '##'
  - 示例：获取比特币价格
- - '##'
  - 总结
- - '#'
  - 2. 识别万物的方法
- - '##'
  - 项目设置
- - '##'
  - 哈希函数
- - '###'
  - 示例 1：Python 中的哈希运算
- - '###'
  - 哈希函数期望输入为字节：`encode()` 方法可将字符串转换为字节
- - '###'
  - 我们使用 `hexdigest()` 将字节转换为十六进制，因为更易读
- - '##'
  - 哈希函数的选择
- - '###'
  - 示例 2：为图像进行哈希运算
- - '##'
  - 验证从互联网下载的文件
- - '##'
  - 类比
- - '##'
  - 不可逆性
- - '###'
  - 示例 3：发送防篡改的电子邮件
- - '##'
  - 问题
- - '###'
  - 解决方案
- - '##'
  - 防止垃圾邮件如何促成了工作量证明
- - '##'
  - 总结
- - '#'
  - 3. 区块链
- - '##'
  - 区块长什么样？
- - '##'
  - 不可变性与哈希的重要性
- - '##'
  - 用 Python 实现基础区块链
- - '###'
  - 使用类表示区块链
- - '####'
  - '`Generates a new block and adds it to the chain`'
- - '####'
  - '`Hashes a Block`'
- - '####'
  - '`Gets the latest block in the chain`'
- - '###'
  - 支持交易
- - '####'
  - '`Generates a new block and adds it to the chain`'
- - '####'
  - '`Hashes a Block`'
- - '####'
  - '`Gets the latest block in the chain`'
- - '####'
  - '`Adds a new transaction to the list of pending transactions`'
- - '###'
  - 添加区块
- - '###'
  - 完整的 `blockchain.py` 代码
- - '#'
  - 4. 工作量证明
- - '##'
  - 使用 iPython 与区块链类交互
- - '###'
  - 工作量证明简介
- - '##'
  - 工作量证明的一个简单示例
- - '##'
  - 类比：拼图游戏
- - '###'
  - 实现工作量证明
- - '###'
  - 货币供应
- - '#'
  - 5. 网络
- - '##'
  - 简要回顾互联网
- - '##'
  - Python 中的并发
- - '###'
  - 异步代码 vs. 多线程
- - '####'
  - '`asyncio` 快速入门指南'
- - '###'
  - 从零开始构建聊天服务器
- - '####'
  - 构建聊天服务器
- - '###'
  - 协议
- - '##'
  - 构建区块链的基础工作
- - '###'
  - 八卦协议
- - '#'
  - 6. 密码学入门
- - '##'
  - 发送完整性消息
- - '###'
  - 对称加密
- - '##'
  - 凯撒密码
- - '###'
  - 公钥密码学
- - '####'
  - Python 示例
- - '####'
  - 为爱丽丝和鲍勃生成密钥
- - '####'
  - 公钥由私钥生成
- - '####'
  - 鲍勃将发送一条消息给爱丽丝...
- - '####'
  - 所以他用他的私钥和爱丽丝的公钥创建了一个 `Box`
- - '####'
  - 我们加密鲍勃的秘密消息（字节形式）...
- - '####'
  - 爱丽丝用她的私钥和鲍勃的公钥创建了第二个 `Box`，这样她就能解密该消息
- - '####'
  - 现在爱丽丝可以解密消息：
- - '###'
  - 数字签名
- - '####'
  - 验证过程
- - '##'
  - 区块链上的钱包
- - '###'
  - 创建交易节点
- - '##'
  - 交易与工作量总结
- - '###'
  - 脱离比特币的 UTXO 模型
- - '###'
  - 矿工的角色
- - '###'
  - 我们将如何实现交易
- - '#'
  - 7. 勘误与变更
- - '##'
  - 为我们的全节点创建项目
- - '###'
  - 安装依赖项
- - '###'
  - 创建文件结构
- - '##'
  - 构建我们的节点结构
- - '###'
  - 职责分配
- - '####'
  - 使用一些配置实例化服务器
- - '####'
  - 启动服务器
- - '####'
  - 实例化区块链和用于“对等节点”的连接池
- - '####'
  - 实例化服务器，并将我们的模块“嵌入”其中
- - '####'
  - 现在启动服务器
- - '##'
  - 服务器模块
- - '###'
  - 从消息中提取地址，并添加到写入器对象中
- - '###'
  - 将对等节点添加到连接池中
- - '###'
  - '...并处理消息'
- - '###'
  - 连接已关闭，开始清理...
- - '##'
  - 区块链模块
- - '##'
  - '`connections` 模块'
- - '##'
  - '`peers` 模块'
- - '###'
  - 如果他们的区块比我们少，就发送给他们
- - '##'
  - 消息传递
- - '###'
  - 使用 Marshmallow 验证消息
- - '####'
  - '`{''last_seen'': 1589780748, ''ip'': ''192.168.0.1'', ''port'': 8888}`'
- - '####'
  - '`"{''last_seen'': 1589780748, ''ip'': ''192.168.0.1'', ''port'': 8888}"`'
- - '###'
  - 实现并验证类型
- - '###'
  - 定义消息（及其模式）
- - '####'
  - '`Passes validation by not throwing an exception`'
- - '##'
  - 整合所有内容
- - '###'
  - 查找你的外部 IP 地址
- - '#'
  - 8. 与现实世界去中心化网络的比较
- - '##'
  - 为什么区块链工程很困难
- - '###'
  - Funcoin 的不足之处
- - '##'
  - 网络层
- - '###'
  - 节点发现
- - '###'
  - 命名
- - '###'
  - 距离函数
- - '###'
  - 路由
- - '###'
  - 数据持久化
- - '###'
  - 替代共识：权益证明（Proof of Stake）
- - '###'
  - 智能合约
- - '###'
  - 智能合约长什么样？
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '###'
  - 区块链数字签名
- - '##'
  - D
- - '###'
  - 区块链工程
- - '###'
  - 磁盘空间
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '###'
  - 类比
- - '##'
  - I, J
- - '##'
  - K, L
- - '##'
  - M
- - '###'
  - 消息块负载
- - '##'
  - N, O
- - '###'
  - 点对点网络
- - '##'
  - P, Q
- - '###'
  - 项目依赖
- - '###'
  - 权益证明 (PoS)
- - '###'
  - 工作量证明系统
- - '##'
  - R
- - '##'
  - S
- - '###'
  - 对称密码学
- - '##'
  - T
- - '###'
  - 交易
- - '###'
  - 传输控制协议 (TCP)
- - '##'
  - U, V, W, X, Y, Z
