name: Ethereum for Web Developers
name_cn: Web开发者的以太坊指南
slug: ethereum-for-web-developers
toc:
- - '##'
  - 引言
- - '##'
  - 本书的目标读者
- - '##'
  - 你应该具备的知识
- - '##'
  - 工作环境
- - '##'
  - 各章节概览
- - '##'
  - 强制免责声明
- - '##'
  - 致谢
- - '###'
  - 关于作者与技术审校
- - '###'
  - 关于作者
- - '###'
  - 关于技术审校
- - '##'
  - 脚注
- - '#'
  - 1. 区块链
- - '##'
  - 密码学速成
- - '###'
  - 哈希函数
- - '###'
  - 公钥密码学
- - '##'
  - 区块链基础
- - '###'
  - 交易与区块
- - '####'
  - 注
- - '####'
  - 哈希链
- - '####'
  - 达成共识
- - '####'
  - 注意
- - '####'
  - 注意
- - '####'
  - 关于吞吐量
- - '####'
  - 从比特币到以太坊
- - '##'
  - 智能合约
- - '##'
  - Gas 费用
- - '##'
  - 去中心化应用
- - '###'
  - 用户体验
- - '####'
  - 去中心化的程度
- - '###'
  - 为什么选择区块链？
- - '####'
  - 优势与用例
- - '####'
  - 局限性
- - '####'
  - 非公有区块链
- - '####'
  - 注意
- - '##'
  - 总结
- - '#'
  - 2. 一个示例 DApp
- - '##'
  - 关于我们的 DApp
- - '###'
  - 我们的需求
- - '###'
  - 智能合约
- - '###'
  - 架构
- - '###'
  - 设置环境
- - '####'
  - 开发工具链
- - '####'
  - Web3 浏览器
- - '###'
  - 警告
- - '###'
  - 注
- - '##'
  - 构建我们的应用
- - '###'
  - 编译智能合约
- - '###'
  - 注
- - '###'
  - 通过 Web3 连接网络
- - '###'
  - 合约接口
- - '###'
  - 注意
- - '##'
  - 与我们的智能合约交互
- - '###'
  - 连接我们的组件
- - '###'
  - 注意
- - '###'
  - 查询合约状态
- - '###'
  - 提示
- - '###'
  - 发送交易
- - '###'
  - 注意
- - '###'
  - 通过事件监控更新
- - '###'
  - 部署应用程序
- - '##'
  - 总结
- - '#'
  - 3. 智能合约速成课
- - '##'
  - 什么是智能合约？
- - '###'
  - 注意
- - '###'
  - 外部账户 vs. 智能合约
- - '###'
  - 注意
- - '###'
  - 代码和状态
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - Gas 用量
- - '###'
  - 注意
- - '###'
  - 交易
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 调用
- - '##'
  - Solidity
- - '###'
  - Remix
- - '###'
  - 注意
- - '###'
  - 你的第一个 Solidity 合约
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 函数里有什么？
- - '####'
  - 可见性修饰符
- - '####'
  - 可支付修饰器（Payability Modifiers）
- - '####'
  - 自定义修饰器（Custom Modifiers）
- - '####'
  - 回退函数（Fallback Function）
- - '###'
  - 警告
- - '###'
  - 值数据类型
- - '####'
  - 布尔值和相等性
- - '####'
  - 整数和算术运算
- - '####'
  - 固定大小字节
- - '####'
  - 地址、合约和转账
- - '###'
  - 注意
- - '###'
  - 引用类型
- - '####'
  - 数组、字节数组和字符串
- - '###'
  - 警告
- - '###'
  - 映射
- - '###'
  - 结构体
- - '###'
  - 发出事件
- - '###'
  - 注意
- - '###'
  - 导入、继承和库
- - '###'
  - 注意
- - '##'
  - 知名智能合约
- - '###'
  - 应用程序二进制接口
- - '###'
  - EIP 与 ERC
- - '###'
  - ERC20 代币
- - '###'
  - 提示
- - '###'
  - ERC721 非同质化代币
- - '##'
  - 本章小结
- - '#'
  - 4. 查询网络
- - '##'
  - 连接到网络
- - '###'
  - 关于全节点和轻节点
- - '####'
  - Infura 和公共节点
- - '###'
  - JSON-RPC 接口
- - '###'
  - 注意
- - '###'
  - 连接协议
- - '###'
  - 替代 API
- - '####'
  - Etherscan API
- - '####'
  - 常规 JSON-RPC 调用
- - '###'
  - 注意
- - '###'
  - Provide 对象
- - '###'
  - 注意
- - '####'
  - Metamask 和启用了 Web3 的浏览器
- - '####'
  - 子提供者
- - '###'
  - 选择合适的连接方式
- - '####'
  - 尊重用户的选择
- - '####'
  - 使用公共节点
- - '####'
  - 整合方案
- - '##'
  - 检索数据
- - '###'
  - 网络信息
- - '###'
  - 备注
- - '###'
  - 账户余额与代码
- - '###'
  - 调用合约
- - '###'
  - 备注
- - '##'
  - 检测变更
- - '###'
  - 轮询新区块
- - '###'
  - 安装事件过滤器
- - '###'
  - 警告
- - '###'
  - 创建订阅
- - '###'
  - 注释
- - '##'
  - 示例应用
- - '###'
  - 设置
- - '###'
  - 依赖项
- - '###'
  - 初始化 Web3
- - '###'
  - 注意
- - '###'
  - ERC20 合约
- - '##'
  - 构建应用
- - '###'
  - 根组件
- - '###'
  - 注意
- - '####'
  - ERC20 组件
- - '##'
  - 展示转账事件
- - '###'
  - 加载历史转账
- - '###'
  - 注意
- - '###'
  - 监控新转账
- - '###'
  - 等待确认
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 5. 发送交易
- - '##'
  - 搭建环境
- - '###'
  - 开发节点
- - '####'
  - 使用 Ganache
- - '###'
  - 注意
- - '####'
  - Geth 或 Parity 开发模式
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 创建合约
- - '####'
  - 编译
- - '###'
  - 注意
- - '####'
  - 部署
- - '###'
  - 管理账户
- - '####'
  - 重新审视 Metamask
- - '###'
  - 注意
- - '###'
  - 提示
- - '####'
  - 在我们的应用中检索用户账户
- - '##'
  - 发起交易
- - '###'
  - 交易参数
- - '###'
  - 发送数值或数据
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 估算 Gas
- - '###'
  - 选择 Gas 价格
- - '###'
  - Note
- - '###'
  - 交易的生命周期
- - '####'
  - 交易被发送
- - '###'
  - 注意
- - '####'
  - 交易被挖掘
- - '###'
  - 注意
- - '###'
  - 说明
- - '####'
  - 交易已确认
- - '###'
  - 替换交易
- - '##'
  - 错误处理
- - '###'
  - 注意
- - '##'
  - 示例应用
- - '###'
  - 设置
- - '####'
  - 依赖项
- - '####'
  - 合约部署
- - '###'
  - 应用
- - '####'
  - 初始化 Web3 实例
- - '###'
  - 创建合约对象
- - '###'
  - 根应用组件
- - '###'
  - 主 ERC721 组件
- - '####'
  - 列出已存在的代币
- - '###'
  - 铸造新代币
- - '###'
  - 响应交易事件
- - '####'
  - 现有代币的确认
- - '###'
  - 后续步骤
- - '##'
  - 总结
- - '#'
  - 6. 索引与存储
- - '##'
  - 索引区块链数据
- - '###'
  - 说明
- - '###'
  - 追踪 ERC20 代币持有者
- - '####'
  - 重温 ERC20 接口
- - '###'
  - 注意
- - '###'
  - 查询转账事件
- - '###'
  - 注意事项
- - '###'
  - 共享数据
- - '###'
  - 处理链重组
- - '####'
  - 使用订阅
- - '####'
  - 检测重组
- - '####'
  - 撤销更改
- - '###'
  - 单元测试
- - '####'
  - 选择节点
- - '###'
  - 注意
- - '####'
  - 测试我们的索引器
- - '####'
  - 使用快照
- - '###'
  - 注意
- - '###'
  - 注
- - '###'
  - 关于中心化的说明
- - '####'
  - 去中心化服务
- - '####'
  - 中心化应用
- - '##'
  - 存储
- - '###'
  - 链下存储
- - '###'
  - ERC721 元数据扩展
- - '###'
  - 保存代币元数据
- - '###'
  - 星际存储
- - '####'
  - 什么是 IPFS？
- - '###'
  - 注意
- - '####'
  - 在我们的应用中使用 IPFS
- - '###'
  - 注意
- - '####'
  - 在 IPFS 上托管我们的应用
- - '##'
  - 总结
- - '#'
  - 7. 用户入门
- - '##'
  - 问题所在
- - '##'
  - 无需账户进行交互
- - '###'
  - 从交易所发送资金
- - '###'
  - 普通转账与回退函数
- - '##'
  - 谨慎提示
- - '##'
  - 注解
- - '##'
  - 转发合约
- - '##'
  - 一次性地址
- - '###'
  - 如何使用一次性地址
- - '####'
  - 创建一次性地址
- - '####'
  - 示例代码
- - '###'
  - 警告
- - '###'
  - 注解
- - '###'
  - 警告
- - '##'
  - 应用程序本地账户
- - '###'
  - 创建并使用本地钱包
- - '###'
  - 注意
- - '###'
  - 加密密钥库
- - '###'
  - 注意
- - '###'
  - 助记词
- - '##'
  - 智能账户
- - '###'
  - 身份即智能合约
- - '###'
  - 注
- - '###'
  - 示例实现
- - '###'
  - 部署智能账户（方案一）
- - '###'
  - 注意
- - '###'
  - 注意
- - '##'
  - 升级用户账户
- - '###'
  - '`DELEGATECALL` 指令'
- - '###'
  - 委托代理
- - '####'
  - 注意事项
- - '###'
  - 可升级身份
- - '###'
  - 注意
- - '##'
  - 无 Gas 交易
- - '###'
  - 注意
- - '###'
  - 以太坊中的签名
- - '###'
  - 注意
- - '###'
  - 引入元交易
- - '####'
  - 基于我们的智能账户进行构建
- - '###'
  - 注意
- - '###'
  - 说明
- - '####'
  - 发送元交易
- - '###'
  - 中继器与奖励
- - '####'
  - 中继器奖励
- - '###'
  - 估算利润
- - '###'
  - 实物支付
- - '###'
  - 原生元交易
- - '####'
  - 原生元交易中的奖励
- - '###'
  - 重访智能账户部署
- - '####'
  - '`CREATE2` 指令'
- - '####'
  - 部署奖励
- - '####'
  - 身份合约工厂
- - '###'
  - 注意
- - '##'
  - 以太坊名称
- - '###'
  - 以太坊的 DNS
- - '###'
  - 名称解析
- - '###'
  - 注意事项
- - '###'
  - 为我们的用户命名
- - '###'
  - 注意
- - '##'
  - 总结
- - '#'
  - 8. 可扩展性
- - '##'
  - 什么是 Layer 2？
- - '##'
  - 通道
- - '###'
  - 单向支付通道
- - '####'
  - 通道如何工作？
- - '####'
  - 实现单向通道
- - '###'
  - 注意
- - '####'
  - 构建一个支付应用
- - '###'
  - 注意事项
- - '##'
  - 双向支付通道
- - '####'
  - 挑战期
- - '###'
  - 注
- - '###'
  - 注
- - '####'
  - 一个示例交换
- - '###'
  - 实现双向通道
- - '###'
  - 注意
- - '###'
  - 优化与扩展
- - '###'
  - 状态通道
- - '####'
  - 将游戏编码为状态通道
- - '###'
  - 备注
- - '###'
  - 备注
- - '##'
  - 广义状态通道
- - '###'
  - 通道网络
- - '###'
  - 注意
- - '##'
  - 侧链
- - '###'
  - 注意
- - '###'
  - 权威证明
- - '####'
  - 安全与信任
- - '###'
  - 注意
- - '####'
  - 部署我们自己的链
- - '###'
  - 注意
- - '###'
  - 构建一个桥接
- - '###'
  - 注意
- - '###'
  - 注意事项
- - '###'
  - 等离子链
- - '##'
  - 摘要
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I, J
- - '###'
  - K, L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X, Y, Z
