name: Blockchain Fundamental Analysis for Digital Asset Investors
name_cn: 数字资产投资者的区块链基本面分析
slug: blockchain-fundamental-analysis-for-digital-asset-investors
toc:
- - '#'
  - 前言
- - '##'
  - 数字资产投资的陷阱
- - '##'
  - 本书目的
- - '##'
  - 如何使用本书
- - '#'
  - 本书使用的约定
- - '##'
  - 联系作者
- - '##'
  - 免责声明
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 1. 区块链技术简介
- - '##'
  - 区块链关键特性
- - '###'
  - 去中心化
- - '###'
  - 不可变性
- - '###'
  - 透明性
- - '###'
  - 匿名性/假名性
- - '###'
  - 可审计性
- - '###'
  - 自主性
- - '##'
  - Bitcoin（比特币）
- - '###'
  - 事实
- - '##'
  - 密码学
- - '###'
  - 加密密钥
- - '###'
  - 私钥
- - '###'
  - 公钥
- - '###'
  - 公开地址
- - '##'
  - 非对称加密
- - '###'
  - 区块链中的非对称加密
- - '###'
  - 密码学密钥回顾及其在非对称加密和典型比特币交易中的作用
- - '####'
  - 私钥的特性与功能
- - '####'
  - 公钥的特性与功能
- - '####'
  - 公钥地址的特性与功能
- - '##'
  - Web3
- - '###'
  - 网络的演变
- - '####'
  - Web1
- - '####'
  - Web2
- - '####'
  - Web3
- - '###'
  - 去中心化
- - '###'
  - 无需信任
- - '###'
  - 所有权和治理权
- - '###'
  - 无需许可
- - '###'
  - 网络演变概要
- - '##'
  - 区块链应用
- - '#'
  - 2. 投资数字资产
- - '##'
  - 为何投资数字资产？
- - '###'
  - 数字资产投资的优势
- - '###'
  - 数字资产投资的弊端
- - '##'
  - 投资分析
- - '###'
  - 数字资产投资分析技术
- - '####'
  - 基本面分析
- - '####'
  - 数字资产世界中的基本面分析
- - '####'
  - 基本面分析的好处
- - '###'
  - 技术分析
- - '###'
  - 指数移动平均线 (EMAs)
- - '###'
  - 随机指标
- - '##'
  - 竞争对手分析
- - '###'
  - 如何识别和评估竞争对手
- - '#'
  - 第一部分 – 区块链与数字资产评估入门
- - '##'
  - 区块链与数字资产评估入门
- - '#'
  - 3. 项目文档
- - '##'
  - 其他技术文档
- - '#'
  - 白皮书
- - '##'
  - 白皮书内容清单
- - '##'
  - 白皮书的益处
- - '###'
  - 白皮书风格
- - '###'
  - 白皮书版本
- - '###'
  - 白皮书脚注
- - '###'
  - 阅读白皮书的最佳方式
- - '###'
  - 成为白皮书专家的小步骤
- - '###'
  - 行动步骤
- - '###'
  - 结果评估
- - '###'
  - 精简白皮书
- - '###'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - 4. 核心产品
- - '##'
  - 产品用例与价值主张
- - '###'
  - 案例分析——Uniswap（产品/服务、用例和价值主张）
- - '###'
  - 产品用例、价值主张及相关市场需求
- - '###'
  - 评估产品用例、价值主张及相关市场需求
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '#'
  - 最小可行产品 (MVP)
- - '##'
  - MVP、测试版对投资者的重要性
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - 产品测试
- - '##'
  - 测试网
- - '###'
  - 测试网的优势
- - '###'
  - 测试网示例
- - '#'
  - 区块链浏览器
- - '#'
  - 伪匿名性
- - '#'
  - 测试网区块浏览器
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '##'
  - 在主网上线
- - '###'
  - 如何判断项目代码（产品）是否在主网上线
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 创始年份
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 5. 最终用户体验
- - '##'
  - 产品应用 UI/UX
- - '###'
  - 区块链的用户界面与用户体验
- - '###'
  - 项目官网
- - '###'
  - 面向投资者的用户界面与用户体验分析技巧
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - dApp 可用性与功能性评估
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 交易速度与成本
- - '###'
  - 交易速度
- - '###'
  - 交易“Gas”费用
- - '###'
  - 低 Gas 成本的重要性
- - '###'
  - 如何查看交易速度和 Gas 费用
- - '###'
  - 交易速度与 Gas 费用的投资者分析
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 终端用户支持与沟通
- - '###'
  - 为什么客户支持和沟通很重要？
- - '#'
  - 评估项目的最终用户支持与沟通策略
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '##'
  - 数字资产交易所
- - '###'
  - 数字资产交易所的类型
- - '###'
  - 中心化交易所（CEX）
- - '###'
  - 去中心化交易所（DEX）
- - '###'
  - 中心化交易所与去中心化交易所对比
- - '###'
  - 顶级 CEX 上市的优势
- - '###'
  - 顶级中心化交易所（CEX）资产验证
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 区块链架构
- - '#'
  - 区块链架构层
- - '##'
  - 区块链层概览
- - '##'
  - 第 0 层区块链
- - '###'
  - Polkadot 区块链基础设施的核心组件
- - '###'
  - 第一层区块链
- - '###'
  - 第二层协议
- - '###'
  - 第三层协议
- - '#'
  - 区块链分层“生态系统”评估
- - '##'
  - 价值创造效率
- - '###'
  - 开发者增长与留存
- - '###'
  - 基础设施技术实力
- - '##'
  - 链上竞争与协同
- - '###'
  - 链上竞争
- - '##'
  - 2. 链上协同效应
- - '###'
  - 第层“生态系统”区块链项目投资
- - '###'
  - 去中心化应用（dApp）投资
- - '##'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 区块链三元悖论
- - '###'
  - 去中心化
- - '####'
  - 中心化系统
- - '####'
  - 去中心化系统
- - '####'
  - 中心化与去中心化系统
- - '####'
  - 分布式账本技术
- - '###'
  - 区块链与分布式账本技术（DLT）
- - '###'
  - 真正的去中心化
- - '###'
  - 影响去中心化的中心化因素
- - '###'
  - 影响真正去中心化的因素
- - '###'
  - 分层基础设施对去中心化的影响
- - '####'
  - 行动步骤
- - '#####'
  - 结果评估
- - '###'
  - 可扩展性
- - '####'
  - 区块链可扩展性术语
- - '####'
  - 共识机制
- - '####'
  - 什么是共识机制？
- - '#'
  - 工作量证明（PoW）
- - '##'
  - 网络流量增加的因素
- - '#####'
  - 权益证明（PoS）
- - '#####'
  - 其他类型的共识机制
- - '#####'
  - 最具可扩展性的共识机制
- - '####'
  - 可扩展性改进解决方案
- - '#'
  - 第一层与第二层扩容方案
- - '##'
  - 横向与纵向扩容方案
- - '###'
  - 专家提示
- - '####'
  - 如何衡量区块链可扩展性性能
- - '####'
  - 行动步骤
- - '#####'
  - 结果评估
- - '###'
  - 安全性
- - '####'
  - 投资者重要的安全检查
- - '####'
  - 51% 攻击
- - '#####'
  - 51% 攻击的可能性
- - '#####'
  - 针对权益证明网络的 51% 攻击
- - '####'
  - 共识机制
- - '####'
  - 双花
- - '####'
  - 分叉
- - '#####'
  - 软分叉与硬分叉
- - '#####'
  - 硬分叉的危险
- - '####'
  - 女巫攻击
- - '#####'
  - 女巫攻击的危险
- - '#'
  - 拒绝服务攻击
- - '#'
  - 区块链投资者端点安全
- - '####'
  - 行动步骤
- - '#####'
  - 结果评估
- - '##'
  - 公有链、私有链、联盟链和混合链
- - '#####'
  - 表 6-12：公有链、私有链、联盟链和混合链的属性
- - '###'
  - 公有链
- - '###'
  - 公共区块链的优势
- - '###'
  - 公共区块链的劣势
- - '###'
  - 私有区块链
- - '####'
  - 私有区块链的优势
- - '####'
  - 私有区块链的劣势
- - '###'
  - 混合区块链
- - '####'
  - 混合区块链的优势
- - '####'
  - 混合区块链的劣势
- - '###'
  - 联盟区块链
- - '####'
  - 联盟区块链的优势
- - '####'
  - 联盟区块链的劣势
- - '####'
  - 这对投资者意味着什么？
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '###'
  - 无许可与有许可区块链
- - '###'
  - 这对投资者意味着什么？
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 支持匿名与隐私保护的区块链
- - '##'
  - 区块链如何帮助保护用户数据？
- - '##'
  - 身份与数据保护
- - '##'
  - 这对投资者意味着什么？
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - 治理
- - '##'
  - 区块链治理模型
- - '###'
  - 链下治理
- - '###'
  - 链上治理
- - '###'
  - 链下治理与链上治理对比
- - '###'
  - 这对投资者意味着什么？
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 跨链互操作性
- - '##'
  - 互操作性解决方案
- - '##'
  - 1. 区块链路由器
- - '##'
  - 2. 哈希锁定技术
- - '##'
  - 3. 公证人方案
- - '##'
  - 4. 预言机
- - '#'
  - 预言机与跨链互操作性
- - '##'
  - 5. 独立的区块链解决方案
- - '###'
  - 5.1 波卡网络
- - '###'
  - 5.2 Cosmos 网络
- - '##'
  - 跨链互操作性的优势
- - '###'
  - 投资者需考察区块链互操作性
- - '####'
  - 审阅项目文档
- - '####'
  - 通过专注互操作性的区块链实现互操作性
- - '#'
  - 其他互操作性解决方案的访问途径
- - '#'
  - 使用加密资产市场数据和价格追踪网站评估区块链互操作性
- - '#'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 7. 代币设计与用例
- - '##'
  - 加密代币、加密货币和山寨币
- - '###'
  - 加密货币
- - '###'
  - 山寨币
- - '###'
  - 加密代币
- - '###'
  - 代币类型
- - '###'
  - 功能型代币
- - '###'
  - 证券/股权代币
- - '###'
  - 非同质化代币
- - '####'
  - NFT 用例
- - '###'
  - 封装代币
- - '###'
  - 稳定代币
- - '#'
  - 代币标准
- - '##'
  - 代币化资产
- - '#'
  - 代币设计与应用场景
- - '##'
  - 评估代币设计
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - 代币价值累积流程与机制
- - '##'
  - 代币价值累积流程与机制
- - '###'
  - 代币价值累积流程
- - '###'
  - 代币累积机制
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 8. 代币经济学
- - '#'
  - 微观代币经济学与宏观代币经济学
- - '##'
  - 为什么良好的代币经济学对投资者很重要？
- - '##'
  - 本章内容预览
- - '##'
  - 代币供应指标
- - '###'
  - 总供应量
- - '###'
  - 流通供应量
- - '###'
  - 最大供应量
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 代币供应模型
- - '###'
  - 通缩型代币供应
- - '###'
  - 通缩型项目示例
- - '###'
  - 通胀型代币供应
- - '####'
  - 规避通胀风险
- - '####'
  - 通胀型项目示例
- - '###'
  - 固定代币供应
- - '###'
  - “固定供应”项目示例
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 代币分配模型
- - '###'
  - 代币分配群体
- - '####'
  - Uniswap 代币供应模型示例
- - '###'
  - 代币分配基准
- - '###'
  - 行动步骤
- - '###'
  - 评估结果
- - '##'
  - 解锁时间表
- - '###'
  - 解锁时间表及相关术语
- - '###'
  - 归属时间表评估
- - '###'
  - 基金会储备代币
- - '###'
  - 公募轮代币
- - '###'
  - 生态发展代币
- - '###'
  - 项目发展代币
- - '###'
  - 私募轮代币
- - '###'
  - 项目团队代币
- - '###'
  - 解锁时间表基准
- - '####'
  - 专家提示
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '#'
  - 9. 财务指标
- - '##'
  - 财务指标软件
- - '##'
  - 市值与完全稀释估值
- - '###'
  - 市值
- - '###'
  - 完全稀释估值
- - '###'
  - 获取市值与 FDV
- - '#'
  - 市值范围
- - '#'
  - 币价与市值
- - '#'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 已实现市值
- - '###'
  - 行动步骤
- - '#'
  - 结果评估
- - '##'
  - 已实现市值 HODL 波浪
- - '###'
  - 如何解读已实现市值 HODL 波浪图表
- - '###'
  - 已实现市值 HODL 区间波浪指标信号
- - '###'
  - 币龄增长
- - '###'
  - 年轻币
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '##'
  - 流动性与交易量
- - '###'
  - 流动性
- - '###'
  - 订单簿
- - '###'
  - 交易量
- - '###'
  - 流动性 vs 交易量
- - '###'
  - 评估市场流动性
- - '####'
  - 交易量
- - '####'
  - 买卖价差
- - '####'
  - 订单簿深度
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 总转移量
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '##'
  - 总质押价值 (TVS)
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '#'
  - 总锁仓价值 (TVL)
- - '##'
  - 如何评估 TVL 比率
- - '##'
  - TVL 历史表现
- - '###'
  - TVL 报告方式的差异
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 费用与收入
- - '###'
  - 费用
- - '###'
  - 收入
- - '###'
  - 评估费用与收入
- - '####'
  - 费用与收入市场趋势
- - '####'
  - 费用与收入分配模型
- - '###'
  - 竞争对手分析
- - '###'
  - 行动步骤
- - '###'
  - 结果评估
- - '##'
  - 交易笔数
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '###'
  - 通胀率
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '###'
  - 投资者工具
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '#'
  - 获利中的供应量百分比
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 活跃地址数
- - '#'
  - 行动步骤
- - '##'
  - 结果评估
- - '#'
  - 余额超过 1 万枚比特币的地址数量
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - MVRV 比率
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - MVRV Z-Score
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 未实现净损益 (NUPL)
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 哈希率
- - '##'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - 网络价值与交易量信号 (NVTS)
- - '##'
  - 操作步骤
- - '###'
  - 结果评估
- - '##'
  - 库存流量模型
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 10. 项目团队
- - '##'
  - 公开身份
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 项目团队成员
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 背景与经验
- - '##'
  - 评估团队背景与经验
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '##'
  - 开发者团队规模
- - '###'
  - 成立年份
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '#'
  - 项目支持
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 团队访谈
- - '###'
  - “有问必答”AMA
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 11. 项目路线图
- - '##'
  - 路线图的益处
- - '##'
  - 区块链路线图的核心要素
- - '###'
  - 目标与目的
- - '#'
  - 智能目标
- - '##'
  - 愿景与宗旨
- - '##'
  - 项目里程碑
- - '#'
  - 交付物的可行性
- - '##'
  - 路线图类型
- - '###'
  - 投资者路线图
- - '####'
  - Sandbox 路线图
- - '####'
  - 考量因素
- - '###'
  - 产品开发路线图
- - '####'
  - 以太坊产品发展路线图
- - '####'
  - 需要考虑的因素
- - '##'
  - 评估加密路线图
- - '###'
  - 目标与目的
- - '####'
  - 行动步骤
- - '###'
  - 结果评估
- - '###'
  - 愿景与目的
- - '####'
  - Polygon 的愿景
- - '####'
  - Polygon 路线图与愿景的一致性
- - '####'
  - 互联网的价值层
- - '####'
  - 行动步骤
- - '###'
  - 结果评估
- - '###'
  - 里程碑可行性
- - '####'
  - 行动步骤
- - '###'
  - 结果评估
- - '###'
  - 透明度与问责制
- - '####'
  - 行动步骤
- - '###'
  - 结果评估
- - '###'
  - 比较竞争对手的路线图
- - '####'
  - 行动步骤
- - '###'
  - 结果评估
- - '#'
  - 12. 项目代码库
- - '##'
  - 编程语言介绍
- - '##'
  - 智能合约
- - '###'
  - 智能合约的优势
- - '###'
  - 以太坊虚拟机（EVM）
- - '##'
  - GitHub
- - '###'
  - 为什么 GitHub 对投资者很重要？
- - '###'
  - 操作步骤
- - '####'
  - 结果评估
- - '#'
  - 开源与闭源软件
- - '##'
  - 开源许可协议
- - '###'
  - 著佐权（Copyleft）许可协议
- - '####'
  - 宽松许可证
- - '####'
  - 这对投资者意味着什么？
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '##'
  - 编程语言
- - '###'
  - 投资者对编程语言的分析
- - '####'
  - 评估非寻常编码语言
- - '###'
  - 编程语言多样性
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '##'
  - GitHub 贡献者
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '###'
  - Git 提交记录
- - '####'
  - 可取的月度提交贡献量
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '##'
  - Git Issues
- - '###'
  - 操作步骤
- - '####'
  - 评估结果
- - '###'
  - 代码安全审计
- - '###'
  - 为什么要进行代码安全审计？
- - '###'
  - 代码安全审计执行
- - '###'
  - 投资者代码安全审计检查
- - '###'
  - 持续改进的代码监控
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '##'
  - 漏洞赏金
- - '###'
  - 行动步骤
- - '####'
  - 评估结果
- - '#'
  - 13. 激励与奖励
- - '##'
  - 主要激励机制
- - '###'
  - 质押
- - '###'
  - 验证者质押
- - '###'
  - 流动性质押
- - '####'
  - 委托质押即服务（SaaS）
- - '####'
  - 中心化质押平台
- - '####'
  - 通过去中心化钱包质押
- - '####'
  - 投资者质押考量
- - '#####'
  - 质押奖励：铸造奖励 vs 交易手续费奖励
- - '#####'
  - 来自铸造代币的奖励
- - '###'
  - 交易手续费带来的奖励
- - '###'
  - 实际收益率
- - '###'
  - 质押比率
- - '###'
  - 最优质押比率
- - '###'
  - 质押项目概览
- - '###'
  - 挖矿奖励
- - '###'
  - 流动性挖矿
- - '#'
  - 流动性挖矿风险
- - '##'
  - 优势
- - '##'
  - 劣势
- - '#'
  - 流动性收益 farming/ 收益农耕
- - '##'
  - 优势
- - '##'
  - 劣势
- - '###'
  - 收益聚合器
- - '####'
  - 收益聚合器架构
- - '###'
  - 治理奖励
- - '###'
  - 边玩边赚奖励
- - '#'
  - 次级激励机制
- - '##'
  - 空投
- - '##'
  - 平台激励
- - '##'
  - Beta 测试奖励
- - '##'
  - 推荐计划
- - '##'
  - 忠诚度激励
- - '#'
  - 行动步骤
- - '##'
  - 确定合适的基于奖励的策略时的考量因素与行动步骤
- - '###'
  - 结果评估
- - '#'
  - 14. 社区与社交媒体
- - '##'
  - 社交媒体
- - '##'
  - 什么是社区？
- - '##'
  - 区块链项目社区的重要性
- - '###'
  - 内测
- - '###'
  - 代码协作
- - '###'
  - 网络效应
- - '###'
  - 持续反馈
- - '###'
  - 传播认知
- - '###'
  - 治理
- - '###'
  - 主流采用与接受
- - '##'
  - 社交媒体与社区评估
- - '###'
  - 区块链社区的社交平台
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '###'
  - 关注者数量
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '###'
  - 发帖频率
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '###'
  - 内容参与度
- - '###'
  - 参与率
- - '###'
  - 基于触及人数的参与率 (ERR)
- - '###'
  - 行动步骤
- - '###'
  - 结果评估
- - '###'
  - 社区版主
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 15. 资金与合作伙伴
- - '#'
  - 机构投资
- - '###'
  - 机构为何青睐 Bitcoin 和 Ethereum
- - '###'
  - 机构投资的类型
- - '#'
  - 机构投资
- - '##'
  - 投资工具
- - '###'
  - 企业投资（[微策略](https://www.microstrategy.com/en)、[谷歌风投](https://www.gv.com/)、[英特尔资本](https://www.intelcapital.com/)、[IBM
    区块链](https://www.ibm.com/blockchain)、[富达投资](https://www.fidelity.com/)）
- - '###'
  - 投资信托（[灰度投资](https://grayscale.com/)）
- - '###'
  - 交易所交易基金（[方舟投资](https://ark-invest.com/)、[Amplify 转型数据共享 ETF (BLOK)](https://amplifyetfs.com/blok/)、[范埃克比特币策略
    ETF (XBTF)](https://www.vaneck.com/us/en/investments/bitcoin-strategy-etf-xbtf/overview/)、[ProShares
    比特币策略 ETF (BITO)](https://www.proshares.com/our-etfs/strategic/bito)）
- - '###'
  - 交易所交易产品（[富达 Wise Origin 比特币基金 (FBTC)](https://institutional.fidelity.com/advisors/investment-solutions/asset-classes/alternatives/fidelity-wise-origin-bitcoin-fund)）
- - '###'
  - 政府拨款（[欧盟区块链观察站](https://www.eublockchainforum.eu/)、[美国国家科学基金会 (NSF) 拨款](https://www.nsf.gov/)）
- - '###'
  - 银行贷款（[摩根大通](https://www.jpmorganchase.com/)、[美国银行](https://www.bankofamerica.com/)、[富国银行](https://www.wellsfargo.com/)）
- - '##'
  - 机构投资优势
- - '##'
  - 机构投资劣势
- - '###'
  - 机构投资评估
- - '####'
  - 机构投资的验证
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 私募融资
- - '###'
  - 私募融资类型
- - '#'
  - 专业提示
- - '##'
  - 私募融资优势
- - '##'
  - 私募融资劣势
- - '##'
  - 私募投资评估
- - '###'
  - 核实私募融资
- - '###'
  - Crunchbase
- - '###'
  - 私募投资者的声誉与角色
- - '###'
  - 行动步骤
- - '###'
  - 结果评估
- - '##'
  - 公开发行
- - '###'
  - 公开发行模式类型
- - '####'
  - 首次代币发行 (ICO)
- - '#'
  - '[IOTA ICO](https://icodrops.com/iota/) – [IOTA](https://www.iota.org/)'
- - '##'
  - 首次交易所发行（IEO）
- - '##'
  - 首次 DEX 发行（IDO）
- - '##'
  - 首次农场发行（IFO）
- - '#'
  - 证券型代币发行（STO）
- - '#'
  - 众贷
- - '###'
  - DAICO 融资
- - '###'
  - 优势
- - '###'
  - 劣势
- - '###'
  - 公募模式总结
- - '###'
  - 公开发售评估
- - '####'
  - 公平启动与预挖模型
- - '#'
  - 公平发射
- - '#'
  - 预挖发射
- - '##'
  - 简化筛选公开发行项目
- - '####'
  - 项目概要
- - '####'
  - 软顶与硬顶
- - '####'
  - 硬顶分析
- - '###'
  - 代币标准
- - '###'
  - 代币单价
- - '###'
  - 项目白皮书
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '##'
  - 合作伙伴关系
- - '###'
  - 加密对加密（C2C）商业伙伴关系
- - '###'
  - 加密货币与实体经济（C2T）企业合作
- - '###'
  - 传统对传统（T2T）企业合作
- - '###'
  - 非合作关系的案例
- - '###'
  - 行动步骤
- - '####'
  - 结果评估
- - '#'
  - 快速词汇表
- - '###'
  - 51% 攻击
- - '###'
  - 架构层
- - '###'
  - 增值机制
- - '###'
  - Bitcoin
- - '###'
  - 区块浏览器
- - '###'
  - 区块链
- - '###'
  - 区块链三难困境
- - '###'
  - 流通供应量
- - '###'
  - 闭源
- - '###'
  - 代码库
- - '###'
  - 币
- - '###'
  - 共识
- - '###'
  - 共识机制
- - '###'
  - 密码学
- - '###'
  - 加密货币
- - '###'
  - 跨链互操作性
- - '#'
  - 区块链术语定义
- - '##'
  - 跨链互操作性 (Cross-chain Interoperability)
- - '##'
  - 去中心化 (Decentralization)
- - '##'
  - 去中心化应用 (Decentralized Application - dApp)
- - '##'
  - 通缩供给 (Deflationary Supply)
- - '##'
  - 数字资产 (Digital Asset)
- - '##'
  - 数字资产交易所 (Digital Asset Exchange)
- - '##'
  - 分布式账本技术 (Distributed Ledger Technology - DLT)
- - '##'
  - 双重支付 (Double Spending)
- - '##'
  - 最终用户 (End-User)
- - '##'
  - 费用 (Fees)
- - '##'
  - 财务指标 (Financial Metrics)
- - '##'
  - 基本面分析 (Fundamental Analysis)
- - '##'
  - 完全稀释估值 (Fully Diluted Valuation)
- - '##'
  - 创世区块 (Genesis Block)
- - '##'
  - GitHub
- - '##'
  - 治理 (Governance)
- - '##'
  - 硬分叉 (Hard Fork)
- - '##'
  - 哈希率 (Hash Rate)
- - '##'
  - 不可篡改性 (Immutability)
- - '##'
  - 通胀供给 (Inflationary Supply)
- - '##'
  - 延迟 (Latency)
- - '##'
  - 账本 (Ledger)
- - '##'
  - 流动性 (Liquidity)
- - '##'
  - 流动性挖矿 (Liquidity Mining)
- - '##'
  - 精简白皮书 (Litepaper)
- - '##'
  - 主网 (Mainnet)
- - '##'
  - 市值 (Market Capitalization)
- - '##'
  - 最大供应量 (Maximum Supply)
- - '##'
  - 挖矿 (Mining)
- - '##'
  - 最小可行产品 (Minimum Viable Product - MVP)
- - '##'
  - 网络效应 (Network Effects)
- - '##'
  - 网络参与者 (Network Participants)
- - '##'
  - 非同质化代币 (NFT)
- - '##'
  - 节点 (Node)
- - '##'
  - 链上 (On-Chain)
- - '##'
  - 链上指标 (On-Chain Metrics)
- - '##'
  - 开源 (Open-Source)
- - '#'
  - 区块链术语表
- - '##'
  - 开源
- - '##'
  - 无许可
- - '##'
  - 私有区块链
- - '##'
  - 公共区块链
- - '##'
  - 私钥
- - '##'
  - 产品或服务
- - '##'
  - 产品用例
- - '##'
  - 权益证明
- - '##'
  - 工作量证明
- - '##'
  - 公共地址
- - '##'
  - 公共区块链
- - '##'
  - 公钥
- - '##'
  - 假名
- - '##'
  - 路线图
- - '##'
  - 中本聪
- - '##'
  - 可扩展性
- - '##'
  - 智能合约
- - '##'
  - 软分叉
- - '##'
  - 稳定币
- - '##'
  - 质押
- - '##'
  - 代币
- - '##'
  - 代币设计
- - '##'
  - 代币供应量
- - '##'
  - 吞吐量
- - '##'
  - 交易
- - '##'
  - 交易量
- - '##'
  - 验证者
- - '##'
  - 归属期
- - '##'
  - 钱包
- - '##'
  - Web3
- - '##'
  - 白皮书
- - '#'
  - 第 1 章——区块链技术简介
- - '#'
  - 第 2 章——投资数字资产
- - '#'
  - 第 3 章——项目文档
- - '#'
  - 第 4 章——核心产品
- - '#'
  - 第 5 章——最终用户体验
- - '#'
  - 参考文献
- - '##'
  - 第 6 章——区块链架构
- - '#'
  - 第 7 章——代币设计与用例
- - '#'
  - 第 8 章——代币经济学
- - '#'
  - 第 9 章——财务指标
- - '#'
  - 第 10 章——项目团队
- - '#'
  - 第 11 章——项目路线图
- - '#'
  - 第 12 章——项目代码库
- - '#'
  - 第 13 章——激励与奖励
- - '#'
  - 第 14 章——社区与社交媒体
- - '#'
  - 第 15 章——融资与合作伙伴关系
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '#'
  - 索引
- - '#'
  - G
- - '#'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P, Q
- - '#'
  - 索引
- - '##'
  - 合作伙伴关系
- - '##'
  - PATEX
- - '##'
  - Patex networks token (PATEX)
- - '##'
  - PBFT
- - '##'
  - 点对点 (P2P)
- - '##'
  - 无需许可/许可型区块链
- - '##'
  - PoA
- - '##'
  - Polkadot 网络
- - '##'
  - Polygon 网络，代码安全审计 616
- - '##'
  - PoS
- - '##'
  - PoW
- - '##'
  - P2P
- - '##'
  - Practical Byzantine Fault Tolerance (PBFT)
- - '##'
  - 主要激励机制
- - '##'
  - 私有区块链
- - '##'
  - 私募融资
- - '##'
  - 产品测试
- - '##'
  - 编程语言
- - '##'
  - 项目文档
- - '##'
  - 权威证明 (PoA)
- - '##'
  - 权益证明 (PoS)
- - '##'
  - 工作量证明 (PoW)
- - '##'
  - 假名性
- - '##'
  - 公有区块链
- - '##'
  - 公共融资模式
- - '##'
  - Python
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y, Z
