name: Blockchain Basics
name_cn: 区块链基础指南
slug: blockchain-basics
toc:
- - '##'
  - 引言
- - '###'
  - 为何要再写一本关于区块链的书？
- - '###'
  - 您不能从本书中期待什么
- - '###'
  - 本书能带给你什么
- - '###'
  - 对话式风格
- - '###'
  - 不涉及数学与公式
- - '###'
  - 问题领域内的渐进式步骤
- - '###'
  - 使用隐喻和类比
- - '##'
  - 本书的组织结构
- - '###'
  - 第一阶段：术语与技术基础
- - '###'
  - 第二阶段：为什么需要区块链
- - '###'
  - 第三阶段：区块链的工作原理
- - '###'
  - 第四阶段：局限性及如何克服
- - '###'
  - 第五阶段：使用区块链、总结与展望
- - '##'
  - 配套材料
- - '###'
  - 目录
- - '#'
  - 第一部分：术语与技术基础
- - '##'
  - 1. 分层与分面思考
- - '###'
  - 隐喻
- - '###'
  - 软件系统的层
- - '####'
  - 应用与实现
- - '####'
  - 功能性与非功能性方面
- - '###'
  - 同时考虑两个层面
- - '###'
  - 完整性
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 2. 纵观全局
- - '###'
  - 隐喻
- - '###'
  - 支付系统
- - '###'
  - 两种软件架构
- - '###'
  - 分布式系统的优势
- - '####'
  - 更高的计算能力
- - '####'
  - 成本降低
- - '####'
  - 更高的可靠性
- - '####'
  - 自然扩展的能力
- - '###'
  - 分布式系统的劣势
- - '####'
  - 协调开销
- - '####'
  - 通信开销
- - '####'
  - 对网络的依赖
- - '####'
  - 更高的程序复杂性
- - '####'
  - 安全问题
- - '###'
  - 分布式对等系统
- - '###'
  - 集中式与分布式系统的混合
- - '###'
  - 识别分布式系统
- - '###'
  - 区块链的用途
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 3. 认识潜力
- - '###'
  - 比喻
- - '###'
  - 点对点系统如何颠覆整个行业
- - '####'
  - 点对点系统的潜力
- - '###'
  - 术语及其与区块链的联系
- - '####'
  - 点对点系统的定义
- - '####'
  - 点对点系统的架构
- - '####'
  - 点对点系统与区块链之间的联系
- - '###'
  - 区块链的潜力
- - '###'
  - 展望
- - '###'
  - 总结
- - '#'
  - 第二部分
- - '##'
  - 4. 发现核心问题
- - '###'
  - 如何统率一群独立的计算机
- - '###'
  - 隐喻
- - '###'
  - 点对点系统中的信任与完整性
- - '###'
  - 点对点系统中的完整性威胁
- - '####'
  - 技术故障
- - '####'
  - 恶意对等点
- - '###'
  - 区块链需要解决的核心问题
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 5. 厘清术语
- - '###'
  - 术语
- - '####'
  - 一种数据结构
- - '####'
  - 一种算法
- - '####'
  - 一套技术
- - '####'
  - 具有共同应用领域的纯分布式点对点系统的总称
- - '###'
  - 本书中术语的用法
- - '###'
  - 临时定义
- - '###'
  - 所有权管理的作用
- - '###'
  - 本书中区块链的应用领域
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 6. 理解所有权的本质
- - '###'
  - 隐喻
- - '###'
  - 所有权与见证人
- - '###'
  - 所有权的基础
- - '###'
  - 安全相关简介
- - '####'
  - 标识
- - '####'
  - 身份验证
- - '####'
  - 授权
- - '###'
  - 账本的目的与属性
- - '###'
  - 所有权与区块链
- - '###'
  - 前景展望
- - '###'
  - 总结
- - '##'
  - 7. 双重花费
- - '###'
  - 比喻
- - '###'
  - 双重花费问题
- - '###'
  - 术语
- - '####'
  - 双花作为数字商品复制的问题
- - '####'
  - 双花作为分布式点对点账本系统的问题
- - '####'
  - 双花作为分布式点对点系统中完整性被破坏的例子
- - '###'
  - 如何解决双花问题
- - '####'
  - 解决作为数字商品复制问题的双花
- - '####'
  - 解决作为分布式点对点账本系统问题的双花
- - '####'
  - 解决作为分布式点对点系统中完整性被破坏例子的双花
- - '###'
  - 本书中双花的用法
- - '###'
  - 展望
- - '###'
  - 总结
- - '#'
  - 第三部分
- - '##'
  - 8. 规划区块链
- - '###'
  - 目标
- - '###'
  - 起点
- - '###'
  - 遵循的路径
- - '####'
  - 任务 1：描述所有权
- - '####'
  - 任务 2：保护所有权
- - '####'
  - 任务 3：存储交易数据
- - '####'
  - 任务 4：准备可在不可信环境中分发的账本
- - '####'
  - 任务 5：分发账本
- - '####'
  - 任务 6：向账本中添加新交易
- - '####'
  - 任务 7：决定哪些账本代表真相
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 9. 记录所有权
- - '###'
  - 隐喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 思路
- - '###'
  - 关于库存数据和交易数据的简要说明
- - '###'
  - 工作原理
- - '####'
  - 描述所有权转移
- - '####'
  - 维护转移历史记录
- - '###'
  - 为何有效
- - '###'
  - 顺序的重要性
- - '###'
  - 交易历史的完整性
- - '####'
  - 形式正确性
- - '####'
  - 语义正确性
- - '####'
  - 授权
- - '###'
  - 展望
- - '###'
  - 摘要
- - '##'
  - 10. 数据哈希
- - '###'
  - 隐喻
- - '###'
  - 目标
- - '###'
  - 工作原理
- - '####'
  - 快速为任何数据提供哈希值
- - '####'
  - 确定性
- - '####'
  - 伪随机性
- - '####'
  - 单向函数
- - '####'
  - 抗碰撞性
- - '###'
  - 动手尝试
- - '###'
  - 数据哈希的模式
- - '####'
  - 独立哈希
- - '####'
  - 重复哈希
- - '####'
  - 组合哈希
- - '#####'
  - 顺序哈希
- - '#####'
  - 分层哈希
- - '#####'
  - 展望
- - '#####'
  - 总结
- - '##'
  - 11. 现实世界中的哈希
- - '###'
  - 比较数据
- - '####'
  - 目标
- - '####'
  - 思路
- - '####'
  - 工作原理
- - '####'
  - 为何有效
- - '###'
  - 检测数据变更
- - '####'
  - 目标
- - '####'
  - 思路
- - '####'
  - 工作原理
- - '####'
  - 为何有效
- - '###'
  - 以变更敏感的方式引用数据
- - '####'
  - 目标
- - '####'
  - 理念
- - '####'
  - 工作原理
- - '####'
  - 示意图解
- - '####'
  - 原理阐释
- - '###'
  - 以变更敏感的方式存储数据
- - '####'
  - 目标
- - '####'
  - 理念
- - '####'
  - 工作原理
- - '#####'
  - 链式
- - '#####'
  - 树
- - '####'
  - 为何有效
- - '###'
  - 引发耗时的计算
- - '####'
  - 目标
- - '####'
  - 思路
- - '####'
  - 工作原理
- - '####'
  - 一个说明性示例
- - '####'
  - 难度级别
- - '####'
  - 为何如此有效
- - '###'
  - 哈希在区块链中的应用
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 12. 识别与保护用户账户
- - '###'
  - 隐喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 理念
- - '###'
  - 密码学小讲堂
- - '####'
  - 密码学的主要思想
- - '####'
  - 术语
- - '####'
  - 对称密码学
- - '####'
  - 非对称密码学
- - '###'
  - 现实世界中的非对称密码学
- - '####'
  - 创建和分发密钥
- - '####'
  - 使用密钥
- - '#####'
  - 公钥到私钥
- - '#####'
  - 私钥到公钥
- - '###'
  - 区块链中的非对称加密
- - '####'
  - 识别账户
- - '####'
  - 授权交易
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 13. 授权交易
- - '###'
  - 比喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 思路
- - '###'
  - 数字签名简介
- - '####'
  - 创建签名
- - '####'
  - 使用签名验证数据
- - '####'
  - 使用签名识别欺诈
- - '###'
  - 工作原理
- - '####'
  - 签署交易
- - '####'
  - 验证交易
- - '###'
  - 为何有效
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 14. 存储交易数据
- - '###'
  - 隐喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 思路
- - '###'
  - 将一本书转化为区块链数据结构
- - '####'
  - 起点：一本书
- - '####'
  - 转换 1：使页面依赖关系显式化
- - '####'
  - 转换 2：内容外包
- - '####'
  - 转换 3：替换页码
- - '####'
  - 转换 4：创建引用编号
- - '####'
  - 转换 5：取消书脊
- - '####'
  - 目标达成：品味成果
- - '###'
  - 区块链数据结构
- - '####'
  - 订购目录页及其对应内容页构成的逻辑单元
- - '####'
  - 订购目录
- - '####'
  - 内容页
- - '####'
  - 目录页码引用
- - '####'
  - 内容引用编号
- - '###'
  - 在区块链数据结构中存储交易
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 15. 使用数据存储
- - '###'
  - 隐喻
- - '###'
  - 添加新交易
- - '###'
  - 检测变更
- - '####'
  - 更改交易数据的内容
- - '####'
  - 更改 Merkle 树中的引用
- - '####'
  - 替换一笔交易
- - '####'
  - 更改 Merkle 根
- - '####'
  - 更改区块头引用
- - '###'
  - 有序地更改数据
- - '###'
  - 有意更改与无意更改
- - '###'
  - 展望
- - '###'
  - 摘要
- - '##'
  - 16. 保护数据存储
- - '###'
  - 隐喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 思路
- - '###'
  - 关于不可变性的简短探讨
- - '###'
  - 工作原理：宏观概览
- - '####'
  - 让篡改行为无所遁形
- - '####'
  - 强制重写历史以嵌入更改
- - '####'
  - 让添加数据在计算上变得昂贵
- - '###'
  - 工作原理：详细说明
- - '####'
  - 必需数据
- - '####'
  - 创建新区块的流程
- - '####'
  - 验证规则
- - '###'
  - 为何有效
- - '###'
  - 篡改 `Blockchain-Data-Structure` 的成本
- - '###'
  - 现实世界中的不可变数据存储
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 17. 在节点间分发数据存储
- - '###'
  - 隐喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 核心理念
- - '###'
  - 工作原理：概述
- - '###'
  - 工作原理：细节
- - '####'
  - 保持现有连接
- - '####'
  - 建立新连接
- - '####'
  - 分发新信息
- - '###'
  - 工作原理
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 18. 验证并添加交易
- - '###'
  - 隐喻
- - '####'
  - 后果
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 核心理念
- - '###'
  - 工作原理：基础模块
- - '####'
  - 验证规则
- - '#####'
  - 交易数据验证规则
- - '#####'
  - 区块头验证规则
- - '####'
  - 奖励
- - '####'
  - 惩罚
- - '####'
  - 竞争
- - '#####'
  - 速度竞争
- - '#####'
  - 质量竞争
- - '#####'
  - 节点相互监督
- - '###'
  - 工作原理：骨架
- - '###'
  - 工作原理：细节
- - '###'
  - 为何有效
- - '###'
  - 应对不当行为
- - '###'
  - 概述
- - '###'
  - 总结
- - '##'
  - 19. 选择交易历史
- - '###'
  - 比喻
- - '###'
  - 目标
- - '###'
  - 挑战
- - '###'
  - 核心理念
- - '###'
  - 工作原理
- - '####'
  - 最长链准则
- - '####'
  - 最重链准则
- - '###'
  - 选择一条链的后果
- - '####'
  - 孤块
- - '####'
  - 奖励回收
- - '####'
  - 明确所有权
- - '####'
  - 交易重新处理
- - '####'
  - 共同主干增长
- - '####'
  - 最终一致性
- - '####'
  - 抗操纵性
- - '###'
  - 对投票模式的威胁
- - '###'
  - 哈希难题的作用
- - '###'
  - 为何有效
- - '###'
  - 展望
- - '###'
  - 总结
- - '####'
  - 脚注
- - '##'
  - 20. 为完整性付费
- - '###'
  - 隐喻
- - '###'
  - 费用在区块链中的作用
- - '####'
  - 对系统完整性的影响
- - '####'
  - 对系统开放性的影响
- - '####'
  - 对系统去中心化性质的影响
- - '####'
  - 对系统哲学的影响
- - '###'
  - 用于补偿对等节点的支付工具的理想特性
- - '###'
  - 加密货币诞生的迂回之路
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 21. 整合所有部分
- - '###'
  - 回顾概念与技术
- - '###'
  - 什么是区块链？
- - '####'
  - 区块链的目的：应用层的功能性方面
- - '#####'
  - 明确所有权
- - '#####'
  - 转移所有权
- - '####'
  - 区块链的特性：非功能性方面
- - '#####'
  - 高可用性
- - '#####'
  - 抗审查
- - '#####'
  - 可靠
- - '#####'
  - 开放
- - '#####'
  - 伪匿名
- - '#####'
  - 安全
- - '#####'
  - 弹性
- - '#####'
  - 最终一致性
- - '#####'
  - 保持完整性
- - '####'
  - 内部运作：实现层的功能性方面
- - '#####'
  - 所有权逻辑
- - '#####'
  - 交易安全
- - '#####'
  - 交易处理逻辑
- - '#####'
  - 存储逻辑
- - '#####'
  - 点对点架构
- - '#####'
  - 共识逻辑
- - '###'
  - 获得抽象
- - '###'
  - 展望
- - '###'
  - 总结
- - '#'
  - 第四部分：局限性及其解决方案
- - '##'
  - 22. 认识局限性
- - '###'
  - 挑战
- - '###'
  - 区块链的技术局限性
- - '####'
  - 缺乏隐私性
- - '####'
  - 安全模型
- - '####'
  - 可扩展性有限
- - '####'
  - 高昂成本
- - '####'
  - 隐藏的中心化
- - '####'
  - 灵活性缺失
- - '####'
  - 关键规模
- - '###'
  - 区块链的非技术性限制
- - '####'
  - 法律上缺乏认可
- - '####'
  - 用户缺乏接受度
- - '###'
  - 克服局限
- - '####'
  - 技术限制
- - '####'
  - 非技术限制
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 23. 重塑区块链
- - '###'
  - 隐喻
- - '###'
  - 区块链的目标冲突
- - '####'
  - 透明性 vs. 隐私性
- - '####'
  - 安全性 vs. 速度
- - '###'
  - 冲突的根源
- - '###'
  - 解决冲突
- - '####'
  - 在透明性与隐私性之间做出决策
- - '####'
  - 在安全性与速度之间做出决策
- - '###'
  - 区块链的四种版本
- - '###'
  - 后果
- - '####'
  - 点对点架构
- - '#####'
  - 分布式特性
- - '#####'
  - 目的
- - '###'
  - 重新审视区块链的目的
- - '###'
  - 区块链一词在本书余下部分的使用
- - '###'
  - 展望
- - '###'
  - 总结
- - '####'
  - 脚注
- - '#'
  - 第五部分
- - '##'
  - 24. 使用区块链
- - '###'
  - 隐喻
- - '###'
  - 区块链的特性
- - '###'
  - 通用应用模式
- - '####'
  - 存在性证明
- - '####'
  - 不存在性证明
- - '####'
  - 时间证明
- - '####'
  - 顺序证明
- - '####'
  - 身份证明
- - '####'
  - 作者身份证明
- - '####'
  - 所有权证明
- - '###'
  - 具体应用场景
- - '###'
  - 分析区块链应用
- - '####'
  - 使用区块链的条件是否满足？
- - '####'
  - 使用哪种类型的区块链？
- - '####'
  - 使用纯点对点系统带来了哪些附加值？
- - '#####'
  - 什么是应用构想？
- - '#####'
  - 什么是商业模式？
- - '#####'
  - 同行贡献资源并维护完整性如何获得补偿？
- - '###'
  - 展望
- - '###'
  - 总结
- - '##'
  - 25. 总结与展望
- - '###'
  - 隐喻
- - '###'
  - 进一步的演进与替代方案
- - '####'
  - 微小的技术改进与变体
- - '####'
  - 提升可扩展性
- - '####'
  - 概念演进
- - '#####'
  - 访问权限
- - '#####'
  - 隐私性
- - '#####'
  - 共识
- - '####'
  - 交易
- - '####'
  - 库存数据
- - '####'
  - 数据结构
- - '###'
  - 区块链的主要成就
- - '####'
  - 去中介化
- - '####'
  - 自动化
- - '####'
  - 标准化
- - '####'
  - 流程精简
- - '####'
  - 处理速度提升
- - '####'
  - 成本降低
- - '####'
  - 向协议与技术的信任转变
- - '####'
  - 将信任变成一种商品
- - '####'
  - 技术意识的提升
- - '###'
  - 可能的缺点
- - '####'
  - 缺乏隐私
- - '####'
  - 个人责任的丧失
- - '####'
  - 工作岗位的流失
- - '####'
  - 再中介化
- - '###'
  - 未来
- - '####'
  - 有限的爱好者项目
- - '####'
  - 大规模商业应用
- - '####'
  - 政府项目
- - '###'
  - 展望
- - '###'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W、X、Y、Z
