name: Still Searching for Satoshi
name_cn: 《还在寻找中本聪》
slug: still-searching-for-satoshi
toc:
- - '#'
  - 前言
- - '#'
  - 引言
- - '##'
  - 什么是比特币？
- - '###'
  - 比特币作为宇宙图景
- - '###'
  - 比特币作为异托邦
- - '###'
  - 比特币作为超物体
- - '###'
  - 启动搜寻
- - '#'
  - 本书大纲
- - '#'
  - 第1章 虚拟货币
- - '##'
  - 什么是虚拟货币？
- - '###'
  - 虚拟货币之梦
- - '###'
  - 匿名数字现金觉醒
- - '###'
  - 美元解放之路
- - '###'
  - 数字黄金货币
- - '##'
  - 电子商务的兴起
- - '##'
  - 从数字邮资到货币
- - '##'
  - 去中心化的银行
- - '##'
  - 虚拟货币的三个流派
- - '##'
  - 虚拟货币的演变
- - '###'
  - 密码学
- - '#'
  - 第2章 公钥密码学
- - '##'
  - 迪菲-赫尔曼-默克尔
- - '##'
  - RSA 论文
- - '###'
  - 英国人的巧思
- - '##'
  - 将公钥密码学带给大众
- - '###'
  - 哈希
- - '###'
  - 数字签名
- - '#'
  - 第3章 工作量证明
- - '##'
  - 打击垃圾邮件
- - '##'
  - 应用工作量证明
- - '##'
  - 数字邮资
- - '##'
  - 为免费信息增加成本
- - '#'
  - 第4章 加密货币如何成为货币
- - '#'
  - 第5章 公共记录
- - '##'
  - 最早的文字与单式簿记
- - '##'
  - 会计革命与复式记账法
- - '##'
  - 信息技术与三式记账法
- - '##'
  - 去中心化记录
- - '###'
  - 去中心化的点对点公共账目
- - '#'
  - 第6章 比特币
- - '##'
  - 虚拟货币
- - '##'
  - 加密以保护隐私
- - '##'
  - 共享公共账本
- - '##'
  - 点对点网络
- - '##'
  - '工作量证明  '
- - '##'
  - 什么是比特币？
- - '#'
  - 第7章 寻找中本聪
- - '##'
  - 谁干的？
- - '##'
  - 搜索开始
- - '###'
  - “比特币加密货币谜团再起”
- - '##'
  - 搜寻仍在继续
- - '###'
  - 《新闻周刊》报道
- - '###'
  - 中本聪的邻居
- - '###'
  - 新嫌疑人出现
- - '###'
  - 证据累积
- - '##'
  - 剧情愈发复杂
- - '###'
  - 兜兜转转
- - '#'
  - 第8章 分析中本聪
- - '##'
  - 中本聪的历史基础
- - '###'
  - 原始资料与二手资料
- - '###'
  - 遗物与叙述
- - '###'
  - 资料来源的倾向性
- - '###'
  - 与事件的时间接近性
- - '###'
  - 独立印证
- - '###'
  - 简约性原则
- - '###'
  - '*Ad Fontes*（追本溯源）：资料来源能告诉我们什么？'
- - '###'
  - 比特币白皮书
- - '###'
  - 信函往来
- - '###'
  - 技术取证证据
- - '###'
  - 采访
- - '###'
  - 资料来源与中本聪
- - '##'
  - 构建中本聪的画像
- - '##'
  - 假设
- - '###'
  - 统一性假设
- - '###'
  - 单一性假设
- - '###'
  - 常态假设
- - '##'
  - 剖析中本聪
- - '###'
  - 性别
- - '###'
  - 年龄
- - '###'
  - 地理定位
- - '###'
  - 国籍
- - '###'
  - 教育与工作
- - '###'
  - 价值观
- - '##'
  - 中本聪画像总结
- - '#'
  - 第9章 常见嫌疑人？
- - '##'
  - 重新绘制嫌疑人名单
- - '##'
  - 聚焦亚当·拜克
- - '###'
  - 拜克在比特币领域的缺席
- - '###'
  - 拜克与中本聪的互动
- - '###'
  - 其他证据
- - '###'
  - 然而，话说回来……
- - '##'
  - 寻找中本聪的结论
- - '#'
  - 第10章 货币
- - '##'
  - 货币的多样性
- - '###'
  - 罗塞尔岛民
- - '###'
  - 香烟
- - '###'
  - 积分
- - '###'
  - 货币的多面性
- - '##'
  - 什么是货币？
- - '###'
  - 货币的职能
- - '###'
  - 交换媒介
- - '###'
  - 记账单位
- - '###'
  - 价值储存
- - '##'
  - 货币与交换的历史
- - '###'
  - 交换
- - '###'
  - 以物易物
- - '###'
  - 原始货币
- - '###'
  - 银行业
- - '###'
  - 硬币
- - '###'
  - 货币的发明
- - '##'
  - 货币的动态变化
- - '###'
  - 货币的关键因素
- - '####'
  - 标准
- - '####'
  - 铸币
- - '###'
  - 法定货币
- - '###'
  - 供给与需求
- - '###'
  - 货币如何变得有价值
- - '##'
  - 货币的关键动态
- - '##'
  - 比特币与货币
- - '###'
  - 作为货币的比特币
- - '###'
  - 稀缺性与价值存储
- - '###'
  - 拉高与抛售
- - '###'
  - 作为动态系统的比特币概览
- - '#'
  - 第11章 社会组织
- - '##'
  - 黑客与开源的起源
- - '##'
  - 开源社区类别
- - '###'
  - 玩具型项目
- - '###'
  - 体育场型项目
- - '##'
  - 密码朋克
- - '##'
  - 自由意志主义与奥地利经济学
- - '##'
  - 比特币的社会结构
- - '##'
  - 网格/群体特征描述
- - '##'
  - 比特币、社会与宇宙
- - '#'
  - 第12章 宗教
- - '##'
  - 什么是宗教？
- - '##'
  - 先知
- - '##'
  - 经文
- - '###'
  - 货物崇拜
- - '###'
  - 千年主义
- - '##'
  - 比特币标准的世界
- - '##'
  - 奇点
- - '###'
  - 超人类主义者与比特币的起源
- - '##'
  - 千禧年统治的到来
- - '##'
  - 比特币与宗教
- - '#'
  - 第13章 未来
- - '##'
  - 规范化
- - '##'
  - 边缘巩固
- - '##'
  - 民族国家的消失
- - '##'
  - 文章排版
- - '##'
  - 民族国家的式微
- - '##'
  - 奇点
- - '##'
  - 后末日
- - '##'
  - 星际航行
- - '##'
  - 未来还会有比特币吗？
- - '#'
  - 第14章 超越
- - '##'
  - 那里有生命吗？
- - '##'
  - 生命是什么？
- - '##'
  - 生命的特征与比特币
- - '###'
  - 结构
- - '###'
  - 繁殖
- - '###'
  - 适应
- - '###'
  - 新陈代谢
- - '###'
  - 生长
- - '###'
  - 对刺激的反应
- - '##'
  - 比特币是活的吗？
- - '##'
  - 将大象重新拼合
- - '#'
  - 附录A 术语索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I
- - '##'
  - J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W, X
- - '##'
  - Y, Z
