name: Decoding Blockchain for Business
name_cn: 商业区块链解码指南
slug: decoding-blockchain-for-business
toc:
- - '#'
  - 引言
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 1. 商业中的区块链
- - '##'
  - 关于过去的一点简述
- - '###'
  - 加密货币崩盘
- - '###'
  - 现在
- - '##'
  - 区块链初创企业与未来图景
- - '##'
  - 区块链投资趋势与技术基础
- - '###'
  - 区块链技术快速入门
- - '#'
  - 构建基石
- - '##'
  - 区块链还是分布式账本？
- - '##'
  - 区块链地址
- - '##'
  - 区块链钱包
- - '##'
  - 节点
- - '##'
  - 挖矿
- - '##'
  - 共识协议
- - '###'
  - 工作量证明
- - '###'
  - 权益证明
- - '###'
  - 委托权益证明
- - '###'
  - 权威证明
- - '###'
  - 区块链平台中使用的其他协议
- - '##'
  - 区块链分叉
- - '##'
  - 侧链
- - '##'
  - 区块链技术栈
- - '##'
  - DAG（有向无环图）
- - '##'
  - BlockDAG
- - '#'
  - 2. 区块链与其他新兴技术
- - '##'
  - 区块链与物联网
- - '##'
  - 区块链平台的风险与劣势
- - '##'
  - 区块链与人工智能
- - '##'
  - 区块链与云
- - '###'
  - 云服务与区块链技术的优势与挑战
- - '##'
  - 区块链与网络安全
- - '###'
  - 区块链与机器人流程自动化
- - '##'
  - 区块链与量子计算
- - '###'
  - 量子计算与区块链安全
- - '##'
  - 区块链与智慧城市
- - '###'
  - 区块链与环境
- - '###'
  - 区块链与贫困
- - '#'
  - 区块链技术的局限性
- - '#'
  - 区块链与行业应用案例
- - '##'
  - 区块链与金融
- - '###'
  - 财务部门
- - '####'
  - 企业资源计划系统
- - '####'
  - 客户关系管理系统
- - '#####'
  - 其他系统
- - '#####'
  - 开票
- - '#####'
  - 数据仪表盘
- - '####'
  - 保证与审计
- - '####'
  - 会计
- - '####'
  - 保险业
- - '####'
  - 房地产
- - '####'
  - 法律行业
- - '####'
  - 供应链
- - '####'
  - 资源
- - '###'
  - 风险管理与网络安全
- - '####'
  - 能源市场
- - '####'
  - 银行业
- - '####'
  - 金融工具
- - '##'
  - 金融世界之外
- - '###'
  - 媒体行业
- - '###'
  - 医疗卫生领域
- - '###'
  - 公共部门
- - '###'
  - 身份与投票应用
- - '###'
  - 游戏产业
- - '###'
  - 教育
- - '###'
  - 人力资源
- - '###'
  - 汽车工业
- - '###'
  - 智能手机行业
- - '#'
  - 区块链与监管：法律世界
- - '##'
  - 欧洲的税收与加密货币监管
- - '##'
  - 亚洲的税收与加密货币监管
- - '##'
  - 非洲的税收与加密货币监管
- - '##'
  - 大洋洲的税收与加密货币监管
- - '##'
  - 美洲的税收与加密货币监管
- - '##'
  - GDPR 与区块链
- - '###'
  - GDPR 与区块链技术的冲突分析
- - '####'
  - 参与者角色界定
- - '####'
  - 数据修改与删除的矛盾
- - '####'
  - 实际影响与解决方案
- - '####'
  - 沟通义务
- - '####'
  - 设计考量与未来展望
- - '###'
  - GDPR 对区块链技术的适用性
- - '####'
  - GDPR 下个人数据的定义
- - '####'
  - 交易数据与个人数据
- - '#'
  - 5. 区块链与加密货币
- - '##'
  - 加密市场简史
- - '###'
  - 加密货币市场
- - '###'
  - 核心加密货币概念
- - '####'
  - 原子交易
- - '####'
  - 首次代币发行（ICO）
- - '####'
  - 部分准备金银行制度与比特币
- - '###'
  - 稳定币
- - '###'
  - 数字孪生与区块链
- - '###'
  - 区块链与数字身份
- - '###'
  - 加密货币的价值从何而来？
- - '###'
  - 加密货币粉尘
- - '###'
  - 交易所与攻击
- - '###'
  - 加密货币市值
- - '###'
  - 加密货币期货交易
- - '###'
  - 加密货币股息
- - '###'
  - 关联托管合约
- - '###'
  - 双重投注策略
- - '###'
  - 代币管理注册表
- - '###'
  - 一些结语
