name: Introducing Blockchain Applications
name_cn: 区块链应用入门指南
slug: introducing-blockchain-applications
toc:
- - '#'
  - 1. 通过分布式系统介绍区块链应用
- - '##'
  - 1.1 区块链应用案例
- - '##'
  - 1.2 本书涵盖内容
- - '#'
  - 2. 区块链简介
- - '##'
  - 2.1 区块链简史
- - '##'
  - 2.2 区块链的应用
- - '##'
  - 2.3 为何区块链如此重要
- - '##'
  - 2.4 本章小结
- - '#'
  - 3. 比特币
- - '##'
  - 3.1 比特币的历史
- - '###'
  - 3.1.1 链式时间戳与默克尔树
- - '###'
  - 3.1.2 分布式共识
- - '##'
  - 3.2 工作量证明
- - '###'
  - 3.2.1 中本聪的天才之处
- - '##'
  - 3.3 密钥与地址
- - '###'
  - 3.3.1 私钥
- - '###'
  - 3.3.2 公钥
- - '###'
  - 3.3.3 比特币地址
- - '###'
  - 3.3.4 数字签名
- - '####'
  - 3.3.4.1 验证数字签名
- - '####'
  - 3.3.4.2 理解 ECDSA 签名/验证的数学原理
- - '##'
  - 3.4 交易
- - '###'
  - 3.4.1 未花费交易输出（UTXO）
- - '###'
  - 3.4.2 输入与输出 (I&O)
- - '###'
  - 3.4.3 支付到公钥哈希（P2PKH）
- - '###'
  - 3.4.4 观察输出方
- - '###'
  - 3.4.5 观察输入方
- - '###'
  - 3.4.6 验证流程
- - '###'
  - 3.4.7 交易结构
- - '###'
  - 3.4.8 交易费用
- - '##'
  - 3.5 交易流程
- - '##'
  - 3.6 区块
- - '###'
  - 3.6.1 区块的结构
- - '###'
  - 3.6.2 区块头部
- - '##'
  - 3.7 中本聪共识
- - '###'
  - 3.7.1 矿工节点
- - '###'
  - 3.7.2 Coinbase 交易
- - '###'
  - 3.7.3 构建区块头
- - '###'
  - 3.7.4 难度目标
- - '###'
  - 3.7.5 工作量证明
- - '###'
  - 3.7.6 验证新区块
- - '###'
  - 3.7.7 区块链分叉
- - '##'
  - 3.8 总结
- - '#'
  - 4. 以太坊
- - '##'
  - 4.1 区块链作为状态转换系统
- - '##'
  - 4.2 以太坊账户
- - '###'
  - 4.2.1 账户状态
- - '###'
  - 4.2.2 外部拥有账户（EOA）
- - '###'
  - 4.2.3 合约账户
- - '###'
  - 4.2.4 外部拥有账户与合约账户的区别
- - '###'
  - 4.2.5 存储密钥：加密密钥库
- - '##'
  - 4.3 世界状态
- - '###'
  - 4.3.1 字典树
- - '###'
  - 4.3.2 基数树
- - '###'
  - 4.3.3 Patricia Trie
- - '###'
  - 4.3.4 以太坊修改版默克尔帕特里夏树
- - '###'
  - 4.3.5 存储根
- - '###'
  - 4.3.6 为什么要用默克尔树？
- - '##'
  - 4.4 以太坊虚拟机
- - '##'
  - 4.5 什么是 Gas？
- - '###'
  - 存储的 Gas 费用
- - '###'
  - Gas 的目的
- - '##'
  - 4.6 交易与消息
- - '###'
  - 交易结构
- - '###'
  - 交易数字签名流程
- - '###'
  - 4.6.3 从数字签名中恢复公钥
- - '###'
  - 4.6.4 三种交易类型
- - '###'
  - 4.6.5 消息
- - '##'
  - 4.7 以太坊状态转换函数
- - '##'
  - 4.8 以太坊区块链中的交易流程
- - '##'
  - 4.9 交易状态
- - '##'
  - 4.10 区块结构
- - '###'
  - 4.10.1 交易收据
- - '###'
  - 4.10.2 叔块
- - '##'
  - 4.11 以太坊简化版 GHOST 协议
- - '##'
  - 4.12 以太坊共识机制
- - '###'
  - 4.12.1 工作量证明算法 (PWA)
- - '##'
  - 4.13 以太坊 2.0
- - '##'
  - 4.14 总结
- - '#'
  - 5. 权益证明：未来的共识机制
- - '##'
  - 5.1 基于链的权益证明
- - '###'
  - 5.1.1 基于委员会的权益证明
- - '###'
  - 5.1.2 “无成本”难题
- - '####'
  - 5.1.2.1 Slash 机制
- - '####'
  - 5.1.2.2 Dunkle 机制
- - '###'
  - 5.1.3 基于 BFT 的权益证明
- - '##'
  - 5.2 以太坊 Casper
- - '##'
  - 5.3 Casper 实现
- - '##'
  - 5.4 本章小结
- - '#'
  - 6. Hyperledger Fabric
- - '##'
  - 6.1 高层次视角
- - '##'
  - 6.2 资产
- - '##'
  - 6.3 链码
- - '##'
  - 6.4 账本的特征
- - '##'
  - 6.5 隐私
- - '##'
  - 6.6 身份
- - '###'
  - 6.6.1 公钥基础设施 (PKI)
- - '###'
  - 6.6.2 数字证书
- - '##'
  - 6.7 证书颁发机构
- - '##'
  - 6.8 成员服务提供者（MSP）
- - '###'
  - 本地 MSP
- - '###'
  - 通道 MSP
- - '###'
  - 存储 MSP 数据
- - '##'
  - 6.9 对等节点
- - '###'
  - 对等节点与组织
- - '###'
  - 对等节点与身份
- - '###'
  - 对等节点、共识与排序
- - '##'
  - 6.10 Hyperledger Fabric 共识
- - '###'
  - 阶段 1：提案
- - '###'
  - 阶段 2：交易被排序并打包成区块
- - '##'
  - 6.11 账本
- - '###'
  - 区块链
- - '###'
  - 交易
- - '###'
  - 世界状态
- - '##'
  - 6.12 排序服务实现
- - '##'
  - 6.13 总结
- - '#'
  - 7. 区块链共识算法
- - '##'
  - 7.1 共识算法与加密货币
- - '##'
  - 7.2 共识模型的目标
- - '##'
  - 7.3 不同类型共识算法
- - '##'
  - 7.4 区块链共识算法的类型
- - '###'
  - 7.4.1 工作量证明（PoW）
- - '###'
  - 7.4.2 权益证明（PoS）
- - '####'
  - 7.4.2.1 委托权益证明（PoSD）
- - '####'
  - 7.4.2.2 租赁权益证明（LPoS）
- - '###'
  - 7.4.3 拜占庭容错（BFT）
- - '###'
  - 7.4.4 实用拜占庭容错（Practical-BFT）
- - '###'
  - 7.4.5 委托拜占庭容错（dBFT）
- - '###'
  - 7.4.6 有向无环图（DAG）
- - '###'
  - 7.4.7 容量证明（PoC）
- - '###'
  - 7.4.8 燃烧证明（PoB）
- - '###'
  - 7.4.9 身份证明（PoI）
- - '###'
  - 7.4.10 活动证明（PoA）
- - '###'
  - 7.4.11 消逝时间证明（PoET）
- - '###'
  - 7.4.12 重要性证明（PoI）
- - '##'
  - 7.5 分布式系统与区块链技术中的共识
- - '##'
  - 7.6 复习题
- - '##'
  - 7.7 复习答案
- - '##'
  - 7.8 本章小结
- - '#'
  - 8. 区块链项目共识算法
- - '##'
  - 8.1 启动项目
- - '##'
  - 8.2 Python 代码
- - '###'
  - Proof of work algorithm
- - '###'
  - you can check if transactions are valid here
- - '##'
  - 8.3 示例 2：在 Python 中使用 Flask
- - '###'
  - 8.3.1 第一步：创建一个简单的工作量证明
- - '###'
  - We must make sure that the Dictionary is Ordered, or we'll have inconsistent hashes
- - '###'
  - 8.3.2 第二步：为区块链创建一个 API 端点
- - '###'
  - Instantiate our Node
- - '###'
  - Generate a globally unique address for this node
- - '###'
  - Instantiate the Blockchain
- - '###'
  - Check that the required fields are in the POST'ed data
- - '###'
  - Create a new Transaction
- - '###'
  - 8.3.3 第三步：创建一个区块链矿工
- - '###'
  - 8.3.4 第四步：运行你的区块链项目
- - '##'
  - 8.4 复习题
- - '##'
  - 8.5 复习题答案
- - '##'
  - 8.6 总结
- - '#'
  - 9. 实时系统
- - '##'
  - 9.1 理解实时系统
- - '##'
  - 9.2 实时系统参考模型
- - '###'
  - 9.2.1 故障安全系统与故障可运行系统
- - '###'
  - 9.2.2 可保证的及时性系统与尽力而为系统
- - '##'
  - 9.3 实时系统分类
- - '###'
  - 9.3.1 资源充足性
- - '###'
  - 9.3.2 罕见事件情况下的可预测性
- - '###'
  - 9.3.3 状态与事件
- - '###'
  - 9.3.4 时间触发系统与事件触发系统
- - '##'
  - 9.4 时间要求
- - '##'
  - 9.5 调度算法分类
- - '###'
  - 9.5.1 硬实时与软实时调度
- - '###'
  - 9.5.2 动态与静态调度器
- - '###'
  - 9.5.3 可抢占/非可抢占调度器
- - '###'
  - 9.5.4 静态调度
- - '###'
  - 9.5.5 动态调度
- - '###'
  - 9.5.6 独立任务调度
- - '##'
  - 9.6 复习题
- - '##'
  - 9.7 复习题答案
- - '##'
  - 9.8 总结
- - '#'
  - 10. 实时系统中的调度
- - '##'
  - 10.1 调度的概念
- - '##'
  - 10.2 约束类型
- - '###'
  - 10.2.1 独立任务调度约束
- - '###'
  - 10.2.2 调度依赖任务
- - '##'
  - 10.3 复习题与答案
- - '###'
  - 10.3.1 复习题
- - '###'
  - 10.3.2 答案
- - '##'
  - 10.4 本章小结
- - '#'
  - 11. 基于模型的工程
- - '##'
  - 11.1 面向区块链的模型驱动方法
- - '##'
  - 11.2 模型驱动开发
- - '###'
  - 11.2.1 区块链分层模型
- - '###'
  - 11.2.2 模型与元模型
- - '###'
  - 11.2.3 模型
- - '###'
  - 11.2.4 元模型
- - '##'
  - 11.3 构建元模型与模型
- - '##'
  - 11.4 建模语言的类别
- - '##'
  - 11.5 为信息物理系统设计元模型
- - '##'
  - 11.6 CPS 元模型示例
- - '###'
  - 11.6.1 元对象设施
- - '##'
  - 11.7 复习题
- - '##'
  - 11.8 复习题答案
- - '##'
  - 11.9 总结
- - '#'
  - 12. BLOCKLY 4SOS
- - '##'
  - 12.1 SoS 建模
- - '##'
  - 12.2 SoS 行为仿真环境
- - '##'
  - 12.3 复习题
- - '##'
  - 12.4 复习题答案
- - '##'
  - 12.5 本章小结
- - '#'
  - 13. 网络物理系统项目
- - '##'
  - 13.1 使用 Kilobots
- - '###'
  - 13.1.1 Kilobots 的运动
- - '##'
  - 13.2 项目需求
- - '###'
  - 13.2.1 架构
- - '###'
  - 13.2.2 项目通信
- - '###'
  - 13.2.3 时间
- - '###'
  - 13.2.4 动态性
- - '###'
  - 13.2.5 可靠性
- - '##'
  - 13.3 Blockly4SoS 模型
- - '##'
  - 13.4 实现项目
- - '##'
  - 13.5 执行项目
- - '##'
  - 13.6 项目代码
- - '##'
  - 13.7 本章小结
- - '#'
  - 14. 使用 MATLAB 智能农场项目
- - '##'
  - 14.1 智能农场项目描述
- - '###'
  - 14.1.1 项目需求
- - '###'
  - 14.1.2 解决方案提示
- - '##'
  - 14.2 实施项目
- - '###'
  - 14.2.1 环境模型
- - '###'
  - 14.2.2 传感器模型
- - '###'
  - 14.2.3 多机器人激光雷达传感器
- - '##'
  - 14.3 系统架构
- - '##'
  - 14.4 系统建模
- - '###'
  - 14.4.1 机器人可视化工具和激光雷达传感器
- - '###'
  - 14.4.2 避障逻辑与*两阶段提交（2PC）*协议概念
- - '###'
  - 14.4.3 北农场、南农场与仓库的架构
- - '##'
  - 14.5 实现两阶段提交协议
- - '###'
  - 14.5.1 需求
- - '###'
  - 14.5.2 遇到的问题
- - '##'
  - 14.6 总结
- - '#'
  - 15. Platoon 项目
- - '##'
  - 15.1 游戏环境
- - '###'
  - 15.1.1 SoS 组织
- - '###'
  - 15.1.2 计算机系统级
- - '###'
  - 15.1.3 系统级组织
- - '###'
  - 15.1.4 涌现观点
- - '###'
  - 15.1.5 动态性观点
- - '###'
  - 15.1.6 时间观点
- - '##'
  - 15.2 网络物理系统
- - '##'
  - 15.3 Kilobot 源代码
- - '##'
  - 15.4 Kilobots 的运动
- - '##'
  - 15.5 赛博物理建模
- - '###'
  - StraightDelay
- - '###'
  - 左转领航者
- - '###'
  - TurnDelay
- - '###'
  - FollowerPrgrm
- - '###'
  - 直行跟随者
- - '##'
  - 15.6 总结
- - '#'
  - 16. 区块链技术与分布式系统的未来范围及 B-Coin 项目
- - '##'
  - 16.1 区块链与物联网安全
- - '###'
  - 16.1.1 区块链在物联网中的实现与用例
- - '###'
  - 16.1.2 将区块链集成到物联网中的挑战
- - '##'
  - 16.2 安全建议
- - '##'
  - 16.3 区块链安全与隐私
- - '##'
  - 16.4 未来展望
- - '###'
  - 16.4.1 区块链架构：私有、公有或混合公有区块链设计
- - '###'
  - 16.4.2 激励机制
- - '###'
  - 16.4.3 数据隐私
- - '##'
  - 16.5 对区块链持有现实预期
- - '##'
  - 16.6 食品认证
- - '##'
  - 16.7 智能合约与公证人
- - '###'
  - 16.7.1 将区块链技术应用于智能合约
- - '###'
  - 16.7.2 在市场中开发区块链
- - '###'
  - 16.7.3 区块链的地缘政治
- - '###'
  - 16.7.4 书籍、白皮书与区块链
- - '##'
  - 16.8 比特币（B 币）示例项目
- - '###'
  - 16.8.1 项目代码
- - '####'
  - 添加交易
- - '####'
  - 添加节点
- - '####'
  - 用最长链替换当前链
- - '####'
  - 创建区块链
- - '####'
  - 这是区块链的 Python 类
- - '####'
  - 区块链的 GET 方法
- - '####'
  - 区块链的验证方法
- - '####'
  - 区块链的 POST 方法
- - '####'
  - 连接到节点
- - '####'
  - 更换链的方法
- - '###'
  - 16.8.2 将区块链转变为加密货币
- - '###'
  - 16.8.3 GET 方法
- - '###'
  - 16.8.4 POST 方法
- - '##'
  - 16.9 节点的功能
- - '###'
  - 16.9.1 组合有效交易以创建新区块候选
- - '###'
  - 16.9.2 防御墙上的算力（哈希率）
- - '##'
  - 16.10 创造新比特币
- - '###'
  - 16.10.1 去中心化的概念
- - '##'
  - 16.11 总结
- - '#'
  - 17. 人工智能与区块链监控的自动驾驶车辆管理项目
- - '###'
  - 17.1 区块链与人工智能之间的联系
- - '####'
  - 17.1.1 应用中的 AI 与区块链
- - '####'
  - 17.1.2 AI 在制造实时智能决策机器中的角色
- - '##'
  - 17.2 区块链用于信息共享与交换
- - '###'
  - 备注
- - '###'
  - 自动驾驶车辆管理的优势包括：
- - '##'
  - 17.3 可靠性与安全性
- - '##'
  - 17.4 系统追踪
- - '##'
  - 17.5 本工作的动机与目标
- - '##'
  - 17.6 汽车应用
- - '###'
  - 17.6.1 作为信息物理系统的自动驾驶汽车
- - '##'
  - 17.7 安全性与自动驾驶汽车
- - '##'
  - 17.8 控制器：检测器的问题
- - '##'
  - 17.9 系统分析方法
- - '###'
  - 初步阶段与介绍
- - '##'
  - 17.10 实验方法
- - '###'
  - 17.10.1 控制器测试
- - '###'
  - 17.10.2 监控器或观察测试
- - '###'
  - 安全监控器测试与控制器重训练
- - '###'
  - 17.10.3 控制器重训练
- - '##'
  - 17.11 方法实现与结果
- - '##'
  - 17.12 工具与软件
- - '###'
  - 17.12.1 CARLA 模拟器
- - '###'
  - 17.12.2 控制器设置
- - '###'
  - 17.12.3 安全监控器实现
- - '##'
  - 17.13 实验活动
- - '##'
  - 17.14 结果
- - '###'
  - 17.14.1 测试控制器（第一阶段）
- - '####'
  - 排版后的内容
- - '###'
  - 17.14.2 监控评估（第二阶段）
- - '###'
  - 17.14.3 重新训练与复检（第 3 阶段）
- - '##'
  - 17.15 总结
- - '#'
  - 18. 总结
- - '##'
  - 18.1 区块链在政策背景中的应用
- - '###'
  - 18.1.1 避免公地悲剧
- - '##'
  - 18.2 变革产业与市场
- - '###'
  - 18.2.1 政府与公共部门
- - '###'
  - 18.2.2 数据管理
- - '##'
  - 18.3 安全建议
- - '###'
  - 18.3.1 隐私政策
- - '###'
  - 18.3.2 智能合约
- - '###'
  - 18.3.3 分布式计算系统
- - '###'
  - 18.3.4 分布式信息系统
- - '###'
  - 18.3.5 分布式普适系统
- - '##'
  - 18.4 客户端与服务器架构剖析
- - '###'
  - 18.4.1 客户端
- - '###'
  - 18.4.2 服务器
- - '##'
  - 18.5 关于分布式系统的问题
- - '###'
  - 18.5.1 中间件在分布式系统中的作用是什么？
- - '###'
  - 18.5.2 什么是（分布式的）透明性？
- - '###'
  - 18.5.3 为什么在分布式系统中有时很难隐藏故障的发生及其恢复？
- - '###'
  - 18.5.4 在开发分布式系统时使用两种不同的编程语言是否可行？
- - '###'
  - 18.5.5 缓存和复制之间的区别是什么？
- - '###'
  - 18.5.6 什么时候使用集群计算机比使用网格计算机更合适？
- - '###'
  - 18.5.7 如何区分不同类型的分布式系统？
- - '##'
  - 18.6 区块链的优势与劣势
- - '##'
  - 18.7 区块链技术与成本削减
- - '##'
  - 18.8 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J
- - '###'
  - K
- - '###'
  - L
- - '###'
  - M
- - '###'
  - N
- - '###'
  - O
- - '###'
  - P
- - '###'
  - Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U
- - '###'
  - V
- - '###'
  - W, X, Y, Z
