name: Introducing Blockchain with Lisp
name_cn: Lisp 区块链入门指南
slug: introducing-blockchain-with-lisp
toc:
- - '#'
  - 前言
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校
- - '#'
  - 1. 区块链简介
- - '##'
  - 1.1 动机与基本定义
- - '##'
  - 1.2 加密
- - '###'
  - 1.2.1 函数
- - '###'
  - 1.2.2 对称密钥算法
- - '###'
  - 1.2.3 非对称密钥算法
- - '##'
  - 1.3 哈希
- - '##'
  - 1.4 智能合约
- - '##'
  - 1.5 比特币
- - '##'
  - 1.6 工作流程示例
- - '##'
  - 1.7 总结
- - '#'
  - 2. Racket 编程语言
- - '##'
  - 2.1 Lisp 简介
- - '###'
  - 2.1.1 数据结构与递归
- - '###'
  - 2.1.2 语言与语法
- - '##'
  - 2.2 配置与安装
- - '##'
  - 2.3 Racket 简介
- - '###'
  - 2.3.1 基本类型
- - '###'
  - 2.3.2 列表、求值和引号
- - '####'
  - 2.3.2.1 点对
- - '####'
  - 2.3.2.2 添加定义
- - '####'
  - 2.3.2.3 过程与函数
- - '###'
  - 2.3.6 条件过程
- - '###'
  - 2.3.7 递归过程
- - '###'
  - 2.3.8 返回过程的过程
- - '###'
  - 2.3.9 通用高阶过程
- - '###'
  - 2.3.10 包
- - '###'
  - 2.3.11 作用域
- - '###'
  - 2.3.12 突变
- - '###'
  - 2.3.13 结构体
- - '###'
  - 2.3.14 线程
- - '##'
  - 2.4 创建可执行文件
- - '##'
  - 2.5 总结
- - '#'
  - 3. 区块链实现
- - '##'
  - 3.1 wallet.rkt 文件
- - '##'
  - 3.2 block.rkt 文件
- - '###'
  - 3.2.1 构造
- - '###'
  - 3.2.2 哈希计算与验证
- - '###'
  - 3.2.3 Hashcash 算法
- - '##'
  - 3.3 `utils.rkt` 文件
- - '##'
  - 3.4 交易
- - '###'
  - 3.4.1 `transaction-io.rkt` 文件
- - '###'
  - 3.4.2 `transaction.rkt` 文件
- - '####'
  - 3.4.2.1 数字签名
- - '####'
  - 3.4.2.2 处理交易
- - '##'
  - 3.5 blockchain.rkt 文件
- - '###'
  - 3.5.1 初始化
- - '###'
  - 3.5.2 奖励
- - '###'
  - 3.5.3 添加交易
- - '###'
  - 3.5.4 验证
- - '##'
  - 3.6 集成组件
- - '###'
  - 3.6.1 `main-helper.rkt` 文件
- - '###'
  - 3.6.2 `main.rkt` 文件
- - '##'
  - 3.7 小结
- - '#'
  - 4. 扩展区块链
- - '##'
  - 4.1 智能合约实现
- - '###'
  - 4.1.1 文件 `smart-contracts.rkt`
- - '###'
  - 4.1.2 更新现有代码
- - '##'
  - 4.2 点对点实现
- - '###'
  - 4.2.1 `peer-to-peer.rkt` 文件
- - '####'
  - 4.2.1.1 对等节点上下文结构
- - '####'
  - 4.2.1.2 通用处理器
- - '####'
  - 4.2.1.3 服务器端实现
- - '####'
  - 4.2.1.4 客户端实现
- - '####'
  - 4.2.1.5 整合各部分
- - '###'
  - 4.2.2 更新现有代码
- - '###'
  - 4.2.3 `main-p2p.rkt` 文件
- - '##'
  - 4.3 总结
