name: Beginning Blockchain
name_cn: 区块链入门指南
slug: beginning-blockchain
toc:
- - '##'
  - 引言
- - '##'
  - 致谢
- - '#'
  - 目录
- - '#'
  - 1. 区块链简介
- - '##'
  - 区块链的前世今生
- - '##'
  - 什么是区块链？
- - '###'
  - 步骤 1：
- - '###'
  - 步骤 2：
- - '###'
  - 步骤 3：
- - '##'
  - 中心化与去中心化系统
- - '###'
  - 中心化系统
- - '###'
  - 去中心化系统
- - '##'
  - 区块链的层次结构
- - '###'
  - 应用层
- - '###'
  - 执行层
- - '####'
  - 语义层
- - '####'
  - 传播层
- - '####'
  - 共识层
- - '##'
  - 为什么区块链很重要？
- - '###'
  - 中心化系统的局限性
- - '###'
  - 区块链的采用现状
- - '##'
  - 区块链的用途与用例
- - '##'
  - 总结
- - '#'
  - 2. 区块链的工作原理
- - '##'
  - 奠定区块链基础
- - '##'
  - 密码学
- - '###'
  - 对称密钥密码学
- - '####'
  - 柯克霍夫原则与异或函数
- - '###'
  - 流密码 vs. 分组密码
- - '###'
  - 一次性密码本
- - '####'
  - 示例
- - '#####'
  - 数据加密标准
- - '###'
  - 高级加密标准
- - '####'
  - AES 密钥扩展
- - '#####'
  - 排版后的 Markdown 文档
- - '###'
  - 对称密钥密码学中的挑战
- - '##'
  - 密码学哈希函数
- - '###'
  - 关于不同哈希函数的温馨提示
- - '###'
  - SHA-2
- - '###'
  - SHA-256 与 SHA-512
- - '###'
  - RIPEMD
- - '###'
  - SHA-3
- - '####'
  - SHA-3 海绵结构与 Keccak-f
- - '###'
  - 哈希函数的应用
- - '####'
  - 哈希函数代码示例
- - '#####'
  - '-*- coding: utf-8 -*-'
- - '#####'
  - hashlib 模块是 Python 中流行的哈希计算模块
- - '#####'
  - hashlib 中提供了 md5()、sha1()、sha224()、sha256()、sha384()和 sha512()的构造函数
- - '#####'
  - 比较 SHA224、SHA256、SHA384、SHA512 的摘要
- - '#####'
  - 所有哈希输出都是唯一的
- - '#####'
  - RIPEMD160 160 位哈希示例
- - '#####'
  - 密钥派生算法：
- - '#####'
  - 原生哈希算法无法抵御暴力破解攻击。
- - '#####'
  - 密钥派生算法用于保护密码哈希。
- - '#####'
  - 检查哈希的属性
- - '#####'
  - 将迭代器附加到文本末尾
- - '#####'
  - 显示输入和哈希结果
- - '###'
  - MAC 与 HMAC
- - '##'
  - 非对称密钥密码学
- - '###'
  - RSA
- - '####'
  - 模运算
- - '###'
  - 密钥对的生成
- - '###'
  - 使用密钥对进行加密/解密
- - '####'
  - 数字签名算法
- - '####'
  - 椭圆曲线密码学
- - '###'
  - 椭圆曲线数字签名算法
- - '####'
  - 密钥生成
- - '####'
  - 签名生成
- - '####'
  - 签名验证
- - '###'
  - 非对称密钥密码学代码示例
- - '####'
  - '-*- coding: utf-8 -*-'
- - '####'
  - 生成密钥的函数，默认长度为 1024
- - '####'
  - 为爱丽丝和鲍勃生成密钥
- - '####'
  - 打印爱丽丝和鲍勃的公钥。此密钥可以共享
- - '####'
  - 爱丽丝想向鲍勃发送一条秘密消息。为爱丽丝创建一条虚拟消息
- - '####'
  - 生成签名的函数
- - '####'
  - 为秘密消息生成签名
- - '####'
  - 在网络中发送消息之前，使用鲍勃的公钥加密消息...
- - '####'
  - 鲍勃使用自己的私钥解密消息...
- - '####'
  - 鲍勃将使用以下函数，通过爱丽丝的公钥验证她的签名
- - '####'
  - 鲍勃使用解密后的消息和爱丽丝的公钥进行验证
- - '###'
  - ECDSA 算法
- - '####'
  - SECP256k1 是比特币椭圆曲线
- - '####'
  - 获取验证密钥
- - '####'
  - 生成消息的签名
- - '####'
  - 验证签名对于消息是否有效
- - '####'
  - 验证签名对于消息是否有效
- - '###'
  - Diffie-Hellman 密钥交换
- - '##'
  - 对称密码学与非对称密码学
- - '##'
  - 博弈论
- - '###'
  - 博弈论：一个商业场景示例
- - '###'
  - 纳什均衡
- - '####'
  - 囚徒困境
- - '####'
  - 拜占庭将军问题
- - '####'
  - 零和博弈
- - '###'
  - 为何要学习博弈论
- - '##'
  - 计算机科学工程
- - '###'
  - 区块链
- - '###'
  - 默克尔树
- - '####'
  - 区块链数据结构与默克尔树的结合
- - '###'
  - 默克尔树的示例代码片段
- - '####'
  - '-*- coding: utf-8 -*-'
- - '####'
  - Given a list of transactions, we concatinate the hashes in groups of two and compute
- - '####'
  - the hash of the group, then keep the hash of group. We repeat this step till
- - '####'
  - we reach a single hash
- - '####'
  - When the sub_tree has only one hash then we reached our merkel tree hash.
- - '##'
  - 综合应用
- - '###'
  - 区块链解决方案的属性
- - '####'
  - 不可变性
- - '####'
  - 防伪造
- - '####'
  - 民主性
- - '####'
  - 防双花
- - '####'
  - 账本状态一致性
- - '####'
  - 弹性
- - '####'
  - 可审计性
- - '###'
  - 区块链交易
- - '###'
  - 分布式共识机制
- - '###'
  - 工作量证明（Proof of Work）
- - '###'
  - 权益证明（Proof of Stake）
- - '###'
  - PBFT
- - '##'
  - 区块链应用
- - '###'
  - 扩展区块链
- - '####'
  - 链下计算
- - '####'
  - 区块链状态分片
- - '##'
  - 本章小结
- - '#'
  - 3. 比特币如何运作
- - '##'
  - 货币的历史
- - '##'
  - 比特币的诞生
- - '###'
  - 什么是比特币？
- - '###'
  - 使用比特币
- - '##'
  - 比特币区块链
- - '###'
  - 区块结构
- - '###'
  - 默克尔树
- - '###'
  - 难度目标
- - '###'
  - 创世区块
- - '##'
  - 比特币网络
- - '###'
  - 新节点的网络发现
- - '####'
  - 第一步：
- - '####'
  - 第二步：
- - '####'
  - 第三步：
- - '####'
  - 第四步：
- - '####'
  - 第五步：
- - '###'
  - 比特币交易
- - '###'
  - 共识与区块挖矿
- - '####'
  - 理解比特币挖矿中的工作量证明
- - '#####'
  - 第一步
- - '#####'
  - 第二步
- - '#####'
  - 第三步
- - '#####'
  - 第四步
- - '###'
  - 区块传播
- - '###'
  - 综合应用
- - '##'
  - 比特币脚本
- - '###'
  - 重新审视比特币交易
- - '###'
  - 脚本
- - '##'
  - 全节点与简易支付验证（SPV）
- - '###'
  - 全节点
- - '###'
  - SPV（简易支付验证）
- - '##'
  - 比特币钱包
- - '##'
  - 摘要
- - '#'
  - 4. 以太坊的工作原理
- - '##'
  - 从比特币到以太坊
- - '###'
  - '以太坊：下一代区块链  '
- - '###'
  - '以太坊的设计理念  '
- - '##'
  - '进入以太坊区块链  '
- - '###'
  - 以太坊区块链
- - '####'
  - 第 1 节：区块元数据
- - '####'
  - 第 2 节：数据引用
- - '####'
  - 第 3 节：交易执行信息
- - '####'
  - 第 4 节：共识子系统信息
- - '###'
  - 以太坊账户
- - '####'
  - UTXOs 的优势
- - '####'
  - 账户的优势
- - '####'
  - 账户状态
- - '####'
  - 'Trie 的使用  '
- - '####'
  - '默克尔帕特里夏树  '
- - '####'
  - RLP 编码
- - '####'
  - 以太坊交易与消息结构
- - '####'
  - 以太坊状态转换函数
- - '####'
  - Gas 与交易成本
- - '###'
  - 以太坊智能合约
- - '####'
  - 合约创建
- - '###'
  - 以太坊虚拟机与代码执行
- - '##'
  - 以太坊生态
- - '###'
  - Swarm
- - '###'
  - Whisper
- - '###'
  - DApp
- - '###'
  - 开发组件
- - '####'
  - Web3.js
- - '####'
  - Truffle
- - '####'
  - Mist 钱包
- - '##'
  - 总结
- - '#'
  - 5. 区块链应用开发
- - '##'
  - 去中心化应用
- - '##'
  - 区块链应用开发
- - '###'
  - 库和工具
- - '###'
  - 与比特币区块链交互
- - '####'
  - 在 node.js 应用中设置并初始化 bitcoinjs 库
- - '####'
  - 为发送方和接收方创建密钥对
- - '####'
  - 在发送方的钱包中获取测试比特币
- - '####'
  - 获取发送方的未花费输出
- - '####'
  - 准备比特币交易
- - '####'
  - 签署交易输入
- - '####'
  - 创建交易十六进制字符串
- - '####'
  - 将交易广播到网络
- - '###'
  - 以编程方式与以太坊交互——发送交易
- - '####'
  - 设置库和连接
- - '####'
  - 设置以太坊账户
- - '####'
  - 在发送方账户中获取测试以太币
- - '####'
  - 准备以太坊交易
- - '####'
  - 签名交易
- - '####'
  - 将交易发送至以太坊网络
- - '###'
  - 以编程方式与以太坊交互——创建智能合约
- - '####'
  - 先决条件
- - '####'
  - 编写智能合约
- - '####'
  - 编译合约并获取详细信息
- - '####'
  - 在以太坊网络上部署合约
- - '###'
  - 以编程方式与以太坊交互——执行智能合约函数
- - '####'
  - 获取智能合约的引用
- - '####'
  - 执行智能合约函数
- - '####'
  - 重要提示
- - '##'
  - 重新审视区块链概念
- - '##'
  - 公有链与私有链
- - '##'
  - 去中心化应用架构
- - '###'
  - 公共节点 vs. 自托管节点
- - '###'
  - 去中心化应用与服务器
- - '##'
  - 本章小结
- - '#'
  - 6. 构建一个以太坊 DApp
- - '##'
  - DApp 去中心化应用
- - '##'
  - 搭建私有以太坊网络
- - '###'
  - 安装 go-ethereum（geth）
- - '###'
  - 创建 geth 数据目录
- - '###'
  - 创建一个 geth 账户
- - '###'
  - 创建 genesis.json 配置文件
- - '####'
  - 运行私有网络的第一个节点
- - '####'
  - 运行网络中的第二个节点
- - '##'
  - 创建智能合约
- - '###'
  - 部署智能合约
- - '####'
  - 设置 web3 库和连接
- - '####'
  - 将合约部署到私有网络
- - '##'
  - 客户端应用
- - '##'
  - 总结
