name: BLOCKCHAIN ENABLED APPLICATIONS
name_cn: 区块链应用构建指南
slug: blockchain-enabled-applications
toc:
- - '##'
  - 目录
- - '#'
  - 引言
- - '#'
  - 当下
- - '#'
  - 致谢
- - '#'
  - 关于作者
- - '#'
  - 关于技术审校者
- - '#'
  - 1. 见证梦想家
- - '##'
  - 范式转移
- - '##'
  - 技术栈
- - '##'
  - 小结
- - '#'
  - 2. 淘金热：挖掘比特币
- - '##'
  - 达成共识
- - '##'
  - 挖矿硬件
- - '##'
  - 创业故事
- - '##'
  - 新的共识
- - '##'
  - 总结
- - '#'
  - 3. 区块链的基础
- - '##'
  - 交易工作流程
- - '###'
  - 生存证明
- - '###'
  - 交易列表的组成部分
- - '###'
  - 比特币交易与钱包机制
- - '##'
  - 简单支付验证（SPV）
- - '##'
  - 区块链分叉
- - '###'
  - 总结
- - '#'
  - 4. 解析以太坊
- - '##'
  - 以太坊概览
- - '###'
  - 核心理念
- - '##'
  - 以太坊中的账户
- - '###'
  - 状态、存储与燃料
- - '###'
  - 以太坊虚拟机
- - '###'
  - Solidity 与 Vyper 编程语言
- - '##'
  - 开发者资源
- - '###'
  - 世界计算机模型
- - '###'
  - 第 2 层升级
- - '####'
  - 分片
- - '####'
  - 信标链
- - '#####'
  - 管理验证者
- - '#####'
  - 区块提议者
- - '#####'
  - 委员会
- - '#####'
  - 奖励与惩罚
- - '###'
  - 状态通道
- - '###'
  - Plasma
- - '##'
  - 区块链即服务
- - '##'
  - 去中心化应用
- - '###'
  - Geth 与 Mist
- - '###'
  - 总结
- - '#'
  - 5. 去中心化组织
- - '##'
  - Aragon 技术栈与 Aragon 网络代币（ANT）
- - '###'
  - Aragon 的社会公益：筹款应用
- - '##'
  - 身份管理用例
- - '##'
  - DAO / 公司操作指南
- - '###'
  - 主题 1：设置 DAO 环境
- - '####'
  - 钱包视图与 MetaMask 设置
- - '###'
  - 主题 2：设置 DAO
- - '###'
  - 主题 3：DAO 应用和权限
- - '####'
  - 代币应用
- - '####'
  - 投票应用
- - '####'
  - 财务应用
- - '####'
  - 应用权限
- - '###'
  - 优先股（B 类）
- - '###'
  - 创始人股（F 类）
- - '##'
  - 总结
- - '#'
  - 6. DAO 遭黑客攻击
- - '##'
  - 引言
- - '##'
  - 团队
- - '###'
  - The DAO
- - '###'
  - ICO 亮点
- - '##'
  - 黑客攻击
- - '##'
  - 争论
- - '##'
  - 分裂：以太坊（ETH）与以太经典（ETC）
- - '##'
  - 未来
- - '##'
  - 总结
- - '#'
  - 7. 高性能计算
- - '##'
  - 代币与价值创造
- - '###'
  - Token 与以太坊计算市场（ECM）
- - '###'
  - 以太坊计算市场（ECM）
- - '##'
  - Golem 网络
- - '###'
  - 应用程序注册表
- - '###'
  - 交易框架
- - '###'
  - SONM（由网络挖矿组织的超级计算机）
- - '####'
  - 买家–中心–矿工交互
- - '####'
  - 超级全局网络操作系统（SOSNA）
- - '###'
  - iEx.ec
- - '###'
  - 总结
- - '#'
  - 8. 科学中的区块链
- - '##'
  - 可重复性危机
- - '###'
  - 数据发现索引
- - '###'
  - 可重复性项目
- - '##'
  - 临床试验
- - '###'
  - 试验注册
- - '###'
  - 药物疗效比较
- - '###'
  - 后期处理
- - '###'
  - 彩色币与规则引擎
- - '##'
  - 信誉系统
- - '###'
  - 药品追踪
- - '###'
  - 摘要
- - '#'
  - 9. 区块链在医疗健康领域的应用
- - '##'
  - 展望
- - '##'
  - 支付方–提供方–患者模型
- - '###'
  - 患者工作流程
- - '##'
  - 热切换
- - '###'
  - 医师资质认证
- - '###'
  - 浪费管理：Capital One、Ark Invest、Gem 的视角
- - '##'
  - 可验证数据审计
- - '###'
  - 面向 DeepMind 健康的可验证数据审计
- - '####'
  - 前方的技术挑战
- - '####'
  - 开放式构建
- - '##'
  - 总结
- - '#'
  - 10. 精益区块链
- - '##'
  - 精益方法论
- - '##'
  - 识别并构建适当的 MVP
- - '###'
  - 在农场进行客户探索
- - '###'
  - 精益不是工程流程
- - '##'
  - 聚焦核心目标
- - '##'
  - 说明
- - '##'
  - 商业模式画布
- - '###'
  - 你需要区块链吗？
- - '###'
  - Hyperledger 项目
- - '####'
  - Hyperledger Fabric
- - '####'
  - Hyperledger Burrow
- - '####'
  - Hyperledger Indy
- - '####'
  - Hyperledger Sawtooth
- - '####'
  - Hyperledger Grid
- - '####'
  - Hyperledger Iroha
- - '####'
  - Hyperledger Besu
- - '###'
  - 使用 Hyperledger Composer 进行快速原型设计
- - '##'
  - 总结
- - '#'
  - 11. 区块链 3.0
- - '##'
  - EOS 区块链
- - '###'
  - 委托权益证明（DPoS）
- - '###'
  - 并行执行
- - '###'
  - 调度
- - '##'
  - 链核心（Chain Core）
- - '##'
  - 配置 Chain Core
- - '###'
  - Chain 控制面板上的导航菜单布局
- - '###'
  - 创建一个新的 HSM 密钥
- - '##'
  - 创建资产
- - '###'
  - 创建一个新资产
- - '####'
  - 资产创建与签名
- - '###'
  - 签署一个资产
- - '##'
  - 发行资产和创建账户
- - '##'
  - 企业以太坊
- - '###'
  - Quorum 技术栈
- - '##'
  - zk-SNARKs
- - '##'
  - Review of Quorum Whitepaper
- - '###'
  - 企业以太坊联盟路线图
- - '##'
  - R3 与 Corda
- - '##'
  - 总结
- - '#'
  - 12. 技术革命与金融资本市场
- - '##'
  - 区块链行业现状
- - '###'
  - 区块链解决方案
- - '##'
  - 风险投资与 ICO
- - '###'
  - 首次代币发行
- - '###'
  - 数字货币交易所
- - '###'
  - ICO 监管现状
- - '###'
  - ICO 投资的利弊
- - '###'
  - 关于替代币的风险与监管技术
- - '###'
  - 监管技术：RegChain
- - '##'
  - 新的区块链公司与理念
- - '###'
  - Homechain 与 SALT
- - '###'
  - Ambrosus、Numerai 与 SWARM
- - '###'
  - Stellar
- - '###'
  - 投资机会民主化
- - '###'
  - 2020 年监管动态
- - '###'
  - 去中心化金融（DeFi）
- - '##'
  - 总结
- - '#'
  - 13. 构建医疗健康联盟
- - '##'
  - 区块链在医疗健康领域的未来：对话与洞察
- - '###'
  - 约翰的访谈
- - '##'
  - 区块链即服务
- - '###'
  - 服务提供商
- - '####'
  - Microsoft Azure
- - '#####'
  - Azure Blockchain Service
- - '#####'
  - Azure Blockchain Workbench
- - '#####'
  - Azure 区块链开发工具包
- - '#####'
  - Amazon Web Services
- - '######'
  - 易于设置（取自 Amazon Managed Blockchain 文档）
- - '######'
  - 安全性（取自 Amazon Managed Blockchain 文档）
- - '######'
  - 不可变排序服务（取自 Amazon Managed Blockchain 文档）
- - '#####'
  - Oracle
- - '######'
  - 维护（取自 Oracle 支持文档）
- - '######'
  - 身份（取自 Oracle 支持文档）
- - '######'
  - 备份（摘自 Oracle 支持文档）
- - '#####'
  - Kaleido
- - '######'
  - 网络治理（摘自 Kaleido BaaS 博客）
- - '######'
  - 高可用性与灾难恢复（摘自 Kaleido BaaS 博客）
- - '##'
  - 总结
- - '#'
  - 15. 区块链联盟的兴起
- - '#'
  - 16. 全新可能的艺术：用新兴技术与联邦学习变革医疗
- - '##'
  - 引言
- - '###'
  - 区块链与代币化
- - '###'
  - 去中心化人工智能（AI）
- - '###'
  - 深度隐私
- - '####'
  - 源健康数据与衍生健康数据
- - '###'
  - 联邦学习
- - '##'
  - 结论
- - '#'
  - 17. 区块链的正式研究与教育
- - '#'
  - 18. 区块链模拟
- - '##'
  - 范围
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y
- - '##'
  - Z
