name: Blockchain for Teens
name_cn: 青少年的区块链指南
slug: blockchain-for-teens
toc:
- - '#'
  - 引言
- - '#'
  - 排版后的内容
- - '##'
  - 致谢
- - '##'
  - 关于作者 | 关于技术审稿人
- - '#'
  - 第 1 章 区块链：一项颠覆性技术
- - '##'
  - 什么是区块链？
- - '##'
  - 区块链的工作原理
- - '###'
  - 区块头
- - '####'
  - 为什么需要梅克尔根哈希？
- - '###'
  - 区块体
- - '####'
  - 交易计数器
- - '##'
  - 交易
- - '##'
  - 共识算法
- - '###'
  - 工作量证明 (PoW)
- - '####'
  - 能源消耗
- - '###'
  - 51% 问题
- - '###'
  - 权益证明（PoS）
- - '##'
  - 货币体系的演变
- - '###'
  - 物物交换系统
- - '###'
  - 商品货币
- - '####'
  - 金属硬币
- - '###'
  - 纸币
- - '###'
  - 塑料货币
- - '###'
  - 移动支付
- - '####'
  - 移动支付类型
- - '##'
  - 理解加密货币
- - '###'
  - 加密货币市场
- - '###'
  - 什么是加密货币波动性？
- - '###'
  - 是什么导致了加密货币市场的高波动性？
- - '###'
  - 新兴市场
- - '###'
  - 新技术
- - '###'
  - 去中心化
- - '###'
  - 市场情绪
- - '###'
  - 代币与币的区别
- - '##'
  - 总结
- - '#'
  - 第 2 章 密码学：区块链安全的基石
- - '##'
  - 密码学基础
- - '###'
  - 对称密钥密码学
- - '####'
  - 流密码
- - '####'
  - 分组密码
- - '##'
  - 非对称密钥密码学
- - '###'
  - 公钥和私钥
- - '####'
  - Diffie-Hellman 算法的工作原理
- - '##'
  - 数字签名的工作原理
- - '###'
  - 数字签名
- - '###'
  - 哈希算法
- - '####'
  - Keccak-256 算法
- - '###'
  - 椭圆曲线密码学（ECC）
- - '####'
  - 什么是椭圆曲线？
- - '####'
  - 推导以太坊地址
- - '###'
  - 本章小结
- - '#'
  - 第 3 章 比特币：未来的货币
- - '##'
  - 比特币历史
- - '###'
  - 早期尝试
- - '###'
  - 2008 年金融危机
- - '###'
  - 比特币的诞生
- - '###'
  - 早期发展
- - '####'
  - 走向主流
- - '###'
  - 区块大小之争
- - '####'
  - Bitcoin XT（2015 年 8 月）
- - '####'
  - 闪电网络白皮书（2016 年 1 月）
- - '####'
  - Bitcoin Classic（2016 年 1 月）
- - '####'
  - 香港共识 – SegWit 提案（2016 年 2 月）
- - '####'
  - 纽约共识（NYA）（2017 年 5 月）
- - '####'
  - SegWit 激活（2017 年 8 月）
- - '##'
  - 比特币扩展性方案
- - '###'
  - 比特币 SegWit 采用率
- - '###'
  - 作为主流货币被接纳
- - '###'
  - BIP342
- - '###'
  - 比特币 ETF（2021 年 10 月–2022 年 7 月）
- - '##'
  - 了解比特币
- - '###'
  - 比特币单位
- - '###'
  - 比特币减半
- - '###'
  - 比特币钱包
- - '####'
  - 比特币钱包的工作原理
- - '####'
  - 比特币钱包的类型
- - '#####'
  - 网络钱包
- - '#####'
  - 桌面钱包
- - '#####'
  - 移动钱包
- - '#####'
  - 硬件钱包
- - '#####'
  - 纸钱包
- - '##'
  - 比特币网络
- - '###'
  - 全节点
- - '###'
  - 轻节点或 SPV
- - '####'
  - 挖矿节点
- - '##'
  - 交易
- - '###'
  - 交易数据结构
- - '####'
  - 输入
- - '####'
  - 输出
- - '###'
  - UTXO（未花费交易输出）
- - '####'
  - 一个输入 – 两个输出
- - '####'
  - 一个输入 – 多个输出
- - '####'
  - 多个输入 – 一个或两个输出
- - '###'
  - 交易池
- - '###'
  - 交易手续费
- - '###'
  - 闪电网络
- - '####'
  - 闪电网络的工作原理
- - '##'
  - 总结
- - '#'
  - 第 4 章 以太坊：通往加密货币的门户
- - '##'
  - 以太坊的历史
- - '###'
  - 白皮书发布（2013 年 11 月）
- - '###'
  - 黄皮书发布（2014 年 4 月）
- - '###'
  - 以太坊的诞生（2014 年 7 月）
- - '###'
  - 启动以太币销售（2014 年 7 月至 9 月）
- - '###'
  - 以太坊发布（2015 年 6 月）
- - '###'
  - DAO 攻击（2016 年 7 月）
- - '###'
  - 以太坊 2.0（合并）
- - '####'
  - 阶段 0 – 信标链
- - '####'
  - 阶段 1 – 合并
- - '####'
  - 阶段 2 – 分片链
- - '##'
  - 了解以太坊
- - '###'
  - 以太币（单位）
- - '###'
  - Gas、Gas 价格与 Gas 限额
- - '###'
  - 以太坊账户
- - '####'
  - 外部拥有账户（EOA）
- - '####'
  - 合约账户（CA）
- - '###'
  - 智能合约
- - '###'
  - 以太坊虚拟机（EVM）
- - '####'
  - 日志、调用及其他操作码（LOG0、LOG1、LOG2 等）
- - '##'
  - 以太坊节点
- - '###'
  - 全节点
- - '###'
  - 归档节点
- - '###'
  - 轻节点
- - '###'
  - 以太坊客户端
- - '####'
  - Geth 控制台
- - '####'
  - 通过命令行使用 Geth JSON-RPC
- - '####'
  - Geth 文件夹结构
- - '###'
  - 以太坊网络
- - '##'
  - 以太坊的工作原理
- - '###'
  - 交易的结构
- - '###'
  - 交易收据
- - '###'
  - Block
- - '##'
  - 总结
- - '#'
  - 第 5 章 智能合约与去中心化应用：从理论到实践
- - '##'
  - 介绍 Remix
- - '###'
  - 文件浏览器
- - '###'
  - Solidity 编译器
- - '###'
  - 部署与运行交易
- - '###'
  - 其他模块
- - '##'
  - 编写你的第一个智能合约
- - '###'
  - 编写合约
- - '####'
  - 软件许可证
- - '####'
  - 编译器指令 (Pragmas)
- - '####'
  - 定义合约
- - '####'
  - 声明合约变量
- - '####'
  - 定义合约构造函数
- - '####'
  - 定义函数
- - '#####'
  - 语法
- - '#####'
  - 函数可见性
- - '#####'
  - 函数行为
- - '###'
  - 编译合约
- - '###'
  - 部署并运行合约
- - '##'
  - 掌控你的第一个以太坊钱包
- - '##'
  - 去中心化应用（Dapps）
- - '###'
  - 开始
- - '####'
  - 安装 node.js
- - '####'
  - 安装 Git
- - '####'
  - Git 克隆 HelloWorld Dapp 项目
- - '####'
  - 安装 HelloWorld Dapp 项目
- - '####'
  - 运行 HelloWorld Dapp 项目
- - '####'
  - 从浏览器打开 HelloWorld Dapp
- - '###'
  - 连接到 Metamask
- - '####'
  - 获取合约并调用获取消息
- - '#####'
  - 获取合约并调用更新消息
- - '##'
  - 代币标准
- - '###'
  - ERC-20
- - '###'
  - ERC-721
- - '##'
  - 总结
- - '#'
  - 第 6 章 NFT：作为收藏品的加密资产
- - '##'
  - 什么是 NFT？
- - '##'
  - 同质化 vs. 非同质化
- - '###'
  - NFT 简史
- - '##'
  - NFT 的应用
- - '###'
  - 图像
- - '###'
  - 视频
- - '###'
  - GIF
- - '###'
  - 音频
- - '###'
  - 数字地产
- - '###'
  - 交易卡
- - '###'
  - 电子游戏物品
- - '###'
  - 时尚
- - '###'
  - 3D 模型
- - '###'
  - 文本
- - '###'
  - 域名
- - '###'
  - NFT 的示例
- - '##'
  - NFT 的卖点
- - '###'
  - 稀缺性
- - '###'
  - 真实性
- - '###'
  - 易于与加密货币一起使用
- - '###'
  - 所有权
- - '###'
  - 永久性
- - '###'
  - 效率
- - '###'
  - 版税
- - '###'
  - 制造成本低廉
- - '##'
  - 创建你自己的 NFT
- - '##'
  - NFT 市场
- - '###'
  - OpenSea.io
- - '###'
  - Rarible
- - '###'
  - SuperRare
- - '###'
  - Foundation
- - '###'
  - Nifty Gateway
- - '###'
  - Axie Marketplace
- - '###'
  - NBA Top Shot Marketplace
- - '###'
  - Mintable
- - '###'
  - Larva Labs/CryptoPunks
- - '##'
  - NFT 的未来
- - '##'
  - 总结
- - '#'
  - 第 7 章 元宇宙：重塑的世界
- - '##'
  - 元宇宙简介
- - '###'
  - 什么是元宇宙？
- - '###'
  - 元宇宙简史
- - '###'
  - 元宇宙的特征
- - '####'
  - 互操作性
- - '####'
  - 去中心化
- - '####'
  - 沉浸式
- - '####'
  - 无边界
- - '####'
  - 虚拟经济
- - '####'
  - 持久性
- - '####'
  - 社交体验
- - '##'
  - AR、VR、MR 与 XR
- - '###'
  - 增强现实（AR）
- - '####'
  - 什么是增强现实？
- - '####'
  - AR 的类型
- - '#####'
  - 基于标记的 AR
- - '#####'
  - 无标记 AR
- - '#####'
  - 基于投影的 AR
- - '#####'
  - 基于位置的 AR
- - '#####'
  - 基于叠加的 AR
- - '###'
  - 增强现实的工作原理
- - '###'
  - 虚拟现实 (VR)
- - '####'
  - 什么是虚拟现实？
- - '####'
  - VR 的类型
- - '#####'
  - 非沉浸式 VR
- - '#####'
  - 半沉浸式 VR
- - '#####'
  - 完全沉浸式 VR
- - '####'
  - 虚拟现实如何工作
- - '#####'
  - 视场角 (FOV)
- - '#####'
  - 帧率 (FPS)
- - '#####'
  - 位置与头部追踪
- - '#####'
  - 空间音频与音效
- - '###'
  - 混合现实（MR）
- - '###'
  - 扩展现实（XR）
- - '##'
  - 理解元宇宙的层级
- - '###'
  - 体验
- - '###'
  - 发现
- - '###'
  - 创作者经济
- - '###'
  - 空间计算
- - '###'
  - 去中心化
- - '###'
  - 人机界面
- - '###'
  - 基础设施
- - '##'
  - 元宇宙中的加密 NFT 游戏
- - '###'
  - 游戏行业的商业模式
- - '####'
  - 付费游玩模式
- - '####'
  - 免费游玩模式
- - '####'
  - 边玩边赚模式
- - '#####'
  - 赚取或交易游戏内 NFT
- - '#####'
  - 赚取游戏内加密货币
- - '#####'
  - 质押（Staking）
- - '###'
  - “边玩边赚” NFT 游戏示例
- - '####'
  - The Sandbox
- - '#####'
  - VoxEdit
- - '#####'
  - Game Maker
- - '#####'
  - Marketplace
- - '#####'
  - SAND
- - '#####'
  - LAND
- - '#####'
  - ASSET
- - '#####'
  - GAME
- - '#####'
  - CATALYSTs
- - '#####'
  - GEMs
- - '####'
  - Decentraland
- - '##'
  - 元宇宙中的虚拟房地产
- - '###'
  - 什么是虚拟土地？
- - '###'
  - Decentraland（案例研究）
- - '####'
  - Decentraland 中的三种原生代币
- - '###'
  - Decentraland 架构
- - '####'
  - 共识层
- - '####'
  - 土地内容层
- - '####'
  - 实时层
- - '###'
  - 在元宇宙中购买土地
- - '####'
  - 第一步 – 选择元宇宙平台并登录
- - '####'
  - 第二步 – 购买加密货币
- - '####'
  - 第三步 – 选择一块 LAND
- - '####'
  - 第四步 – 购买房产
- - '##'
  - 元宇宙的未来
- - '###'
  - 元宇宙第一阶段：兴起（2021–2030）
- - '###'
  - 元宇宙发展阶段二：进阶期（2030–2050 年）
- - '###'
  - 元宇宙发展阶段三：成熟期（2050 年后）
- - '##'
  - 本章小结
- - '#'
  - 第 8 章 去中心化金融（DeFi）：重塑金融服务
- - '##'
  - 什么是去中心化金融 (DeFi)？
- - '##'
  - DeFi 的结构
- - '###'
  - 第一层：结算层
- - '###'
  - 第二层：资产层
- - '###'
  - 第三层：协议层
- - '###'
  - 第四层：应用层
- - '###'
  - 第五层：聚合层
- - '##'
  - 去中心化稳定币
- - '###'
  - 稳定币历史
- - '###'
  - 稳定币的类型
- - '####'
  - 商品抵押稳定币
- - '####'
  - 法定货币抵押稳定币
- - '####'
  - 加密货币抵押稳定币
- - '####'
  - 非抵押型稳定币
- - '###'
  - 深入解析稳定币——Maker（DAI）
- - '####'
  - DAI 的工作原理
- - '####'
  - Maker（MKR）币的供应
- - '####'
  - MakerDAO 的治理
- - '####'
  - 治理民意调查
- - '###'
  - 执行投票
- - '###'
  - 对提案进行投票
- - '####'
  - 步骤 1：获取你的 MKR 代币
- - '####'
  - 步骤 2：使用钱包连接到以太坊主网
- - '####'
  - 步骤 3：选择一项进行中的投票
- - '####'
  - 步骤 4：审核并提交你的投票
- - '####'
  - 步骤 5：投票完成
- - '##'
  - 去中心化交易所 (DEXs)
- - '###'
  - 去中心化交易所的类型
- - '###'
  - 自动做市商 (AMMs)
- - '###'
  - AMM 基本概念
- - '####'
  - 现有 AMM 模型有哪些？
- - '####'
  - 恒定乘积做市商（CPMM）
- - '####'
  - 恒定总和做市商（CSMM）
- - '####'
  - 恒定均值做市商（CMMM）
- - '####'
  - 混合恒定函数
- - '####'
  - AMM 的局限性
- - '####'
  - 滑点
- - '####'
  - 无常损失（IL）
- - '###'
  - 订单簿去中心化交易所
- - '####'
  - 链上订单簿
- - '####'
  - 链下订单簿
- - '###'
  - 去中心化交易所聚合器
- - '###'
  - 深入剖析 AMM DEX——Uniswap
- - '####'
  - 在 Uniswap DEX 上列出你自己的代币
- - '####'
  - 前置条件
- - '###'
  - 创建 ERC-20 代币
- - '###'
  - 在 Uniswap 中创建新的流动性池
- - '###'
  - 增加流动性池的资金
- - '###'
  - 在 Uniswap 中兑换代币
- - '###'
  - 从流动性池领取奖励
- - '##'
  - 去中心化借贷
- - '###'
  - DeFi 借贷平台概览——Aave
- - '####'
  - Aave 代币
- - '#####'
  - AAVE
- - '#####'
  - aToken
- - '###'
  - 如何在 Aave 上存款
- - '###'
  - 如何在 Aave 上提取
- - '###'
  - 如何在 Aave 上进行兑换
- - '###'
  - 如何在 Aave 上进行借款
- - '###'
  - 如何在 Aave 上进行还款
- - '##'
  - 去中心化保险
- - '###'
  - 热门 DeFi 保险平台
- - '####'
  - Nexus Mutual
- - '####'
  - InsurAce 协议
- - '####'
  - Etherisc
- - '##'
  - 总结
- - '#'
  - 第 9 章 区块链的未来
- - '##'
  - 互联网的演进
- - '###'
  - Web 1.0 (1989–2004)——万维网
- - '###'
  - Web 2.0（2004 年至今）——参与式社交网络
- - '###'
  - Web 3.0——去中心化
- - '##'
  - 金融领域的区块链
- - '###'
  - 贸易融资中的信用证
- - '###'
  - 供应链中的区块链
- - '####'
  - 文档管理
- - '####'
  - 各类集中式 IT 软件系统的集成
- - '####'
  - 数据缺乏透明度
- - '###'
  - 食品供应链行业中的区块链
- - '####'
  - 大眼金枪鱼海鲜公司
- - '####'
  - 保持肉类冷藏：金州食品公司
- - '###'
  - 供应链行业的其他领域
- - '####'
  - Brilliant Earth——区块链赋能钻石
- - '####'
  - 梅赛德斯-奔驰——Acentrik 区块链平台
- - '##'
  - 医疗保健领域的区块链
- - '###'
  - 健康数据准确性
- - '###'
  - 健康数据互操作性
- - '###'
  - 保险理赔
- - '####'
  - Avaneer 网络
- - '####'
  - ClaimShare
- - '###'
  - 健康数据管理
- - '####'
  - Patientory
- - '###'
  - 疾病预防
- - '####'
  - GemOS
- - '##'
  - 总结
- - '#'
  - 索引
