name: The Web3 Revolution
name_cn: Web3 革命
slug: the-web3-revolution
toc:
- - '##'
  - 目录
- - '##'
  - 引言
- - '##'
  - 致谢
- - '##'
  - 关于作者
- - '#'
  - 第一部分：区块链的起源与基础
- - '##'
  - 第1章：解密区块链技术
- - '###'
  - 1.1 什么是区块链？
- - '####'
  - 区块链 vs. 互联网
- - '####'
  - 区块链与人工智能
- - '###'
  - 1.2 区块链如何运作：哈希函数、加密与数字签名
- - '####'
  - 哈希函数
- - '####'
  - 加密
- - '####'
  - 数字签名
- - '####'
  - 案例分析：使用 Python 创建比特币地址
- - '###'
  - 共识算法
- - '###'
  - 总结
- - '###'
  - 注释
- - '##'
  - 第2章：比特币：数字货币的先驱
- - '###'
  - 2.1 比特币的诞生
- - '####'
  - 中本聪与白皮书
- - '####'
  - 创世区块与第一笔比特币交易
- - '####'
  - 哈尔·芬尼的传奇故事及其对比特币的影响
- - '####'
  - 比特币的遗产
- - '####'
  - 比特币技术概览
- - '###'
  - 2.2 比特币如何运作：挖矿机制
- - '####'
  - 理解比特币挖矿
- - '####'
  - 挖矿过程
- - '####'
  - 挖矿硬件的演变
- - '####'
  - 矿池
- - '###'
  - 2.3 比特币面临的挑战：安全隐患、钱包存储与扩容难题
- - '####'
  - 51%攻击：对比特币完整性的理论性威胁
- - '####'
  - 区块大小之争与比特币分叉：扩容挑战
- - '####'
  - 多样化的钱包类型
- - '###'
  - 2.4 黄金首饰：序数（铭文）
- - '###'
  - 2.5 总结
- - '###'
  - 注释
- - '#'
  - 第二部分：以太坊：智能合约的摇篮
- - '##'
  - 第3章：以太坊的崛起
- - '###'
  - 3.1 以太坊虚拟机
- - '####'
  - 以太坊的图灵完备性
- - '####'
  - 以太坊作为去中心化计算基础设施
- - '####'
  - 以太坊的发展历程
- - '###'
  - 3.2 智能合约入门
- - '###'
  - 3.3 Remix 介绍 – 以太坊集成开发环境
- - '####'
  - 使用 Remix 进行智能合约开发
- - '###'
  - 3.4 简单的智能合约示例
- - '#####'
  - 枚举声明
- - '#####'
  - 状态变量
- - '#####'
  - 构造函数
- - '#####'
  - 状态变更函数
- - '#####'
  - 状态查询函数
- - '###'
  - 3.5 ERC 标准：ERC20、ERC721、ERC1155
- - '####'
  - ERC 标准概述
- - '#####'
  - ERC20 标准
- - '#####'
  - ERC721 标准
- - '####'
  - ERC1155 标准
- - '####'
  - 标准对比
- - '###'
  - 3.6 总结
- - '###'
  - 注释
- - '##'
  - 第4章：Web3 的支柱：以太坊钱包、水龙头和 Layer 2 解决方案
- - '###'
  - 4.1 Web3 的门户：加密钱包
- - '####'
  - EOA 账户与合约账户的明确区分
- - '####'
  - 设置与使用钱包：以 MetaMask 为例
- - '#####'
  - 创建密码后
- - '####'
  - 为钱包充值并与 DApp 交互
- - '#####'
  - 以太坊浏览器：Etherscan
- - '###'
  - 4.2 区块链新手的资源水龙头：Faucets
- - '####'
  - 智能合约示例 – 水龙头
- - '###'
  - 4.3 通过 Layer 2 解决方案拓展视野
- - '###'
  - 4.4 本章小结
- - '###'
  - 注释
- - '#'
  - 第三部分：去中心化金融（DeFi）及其应用
- - '##'
  - 第5章：去中心化金融（DeFi）的崛起
- - '###'
  - 5.1 DeFi 的核心概念与应用
- - '####'
  - DeFi 与传统金融
- - '####'
  - 去中心化交易所 (DEXs)
- - '####'
  - 借贷平台
- - '####'
  - 稳定币
- - '####'
  - 保险
- - '####'
  - 预测市场/预言机
- - '###'
  - 5.2 主流 DeFi 协议分析
- - '####'
  - Uniswap
- - '####'
  - Aave
- - '####'
  - MakerDAO
- - '####'
  - 总锁仓价值（TVL）
- - '###'
  - 5.3 DeFi 的风险与挑战
- - '####'
  - 安全风险
- - '####'
  - 监管挑战
- - '####'
  - 可扩展性与互操作性
- - '####'
  - 市场风险与波动性
- - '###'
  - 5.4 本章小结
- - '###'
  - 注释
- - '##'
  - 第6章：代币化的现实世界资产（RWA）与去中心化物理基础设施网络（DePIN）
- - '###'
  - 6.1 RWA 简介
- - '####'
  - 区块链作为理想的基础设施
- - '####'
  - RWA 代币化对 TradFi 的颠覆性影响
- - '###'
  - 6.2 DePIN 概述
- - '####'
  - DePIN 的核心组成部分
- - '####'
  - 实际应用案例
- - '####'
  - DePIN 飞轮的动力机制
- - '####'
  - 可扩展性与可持续性
- - '###'
  - 6.3 RWA 与 DePIN 之间的协同效应：机遇与复杂性
- - '####'
  - 去中心化物理基础设施网络（DePIN）项目中 Solana 的优势
- - '####'
  - 挑战与解决方案
- - '###'
  - 6.4 总结
- - '###'
  - 笔记
- - '##'
  - 第7章：非同质化代币（NFT）与数字艺术
- - '###'
  - 7.1 理解 NFT：机制与市场动态
- - '####'
  - 独特属性与底层技术
- - '####'
  - NFT 的应用
- - '####'
  - 发行模式：从标准发售到荷兰式拍卖
- - '####'
  - 应对市场挑战：包容性与完整性
- - '####'
  - 市场动态
- - '###'
  - 7.2 NFT 市场的演变与未来趋势
- - '####'
  - 迈向更公平、透明的分销模式
- - '####'
  - 市场波动与流动性问题
- - '####'
  - 超越数字艺术：NFT 的应用扩展
- - '###'
  - 7.3 创建与交易 NFT：分步指南
- - '####'
  - 第一步：使用 Python 生成随机图像
- - '####'
  - 第二步：将资产上传到存储解决方案
- - '#####'
  - 选项 1：搭建自己的 IPFS 节点
- - '#####'
  - 选项 2：使用第三方服务（如 Pinata）
- - '####'
  - 第三步：创建符合 OpenSea 标准的元数据
- - '####'
  - 第四步：在区块链上铸造 NFT
- - '#####'
  - NFT 管理的智能合约函数
- - '######'
  - 1. 铸造 NFT
- - '######'
  - 2. 设定价格与限制
- - '######'
  - 3. 管理白名单
- - '######'
  - 4. 控制合约行为
- - '######'
  - 5. 调整元数据设置
- - '####'
  - 第五步：在 OpenSea 上架 NFT 进行出售
- - '#####'
  - 上架出售
- - '###'
  - 概述
- - '###'
  - 备注
- - '##'
  - 第8章：DEX 与市值管理
- - '###'
  - 8.1 DEX 的工作原理
- - '####'
  - 运行原理
- - '####'
  - 代币上架与流动性池
- - '####'
  - 去中心化、安全性与治理
- - '###'
  - 8.2 代币市值管理策略
- - '####'
  - 代币销毁
- - '####'
  - 流动性提供
- - '####'
  - 合作伙伴关系与集成
- - '####'
  - 机制与财政政策设计
- - '####'
  - 算法做市
- - '####'
  - 战略分发
- - '####'
  - 货币政策：销毁与铸造平衡
- - '###'
  - 8.3 DEX 的未来发展
- - '####'
  - 与传统金融融合
- - '####'
  - 应对即时流动性攻击和夹心攻击
- - '####'
  - TWAMM 与 CFMM 对比
- - '####'
  - 激励流动性提供者
- - '###'
  - 8.4 总结
- - '###'
  - 注释
- - '#'
  - 第四部分：推进 Web3：融合、创新与监管
- - '##'
  - 第9章：导航 Web3 与元宇宙的未来
- - '###'
  - 9.1 Web3 与元宇宙：基础与技术
- - '####'
  - 元宇宙的核心基础要素
- - '###'
  - 9.2 Web3 与元宇宙中的经济模型与机遇
- - '####'
  - 去中心化经济系统
- - '####'
  - 价值创造与分配
- - '####'
  - 协作工作与创新
- - '####'
  - 代币化与经济激励
- - '###'
  - 9.3 领先平台、项目及其应用
- - '####'
  - Decentraland：用户治理虚拟房地产案例研究
- - '####'
  - 摩根大通进军元宇宙：Onyx Lounge 及其他
- - '###'
  - 9.4 未来方向：挑战与准备
- - '####'
  - 监管与伦理考量
- - '####'
  - 为未来之路做好准备
- - '###'
  - 9.5 本章小结
- - '###'
  - 引用注释
- - '##'
  - 第10章：Web3 中人工智能的融合与演进
- - '###'
  - 10.1 生成式 AI 增强的区块链
- - '###'
  - 10.2 人工智能与 Web3 的协同效应
- - '####'
  - 去中心化金融 (DeFi) 与预测分析
- - '####'
  - 医疗保健：患者数据与个性化医疗
- - '####'
  - 教育：定制化学习体验
- - '#####'
  - 教育与 AI 及 Web3 的融合
- - '####'
  - 治理：透明投票系统
- - '####'
  - 供应链管理
- - '####'
  - 环境可持续性
- - '###'
  - 10.3 从模因到主流：AI 在 Web3 文化与创造力中日益扩大的作用
- - '####'
  - 模因在数字货币社区中的力量
- - '####'
  - 生成式 AI 在模因创作与演变中的作用
- - '####'
  - “Make It More”趋势与 AI 模因的扩展
- - '####'
  - 文化影响与未来方向
- - '###'
  - 10.4 总结
- - '###'
  - 笔记
- - '##'
  - 第11章：Web3 的法律框架
- - '###'
  - 11.1 全球代币定义中的监管分歧与趋同
- - '####'
  - 美国 – 证券交易委员会 (SEC)
- - '####'
  - 英国 – 金融行为监管局 (FCA)
- - '####'
  - 欧盟 – 加密资产市场（MiCA）
- - '####'
  - 瑞士 – 金融市场监督管理局（FINMA）
- - '####'
  - 新加坡 – 新加坡金融管理局 (MAS)
- - '####'
  - 香港 – 金融管理局 (HKMA)
- - '###'
  - 11.2 数字资产的全球监管策略
- - '####'
  - SEC 的监管指南针
- - '####'
  - FCA 的监管蓝图
- - '####'
  - 驾驭跨境监管水域
- - '####'
  - 全球监管的趋同与分歧
- - '####'
  - 未来展望
- - '###'
  - 11.3 数字资产托管与用户保护
- - '####'
  - 数字资产托管的本质
- - '####'
  - 托管与保护的监管方法
- - '####'
  - 监管案例研究
- - '####'
  - 未来之路
- - '###'
  - 11.4 引领未来：Web3 的监管、创新与标准化
- - '####'
  - 比特币 ETF 的出现：连接传统金融与数字金融
- - '#####'
  - 通过受监管工具降低风险
- - '####'
  - 创新前沿
- - '####'
  - 驾驭风险
- - '####'
  - 标准化之路
- - '####'
  - 未来展望
- - '###'
  - 11.5 总结
- - '##'
  - 索引
- - '###'
  - A
- - '###'
  - B
- - '###'
  - C
- - '###'
  - D
- - '###'
  - E
- - '###'
  - F
- - '###'
  - G
- - '###'
  - H
- - '###'
  - I
- - '###'
  - J, K, L
- - '###'
  - M
- - '###'
  - N, O
- - '###'
  - P, Q
- - '###'
  - R
- - '###'
  - S
- - '###'
  - T
- - '###'
  - U, V
- - '###'
  - W, X, Y
- - '###'
  - Z
