name: The Blockchain Developer
name_cn: 区块链开发者
slug: the-blockchain-developer
toc:
- - '#'
  - 关于作者与技术审校
- - '##'
  - 关于作者
- - '##'
  - 关于技术审校
- - '#'
  - 1. 区块链基础
- - '##'
  - 加密经济学入门
- - '###'
  - 注意
- - '###'
  - 倒置偶语
- - '####'
  - 加密/解密
- - '####'
  - 加密 + 解密 = 密码学
- - '###'
  - 注意
- - '###'
  - 数字资产 + 密码学 = 加密货币
- - '###'
  - 注意
- - '###'
  - 密码学 + 经济学 = 加密经济学
- - '###'
  - 注意
- - '##'
  - 区块链解释
- - '###'
  - 区块 + 链 = 区块链
- - '####'
  - 注意
- - '####'
  - 链接的区块
- - '###'
  - 说明
- - '##'
  - 双重支付问题
- - '###'
  - 说明
- - '##'
  - 双重支付解决方案：P2P 网络
- - '###'
  - 说明
- - '##'
  - 加密货币矿工与挖矿
- - '##'
  - 加密货币钱包
- - '##'
  - 纷繁复杂的加密货币
- - '###'
  - 比特币数字现金
- - '###'
  - 代币
- - '####'
  - 说明
- - '###'
  - 替代性加密货币币种（山寨币）
- - '###'
  - 注意
- - '##'
  - 区块链 P2P 网络
- - '###'
  - 共识机制
- - '####'
  - 注意
- - '###'
  - 工作量证明、权益证明和委托权益证明
- - '####'
  - 工作量证明
- - '#####'
  - 注意事项
- - '####'
  - 权益证明（PoS）
- - '#####'
  - 注意
- - '####'
  - 委托权益证明（DPoS）
- - '#####'
  - 注意
- - '###'
  - 挖矿层
- - '###'
  - 传播层
- - '###'
  - 语义层
- - '###'
  - 应用层
- - '##'
  - 总结
- - '#'
  - 2. 区块链节点
- - '##'
  - 运行区块链节点
- - '###'
  - 创建比特币矿工
- - '####'
  - 注意
- - '###'
  - 创建 NEO 记账节点
- - '####'
  - 注意
- - '####'
  - 注意
- - '###'
  - 在 AWS Ubuntu 上设置 NEO 节点
- - '####'
  - 注意
- - '###'
  - 在 Ubuntu 16.04 上安装记账节点部署程序
- - '###'
  - 记账节点部署
- - '###'
  - 申请共识权限证书
- - '###'
  - 获取 GAS
- - '###'
  - 被选为记账人
- - '###'
  - 创建 EOS 区块生产者
- - '###'
  - 安装 EOS 全节点
- - '###'
  - 营销与上架
- - '###'
  - 终止 EOS 节点
- - '##'
  - Bitcoin Core API
- - '###'
  - 安装并配置完整比特币节点
- - '####'
  - prune=3000 - 注释掉此行
- - '###'
  - 序列化区块
- - '###'
  - 区块头
- - '####'
  - 注意
- - '###'
  - 区块版本
- - '####'
  - Merkle 树
- - '###'
  - 目标 nBits
- - '###'
  - txn_count
- - '###'
  - 区块奖励
- - '###'
  - txns：解码交易
- - '##'
  - 比特币钱包
- - '##'
  - 总结
- - '#'
  - 3. 创建你自己的区块链
- - '##'
  - 注意
- - '###'
  - 创建基础 P2P 网络
- - '####'
  - 注意
- - '####'
  - 第一步：基础 P2P 网络练习
- - '##'
  - 创建创世区块与共享区块
- - '###'
  - 步骤 2：P2P 网络发送区块练习
- - '##'
  - 注册矿工并创建新区块
- - '###'
  - 步骤 3：注册矿工并创建新区块练习
- - '##'
  - 在 LevelDB 中存储区块
- - '####'
  - 注意
- - '###'
  - 第四步：使用 LevelDB 存储区块链的练习
- - '##'
  - 创建区块链钱包
- - '###'
  - 第 5 步：钱包练习
- - '##'
  - 创建一个 API
- - '###'
  - 第 6 步：API P2P 区块链练习
- - '##'
  - 创建命令行界面
- - '###'
  - 第 7 步：CLI 练习
- - '##'
  - 后续方向
- - '##'
  - 总结
- - '#'
  - 4. 比特币钱包与交易
- - '##'
  - Bitcoin Core RPC 资源
- - '###'
  - 注意
- - '##'
  - Bitcoin 钱包
- - '###'
  - 创建传统钱包地址并检索私钥
- - '####'
  - 注意
- - '####'
  - 注意
- - '###'
  - 支付到见证公钥哈希（P2WPKH）：SegWit 软分叉
- - '####'
  - 注意
- - '###'
  - 椭圆曲线数字签名算法
- - '####'
  - 注意
- - '####'
  - 注意
- - '##'
  - 交易
- - '###'
  - 简单命令
- - '####'
  - 注意
- - '####'
  - 注意
- - '###'
  - 测试网
- - '####'
  - 注意
- - '###'
  - 在区块链浏览器上查看交易
- - '####'
  - 注意
- - '###'
  - 通过比特币核心钱包图形界面发送测试网币
- - '###'
  - 原始交易
- - '####'
  - 注意事项
- - '###'
  - 生成单一输出原始交易
- - '####'
  - 注
- - '###'
  - 需要多重签名的交易
- - '###'
  - 使用多重签名钱包设置 Electrum
- - '####'
  - 注意
- - '###'
  - 'extended private masterkey: [key]'
- - '###'
  - 可替换交易与锁定时间
- - '####'
  - 注意
- - '##'
  - 比特币彩色币
- - '###'
  - 注意
- - '###'
  - 发送包含 OP_RETURN 的交易
- - '####'
  - 注意
- - '###'
  - 比特币的彩色币
- - '##'
  - 总结
- - '#'
  - 5. 以太坊钱包与智能合约
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - 注意
- - '###'
  - '`Ganache` 模拟全节点客户端'
- - '####'
  - 安装 `Ganache`
- - '####'
  - '`Ganache` CLI：监听端口'
- - '##'
  - 用于 Solidity 的 `IntelliJ IDEA` 插件
- - '##'
  - '`Truffle` 套件'
- - '###'
  - 创建你的智能合约
- - '###'
  - 将 Truffle 连接至 Ganache 网络
- - '###'
  - “Hello, World”智能合约
- - '###'
  - “MD5SmartContract”智能合约
- - '###'
  - 为智能合约部署创建 Truffle 迁移文件
- - '###'
  - 使用 Truffle 编译智能合约
- - '###'
  - 将智能合约部署到你的开发网络
- - '###'
  - Truffle 控制台
- - '###'
  - 通过 Truffle CLI 与智能合约交互
- - '##'
  - 使用 Remix 编译
- - '###'
  - 注意
- - '##'
  - 使用 Geth 建立私有以太坊区块链
- - '###'
  - 初始化 Geth 私有区块链
- - '###'
  - Geth 控制台
- - '###'
  - 为你的私有测试网挖掘以太币
- - '###'
  - 将 Remix 部署到 Geth
- - '###'
  - 将 Truffle 部署到 Geth
- - '###'
  - Geth 中的常用命令
- - '##'
  - 将 Mist 以太坊钱包连接到你的私有网络
- - '###'
  - 其他人如何与你的智能合约交互
- - '###'
  - 注意
- - '##'
  - MetaMask
- - '##'
  - 公开测试网
- - '###'
  - 同步区块
- - '###'
  - 公开测试网水龙头
- - '##'
  - 以太坊主网
- - '##'
  - 推荐的智能合约工具
- - '##'
  - 总结
- - '#'
  - 6. EOS.IO 钱包与智能合约
- - '###'
  - 注意
- - '##'
  - 搭建测试网络环境
- - '###'
  - 安装 EOS.IO
- - '##'
  - 为 EOSIO 设置 PATH
- - '##'
  - 安装 EOSIO.CDT
- - '###'
  - 注意
- - '##'
  - 构建 EOS.IO
- - '##'
  - keosd 和 nodeos 配置文件
- - '###'
  - http-server-address =
- - '##'
  - 使用 cleos 创建和管理钱包
- - '###'
  - EOS.IO 钱包
- - '##'
  - 删除和备份钱包
- - '##'
  - 自定义名称的 EOS.IO 钱包
- - '##'
  - EOS.IO：打开、锁定和解锁钱包
- - '##'
  - 生成 EOS.IO 密钥
- - '###'
  - 注意
- - '###'
  - 使用 `nodeos` 启动节点
- - '####'
  - 注意
- - '###'
  - 重新启动本地测试网节点（`nodeos`）
- - '###'
  - EOS.IO 账户
- - '####'
  - 注意
- - '###'
  - 钱包、密钥和账户：完整命令
- - '##'
  - 自定义、单签名与多重签名
- - '##'
  - “HelloWorld”智能合约
- - '###'
  - “HelloWorld”智能合约账户
- - '###'
  - “HelloWorld”的 C++ 代码
- - '####'
  - 注意
- - '####'
  - 注意
- - '##'
  - 智能合约 IDE
- - '##'
  - 编译合约并生成 ABI
- - '###'
  - Ricardian 合约
- - '####'
  - 注意
- - '##'
  - 部署合约
- - '###'
  - 与智能合约交互
- - '##'
  - 智能合约代币
- - '###'
  - 创建账户
- - '###'
  - 使用最新 eosio.token 代码编译 wasm
- - '###'
  - 部署 eosio.token
- - '###'
  - 创建 EOS.IO 代币
- - '###'
  - 发行代币
- - '###'
  - 转账代币
- - '##'
  - 连接公共测试网区块生产者
- - '###'
  - Note
- - '###'
  - 在公共测试网区块生产者上购买资源分配
- - '###'
  - 在公共测试网上发布你的 HelloWorld 合约
- - '##'
  - 连接到主网
- - '###'
  - 资源分配详解
- - '###'
  - 在主网上购买 RAM
- - '###'
  - 在主网上创建 EOS.IO 账户
- - '###'
  - 更改账户的公钥和私钥
- - '###'
  - CPU 和带宽分配
- - '##'
  - 下一步
- - '##'
  - 本章小结
- - '#'
  - 7. NEO 区块链与智能合约
- - '###'
  - NEO 的高级区块链架构
- - '###'
  - 什么是 NEO 的智能经济？
- - '####'
  - 注意
- - '##'
  - 设置您的本地环境
- - '###'
  - Xcode 10.2
- - '###'
  - 安装 Visual Studio 2017 IDE
- - '###'
  - 安装 .NET Core
- - '####'
  - 安装 Docker
- - '###'
  - 下载 NeoCompiler 并生成 neon.dll
- - '###'
  - 使用 neo-cli 生成 NEO 节点
- - '####'
  - neo-cli
- - '##'
  - 搭建本地 NEO 私有测试网
- - '###'
  - Python 3.6
- - '###'
  - 安装 `neo-python`
- - '###'
  - 安装 `neo-privatenet-docker`
- - '####'
  - 注意
- - '##'
  - 启动网络并领取初始 NEO 和 Gas
- - '##'
  - 引导测试网
- - '##'
  - 启动 NEO Bash
- - '###'
  - 安装过程中的潜在问题
- - '####'
  - 清理数据库
- - '####'
  - b'Corruption 消息
- - '####'
  - 重启 Docker
- - '###'
  - NEO “Hello, World”
- - '###'
  - 构建 NeoContract 框架：Neo.SmartContract.Framework.dll
- - '###'
  - 创建 NEO “Hello, World” 项目
- - '###'
  - 在 C# 中编写 NEO “Hello, World” 智能合约
- - '####'
  - 注意
- - '###'
  - 在 Python 中编写 NEO “Hello, World” 智能合约
- - '###'
  - 将智能合约编译为 .avm 文件
- - '##'
  - 在私有测试网上发布智能合约
- - '##'
  - 发布到主网
- - '###'
  - 引导到主网
- - '###'
  - 安装 neo-gui 客户端
- - '##'
  - 以太坊对比 EOS 对比 NEO：智能合约开发者视角的对决
- - '##'
  - 下一步做什么
- - '##'
  - 摘要
- - '#'
  - 8. Hyperledger
- - '###'
  - 注意
- - '##'
  - Hyperledger 概述
- - '###'
  - Hyperledger
- - '##'
  - Hyperledger 框架
- - '###'
  - 理解 Hyperledger Fabric
- - '####'
  - Note
- - '##'
  - 安装 Hyperledger Fabric 和 Composer
- - '###'
  - 前提条件
- - '####'
  - 验证已安装的先决条件
- - '####'
  - 更新 Git
- - '####'
  - 安装 Node 版本管理器 (nvm)
- - '####'
  - 更新 Node.js
- - '###'
  - 安装带 Hyperledger Composer 扩展的 VSCode
- - '####'
  - Hyperledger Composer 必备 CLI 工具
- - '#####'
  - 注意
- - '###'
  - 使用 Docker 安装 Composer Playground
- - '###'
  - 安装 Hyperledger Fabric 开发服务器
- - '####'
  - 提示
- - '###'
  - 网络连接配置文件
- - '####'
  - fabric
- - '###'
  - 启动本地 Hyperledger Fabric 业务网络
- - '###'
  - 创建管理员身份证
- - '###'
  - 停止 Hyperledger Fabric
- - '####'
  - 注意
- - '##'
  - 重新创建 PeerAdmin 身份卡
- - '##'
  - Hyperledger Composer
- - '##'
  - 使用 Playground 实现“Hello, World”
- - '###'
  - 部署业务网络
- - '###'
  - 业务网络存档 (.bna)
- - '###'
  - 添加模型文件
- - '###'
  - 添加链码
- - '###'
  - 创建资产
- - '###'
  - 访问控制
- - '####'
  - 测试模型
- - '####'
  - 导入/导出模型
- - '###'
  - Playground 在线版
- - '####'
  - 使用 Yeoman 创建业务网络
- - '##'
  - 部署到本地 Hyperledger Fabric 网络
- - '##'
  - 运行 "hello-network" 网络
- - '###'
  - 启动“hello-network”业务网络和管理员卡
- - '###'
  - 导入业务卡
- - '##'
  - 后续方向
- - '##'
  - 错误排查
- - '###'
  - Composer 运行时安装错误或找不到卡
- - '###'
  - Docker 未授权认证错误
- - '###'
  - Docker 容器冲突错误
- - '####'
  - 提示
- - '###'
  - 版本不匹配与清理
- - '##'
  - 总结
- - '#'
  - 9. 使用 Angular 构建 Dapp：第一部分
- - '###'
  - 提示
- - '##'
  - 什么是 Dapp？
- - '###'
  - Dapp 的分类
- - '###'
  - DApp 项目
- - '###'
  - 如何创建你自己的 DApp？
- - '####'
  - 撰写白皮书
- - '#####'
  - 注意
- - '####'
  - 发起首次代币发行
- - '####'
  - 开发 DApp
- - '####'
  - 发布 DApp
- - '####'
  - 营销 DApp
- - '##'
  - 为什么选择 Angular？
- - '####'
  - 注意
- - '####'
  - 注意
- - '####'
  - 提示
- - '###'
  - 创建一个 Angular 去中心化应用
- - '####'
  - 前置条件
- - '####'
  - Angular CLI
- - '###'
  - 创建 Angular 项目
- - '####'
  - 启动应用
- - '####'
  - 使用 WebStorm 创建 Angular 项目
- - '#####'
  - 确保与 Angular CLI 版本不冲突
- - '####'
  - Angular 组件
- - '###'
  - 路由模块
- - '###'
  - 为 Angular 应用设置样式
- - '####'
  - Angular 样式架构
- - '####'
  - Angular Material
- - '####'
  - 安装 Angular Material
- - '####'
  - 导入 Angular Material 模块
- - '####'
  - 为你的 Angular Material 应用设置主题
- - '###'
  - 创建内容
- - '####'
  - 底部组件
- - '####'
  - 头部组件
- - '###'
  - 转账组件
- - '###'
  - Angular 指令
- - '##'
  - 总结
- - '#'
  - 10. 使用 Angular 构建去中心化应用：第二部分
- - '##'
  - 转账智能合约
- - '###'
  - 创建智能合约
- - '####'
  - 就这样。你保持了基础和简单，只有一个事件和一个函数。
- - '##'
  - 创建 Truffle 开发网络
- - '##'
  - 部署智能合约
- - '##'
  - Truffle 控制台
- - '###'
  - 账户
- - '###'
  - 测试智能合约的转账
- - '##'
  - 链接到以太坊网络
- - '##'
  - 转账服务
- - '##'
  - 连接 MetaMask
- - '##'
  - 测试你的 Dapp 功能
- - '##'
  - 后续方向
- - '##'
  - 本章小结
- - '#'
  - 11. 安全性与合规性
- - '##'
  - 安全性与合规性准备
- - '###'
  - 安全准备
- - '##'
  - 合规准备
- - '##'
  - 美国合规性
- - '###'
  - 注意事项
- - '##'
  - 欧盟合规
- - '###'
  - 提示
- - '##'
  - 就绪建议
- - '##'
  - 常见区块链攻击
- - '###'
  - 在线钱包钓鱼-恶意软件攻击
- - '####'
  - 事后分析
- - '###'
  - 键盘记录器恶意软件
- - '####'
  - 事后分析
- - '###'
  - 粉尘攻击
- - '####'
  - 事后分析
- - '###'
  - 热钱包攻击
- - '####'
  - 注意事项
- - '####'
  - 事后反思
- - '##'
  - 区块链网络攻击
- - '###'
  - Sybil 攻击
- - '####'
  - 注意
- - '####'
  - 事后反思
- - '####'
  - 注意
- - '###'
  - 双花或 51% 攻击
- - '####'
  - 事后反思
- - '###'
  - 矿工勒索软件
- - '####'
  - 注意
- - '####'
  - 事后分析
- - '###'
  - 对等网络的日蚀攻击
- - '####'
  - 事后分析
- - '###'
  - 路由攻击
- - '####'
  - 事后分析
- - '###'
  - 平台攻击
- - '###'
  - 凭证攻击
- - '####'
  - 事后分析
- - '##'
  - 安全实践指南
- - '###'
  - 避免恶意软件和勒索软件
- - '###'
  - 开发者安全实践
- - '###'
  - 个人开发电脑安全
- - '###'
  - 缺陷代码
- - '####'
  - 事后分析
- - '###'
  - 依赖包后门攻击
- - '####'
  - 事后分析
- - '##'
  - DoS 与 DDoS 攻击
- - '###'
  - 事后分析
- - '##'
  - 开发周期
- - '###'
  - 设计与编码
- - '###'
  - 发现、审计与测试
- - '####'
  - 发现阶段
- - '####'
  - 审计阶段
- - '##'
  - 安全审计
- - '##'
  - 合规审计
- - '###'
  - 测试阶段
- - '##'
  - 自动化工具
- - '##'
  - 就绪评估
- - '##'
  - 安全性与合规性评估
- - '##'
  - 发布
- - '##'
  - 后续方向
- - '##'
  - 总结
- - '#'
  - 12. 超越加密货币的区块链
- - '##'
  - 利用区块链
- - '##'
  - 币
- - '##'
  - 代币
- - '##'
  - 账本
- - '##'
  - 智能合约与去中心化应用
- - '##'
  - 行业与垂直领域的去中心化
- - '###'
  - 金融
- - '##'
  - 区块链应用场景
- - '###'
  - 金融服务
- - '###'
  - 网络安全
- - '###'
  - 房地产
- - '###'
  - 排版后的文本
- - '###'
  - 移动端
- - '###'
  - 供应链
- - '###'
  - 加密消息传递
- - '##'
  - 选举与投票
- - '##'
  - 市场营销
- - '###'
  - 医疗保健
- - '###'
  - 游戏
- - '##'
  - 区块链在游戏和音乐行业的应用
- - '###'
  - 游戏
- - '###'
  - 音乐
- - '##'
  - 区块链项目与资源
- - '###'
  - 区块链音乐平台
- - '##'
  - 下一步该去哪里
- - '##'
  - 总结
- - '#'
  - 索引
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '#'
  - 词汇表
- - '##'
  - A
- - '##'
  - B
- - '##'
  - C
- - '##'
  - D
- - '##'
  - E
- - '##'
  - F
- - '##'
  - G
- - '##'
  - H
- - '##'
  - I, J
- - '##'
  - K
- - '##'
  - L
- - '##'
  - M
- - '##'
  - N
- - '##'
  - O
- - '##'
  - P
- - '##'
  - Q
- - '##'
  - R
- - '##'
  - S
- - '##'
  - T
- - '##'
  - U
- - '##'
  - V
- - '##'
  - W
- - '##'
  - X, Y
- - '##'
  - Z
